import type { Workflow } from '../types';

/** Sign-in/MFA troubleshooting plus the cybersecurity workflows. */
export const IDENTITY_SECURITY_WORKFLOWS: Workflow[] = [
  {
    id: 'm365-signin-mfa',
    category: 'Microsoft 365',
    title: 'Sign-in, authentication and MFA problems',
    summary:
      'A user cannot sign in to Microsoft 365, is stuck in MFA prompts, or is blocked by policy. Separate credentials, MFA method, account state, Conditional Access and device state using the sign-in logs rather than guessing.',
    tags: ['sign-in', 'mfa', 'conditional access', 'entra', 'password', 'authentication'],
    symptoms: [
      'Repeated password prompts in Outlook, Teams or OneDrive',
      'MFA prompt never arrives, or the registered method is no longer available',
      'Message that access is blocked by the organisation’s policy',
      'Works in a browser but not in the desktop app (or the reverse)',
      'Account shows as locked or sign-in blocked',
    ],
    initialChecks: [
      'One user or several? If several, check Microsoft 365 service health first.',
      'Exact wording of the error and any request or correlation ID shown on screen.',
      'Which app, device and location? Did anything change recently (new phone, password change, travel, new laptop)?',
      'Have you verified the user’s identity using the client’s process before changing anything on the account?',
      'Are you authorised to view sign-in logs and change this user’s account?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Capture where and how it fails',
        detail: 'Record the app, the sign-in page wording, whether it is a browser or desktop app, the device, and the time of the last attempt. Never ask the user to read out a password or MFA code.',
        lookFor: 'Consistent failure across apps (account-level) versus one app or one device (client-level).',
        meaning: 'Account-wide failures point to account state, MFA or Conditional Access. One device points to cached credentials, device registration or clock problems.',
      },
      {
        id: 's2',
        title: 'Check service health',
        detail: 'In the Microsoft 365 admin centre review Service health for authentication or Exchange/Teams incidents. Exact menu names may differ slightly.',
        lookFor: 'Active incidents affecting sign-in or the affected service.',
        meaning: 'A live incident means waiting and communicating, not changing the user’s account.',
        ifAbnormal: 'If there is an incident, record the reference and update the ticket rather than making changes.',
      },
      {
        id: 's3',
        title: 'Review the account state',
        detail: 'In the admin centre open the user: is sign-in blocked, is a licence assigned, has the password expired or been changed, is the account recently created or moved?',
        lookFor: 'Blocked sign-in, missing licence, expired password, wrong UPN.',
        meaning: 'Any of these will stop sign-in or specific apps regardless of the device.',
        ifAbnormal: 'Correct only with authorisation, and record the before and after state.',
      },
      {
        id: 's4',
        title: 'Read the sign-in logs',
        detail: 'In the Entra admin centre open Sign-in logs, filter to the user and time of the failed attempt, and open the entry. Review status, failure reason, Conditional Access result, client app, device details and location.',
        lookFor: 'Failure reason text, which Conditional Access policy applied and whether it blocked or required something, and unfamiliar locations or client apps.',
        meaning: 'The log usually names the cause: wrong credentials, MFA not completed, policy requirement not met (e.g. compliant device), or legacy authentication blocked. Unexpected locations may indicate a compromise.',
        ifAbnormal: 'If sign-ins from unexpected places succeeded, treat it as a possible account compromise and follow that workflow.',
      },
      {
        id: 's5',
        title: 'Check registered authentication methods',
        detail: 'In the user’s authentication methods, see what is registered (authenticator app, phone, etc.) and whether the user still has that device or number.',
        lookFor: 'A method tied to a lost or replaced phone or an old number.',
        meaning: 'The user cannot satisfy MFA with a method they no longer have. This is a re-registration job, not a password job.',
        ifAbnormal: 'Follow the client’s identity-verification process before requiring re-registration.',
      },
      {
        id: 's6',
        title: 'Check device registration and time',
        detail: 'On the PC run `dsregcmd /status` and check AzureAdJoined / DomainJoined and the single sign-on state. Confirm the system date, time and time zone are correct.',
        commandIds: ['dsregcmd-status', 'whoami'],
        lookFor: 'Join state not matching expectation, SSO state showing no primary refresh token, or clock drift.',
        meaning: 'A device that is not registered as expected may fail compliant-device policies. Large clock drift breaks token validation.',
        ifAbnormal: 'Fix the clock first. Re-registering the device is a remediation step that needs authorisation.',
      },
      {
        id: 's7',
        title: 'Test from a clean context',
        detail: 'Try a private browser window or a different known-good device. If a desktop app loops, ask the user to sign out of the account in the app and sign in again.',
        lookFor: 'Whether a fresh session succeeds.',
        meaning: 'Success in a clean context confirms stale cached tokens or credentials on the original device.',
        ifAbnormal: 'If a clean context also fails, the problem is server-side (account, MFA, policy).',
      },
    ],
    causes: [
      { cause: 'Password changed or expired, stale cached credentials', indicators: 'Repeated prompts across apps after a password change; sign-in log shows invalid credentials.' },
      { cause: 'MFA method lost or changed', indicators: 'Prompt never arrives; user has a new phone; registered method no longer reachable.' },
      { cause: 'Conditional Access block or unmet requirement', indicators: 'Sign-in log shows a policy applied with failure (location, device compliance, app).' },
      { cause: 'Account blocked, unlicensed or recently changed', indicators: 'Admin centre shows blocked sign-in or missing licence.' },
      { cause: 'Device clock or registration problem', indicators: 'Only one device fails; dsregcmd shows unexpected state or the time is wrong.' },
    ],
    remediation: [
      { title: 'Reset the password through the authorised process', detail: 'Set a temporary password via the admin centre using the client’s procedure and require a change at next sign-in. Pass it to the user using the approved channel. Do not record it in tickets or ForgeTools.', caution: 'Verify identity first. A reset also invalidates cached passwords on every device.' },
      { title: 'Require MFA re-registration', detail: 'After identity verification, clear the old method so the user can register a new one on next sign-in.', caution: 'Locks the user out of MFA-protected resources until they re-register. Never do this on an unverified request.' },
      { title: 'Refresh sessions and cached sign-in', detail: 'Have the user sign out of the affected app and sign in again; revoke sessions in the admin centre if tokens are stale.', caution: 'Signs the user out everywhere.' },
      { title: 'Correct licence or account state', detail: 'Assign the missing licence or unblock the account where the client has approved it.', caution: 'If the account was blocked deliberately or after suspicious activity, do not unblock without checking why.' },
      { title: 'Raise a Conditional Access change request', detail: 'If policy is blocking a legitimate use, raise it with whoever owns the policy. Do not add broad exclusions as a quick fix.', caution: 'Policy changes affect security for all users and need change control.' },
    ],
    verification: [
      'User signs in to the affected app and completes MFA successfully',
      'Sign-in log shows a successful sign-in with the expected policy result',
      'The fix holds after the app or PC is restarted',
    ],
    documentation: [
      'Exact error message and when it occurred (no passwords or codes)',
      'Sign-in log failure reason and Conditional Access result',
      'How identity was verified before changes were made',
      'What was changed on the account or device and how to undo it',
    ],
    skills: ['m365', 'identity-access', 'troubleshooting', 'customer-support'],
  },
  {
    id: 'sec-account-compromise',
    category: 'Cybersecurity',
    title: 'Suspected account compromise',
    summary:
      'Signs that someone else may be using a user’s account. This is incident-response territory: confirm, contain through authorised admin actions, preserve evidence and escalate per the client’s or MSP’s process.',
    tags: ['compromise', 'phishing', 'inbox rules', 'mfa fatigue', 'incident', 'account takeover'],
    symptoms: [
      'Unexpected MFA prompts the user did not trigger',
      'Mail forwarding or inbox rules the user did not create',
      'Sign-ins from unfamiliar countries or devices',
      'Spam or phishing sent from the user’s mailbox',
      'The user entered credentials on a page they now doubt',
    ],
    initialChecks: [
      'Is there an incident or escalation process for this client? Know who to notify before you start.',
      'Are you authorised to act on this tenant and account? If unsure, escalate now.',
      'What did the user do or click, and when? Ask neutrally; this is not blame.',
      'Has anything already been changed (password reset, device wiped)? Avoid destroying evidence.',
      'Is sensitive data or a finance mailbox involved? That raises the urgency and who must be told.',
    ],
    steps: [
      {
        id: 's1',
        title: 'Record the report and start a timeline',
        detail: 'Write down who reported what, when, and the exact observations. Keep a running timeline of every action you take with times.',
        lookFor: 'A clear first-known time and the specific indicators reported.',
        meaning: 'A timeline supports scoping and any later formal review.',
      },
      {
        id: 's2',
        title: 'Review sign-in activity',
        detail: 'In the Entra admin centre review the user’s sign-in logs for locations, IP addresses, client apps and results around and before the reported time. Exact menu names may differ slightly.',
        lookFor: 'Successful sign-ins from unfamiliar places or devices, legacy protocols, or many failures followed by a success.',
        meaning: 'Successful unfamiliar sign-ins strongly suggest compromise. Only failures suggest attempted attacks that did not succeed.',
        ifAbnormal: 'Treat successful unfamiliar sign-ins as a confirmed incident and escalate immediately.',
      },
      {
        id: 's3',
        title: 'Check mailbox rules and forwarding',
        detail: 'In Outlook on the web or the Exchange admin centre review inbox rules and mailbox forwarding settings for the user. Look for rules that forward, delete or move messages to obscure folders.',
        lookFor: 'Rules or forwarding the user does not recognise, especially external addresses.',
        meaning: 'Attackers commonly hide their activity and exfiltrate mail with rules and forwarding.',
        ifAbnormal: 'Screenshot or export before removing anything, and record the rule details.',
      },
      {
        id: 's4',
        title: 'Review authentication methods and app consents',
        detail: 'Check the user’s registered authentication methods for entries they did not add, and review enterprise applications or consents granted by the user.',
        lookFor: 'Unknown phone numbers, authenticator registrations or third-party apps with mail access.',
        meaning: 'An attacker may have added their own MFA method or granted an app persistent access.',
        ifAbnormal: 'Escalate; removing consent and methods needs authorisation and should be recorded.',
      },
      {
        id: 's5',
        title: 'Look at the endpoint',
        detail: 'If the user may have run something malicious, check the device for unfamiliar software and run the Defender status check. See the suspicious software workflow for evidence collection.',
        commandIds: ['get-mpcomputerstatus', 'get-startup-commands'],
        lookFor: 'Protection disabled, recent unknown installs, remote access tools.',
        meaning: 'A compromised device means a password reset alone will not be enough.',
        ifAbnormal: 'Consider isolating the device per client policy, and do not wipe it before evidence decisions are made.',
      },
    ],
    causes: [
      { cause: 'Credential phishing', indicators: 'User entered details on a fake page; sign-ins from unusual location shortly after.' },
      { cause: 'MFA fatigue or push approval', indicators: 'Many prompts the user did not start, then a successful sign-in.' },
      { cause: 'Reused or breached password', indicators: 'Many failures then success, with no user phishing event.' },
      { cause: 'Malicious OAuth app consent', indicators: 'Unknown application with mail or file permissions granted by the user.' },
      { cause: 'Infected endpoint stealing tokens', indicators: 'Suspicious software or disabled protection on the user’s device.' },
    ],
    remediation: [
      { title: 'Contain the account', detail: 'Using authorised admin actions: block sign-in or reset the password, revoke active sessions, and review MFA methods. Follow the client’s procedure and verify who you are speaking to.', caution: 'Needs client authorisation. Containment disrupts the user, so tell them what is happening.' },
      { title: 'Remove attacker persistence', detail: 'After evidence is captured, remove malicious inbox rules, forwarding, unknown MFA methods and app consents.', caution: 'Capture details first. Removing items too early can destroy evidence.' },
      { title: 'Secure the device', detail: 'Isolate and scan the device, and involve the security lead before any rebuild.', caution: 'Do not wipe or reinstall until evidence and escalation decisions have been made.' },
      { title: 'Escalate and notify', detail: 'Notify the client contact and your escalation path per policy, including any data-protection reporting duties they may have.', caution: 'Reporting decisions belong to the client and your organisation, not to you alone.' },
    ],
    verification: [
      'No further unfamiliar sign-ins appear in the logs after containment',
      'Rules, forwarding, MFA methods and app consents are clean',
      'The device is scanned and cleared, or isolated pending decision',
      'The user has re-secured the account with verified methods',
    ],
    documentation: [
      'Timeline of events and your actions with times',
      'Evidence preserved (screenshots, exports) and where it is stored',
      'Who was notified and when',
      'What was changed and how to undo it',
    ],
    skills: ['incident-response', 'identity-access', 'security-monitoring', 'm365', 'documentation'],
  },
  {
    id: 'sec-endpoint-defender',
    category: 'Cybersecurity',
    title: 'Endpoint protection and Microsoft Defender problems',
    summary:
      'Protection is off, signatures are out of date, scans fail, or another antivirus product conflicts. Establish whether the device is managed and who controls the setting before changing anything.',
    tags: ['defender', 'antivirus', 'real-time protection', 'signatures', 'tamper protection', 'edr'],
    symptoms: [
      'Windows Security shows a red or yellow warning',
      'Real-time protection is off and will not stay on',
      'Signature updates fail or are old',
      'Scans do not complete or error',
      'Another antivirus product is installed alongside Defender',
    ],
    initialChecks: [
      'Is this device managed (Intune, group policy, third-party security tool)? Managed settings may be locked deliberately.',
      'Is another security product installed and licensed? Defender normally steps back when another AV is active.',
      'Did the warning appear after an update, install or removal of software?',
      'Are you authorised to change security settings on this device?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Check Windows Security overview',
        detail: 'Open Windows Security and review Virus & threat protection. Note any messages and whether settings are greyed out with an organisation-managed notice.',
        lookFor: 'Warnings, managed-by-organisation notices, and the active provider.',
        meaning: 'Greyed-out settings usually mean policy control; changes must go through the management tool.',
      },
      {
        id: 's2',
        title: 'Read the detailed Defender status',
        detail: 'In an elevated PowerShell run `Get-MpComputerStatus` and review the service and protection fields and the signature update times.',
        commandIds: ['get-mpcomputerstatus'],
        lookFor: 'AMServiceEnabled, AntivirusEnabled, RealTimeProtectionEnabled, signature ages and tamper protection state.',
        meaning: 'False values or old signatures confirm what the UI suggests. If Defender is passive because another product is active, that is expected.',
        ifAbnormal: 'If the service itself is not running, check the service state and Event Viewer for the cause.',
      },
      {
        id: 's3',
        title: 'Check for other security products',
        detail: 'Review installed apps and Windows Security > Security providers for third-party antivirus, including leftover trial versions.',
        lookFor: 'More than one active AV, or a stale product that is registered but not running.',
        meaning: 'Conflicts or leftovers can switch off Defender or leave the device unprotected.',
        ifAbnormal: 'Remove only products the client confirms are not in use, using the vendor’s removal tool.',
      },
      {
        id: 's4',
        title: 'Update signatures and run a scan',
        detail: 'Run `Update-MpSignature`, then start a quick scan with `Start-MpScan -ScanType QuickScan`, or use Windows Security.',
        commandIds: ['update-mpsignature', 'start-mpscan'],
        lookFor: 'Update success and scan completion with the result.',
        meaning: 'Failure to update can indicate connectivity, proxy or service issues. A completed clean scan is only a snapshot, not proof the device is safe.',
        ifAbnormal: 'If detections appear, stop and follow the suspicious software workflow before cleaning.',
      },
      {
        id: 's5',
        title: 'Review the Defender event log',
        detail: 'In Event Viewer open Applications and Services Logs > Microsoft > Windows > Windows Defender > Operational and look for errors around the time protection changed.',
        commandIds: ['get-winevent'],
        lookFor: 'Error events about disabled protection, failed updates or service stops.',
        meaning: 'Shows whether it was switched off by a person, a policy or a fault.',
      },
    ],
    causes: [
      { cause: 'Third-party antivirus is the active provider', indicators: 'Security providers lists another product; Defender shows passive mode.' },
      { cause: 'Policy or management tool controls the setting', indicators: 'Options greyed out with an organisation notice.' },
      { cause: 'Signature update failure', indicators: 'Old signature date; update command errors; connectivity or proxy trouble.' },
      { cause: 'Service stopped or corrupted', indicators: 'Defender service not running; event log errors.' },
      { cause: 'Protection deliberately disabled by a user or malware', indicators: 'Tamper protection off, protection was on earlier, unknown software present.' },
    ],
    remediation: [
      { title: 'Re-enable protection', detail: 'Turn real-time protection on in Windows Security, or correct the managing policy.', caution: 'If it was turned off unexpectedly, find out why before assuming it is a glitch.' },
      { title: 'Update signatures', detail: 'Run the signature update, fixing connectivity or proxy issues if it fails.' },
      { title: 'Resolve product conflicts', detail: 'Remove the unused security product using the vendor’s removal tool, then restart.', caution: 'Removing an active corporate security product leaves the device unprotected. Confirm with the client first.' },
      { title: 'Repair the service', detail: 'If Windows components are damaged, follow the system corruption workflow.', caution: 'Back up important data before repair actions.' },
    ],
    verification: [
      'Windows Security shows no warnings',
      'Get-MpComputerStatus shows protection enabled and recent signatures',
      'A scan completes successfully',
      'State persists after a restart',
    ],
    documentation: [
      'Which security product is the active provider',
      'Status values before and after the change',
      'Whether the device is managed and by what',
      'Anything that suggested the protection was turned off deliberately',
    ],
    skills: ['endpoint-security', 'windows', 'troubleshooting', 'security-monitoring'],
  },
  {
    id: 'sec-suspicious-software',
    category: 'Cybersecurity',
    title: 'Suspicious software or behaviour on a device',
    summary:
      'Unknown programs, browser hijacks, pop-ups, unexplained CPU or network use. Triage, collect information without destroying evidence, and escalate. Do not run unknown clean-up tools.',
    tags: ['malware', 'suspicious', 'unknown software', 'startup items', 'pop-ups', 'triage'],
    symptoms: [
      'Browser homepage or search engine changed unexpectedly',
      'Pop-ups or unwanted notifications',
      'High CPU, disk or network activity with no explanation',
      'Unknown programs or startup items',
      'Security alerts or protection switched off',
    ],
    initialChecks: [
      'Is the device on a work network or holding sensitive data? That influences isolation and escalation.',
      'What did the user install or click recently, and when did the symptoms start?',
      'Is there an incident process for this client? Know who to escalate to.',
      'Are you authorised to work on this device? Do not remove anything yet.',
    ],
    steps: [
      {
        id: 's1',
        title: 'Decide whether to isolate',
        detail: 'If the device may be actively compromised or handling sensitive data, consider disconnecting it from the network (unplug or disable Wi-Fi) per client policy before further work.',
        lookFor: 'Signs of active malicious activity or data exposure risk.',
        meaning: 'Isolation limits spread and exfiltration but also affects the user and any live evidence in memory.',
        ifAbnormal: 'Follow the incident process if you suspect active compromise.',
      },
      {
        id: 's2',
        title: 'Check protection state',
        detail: 'Run `Get-MpComputerStatus` and confirm protection is on and signatures are current.',
        commandIds: ['get-mpcomputerstatus'],
        lookFor: 'Disabled protection or very old signatures.',
        meaning: 'Disabled protection is a significant indicator and a risk in itself.',
      },
      {
        id: 's3',
        title: 'List running processes and connections',
        detail: 'Review `Get-Process` or `tasklist`, and use `netstat -ano` to map outbound connections to process IDs.',
        commandIds: ['get-process', 'tasklist', 'netstat-ano'],
        lookFor: 'Unfamiliar process names, odd locations, processes with outbound connections to unknown addresses.',
        meaning: 'A name alone proves nothing. Location, signature and behaviour matter. Many legitimate tools look unfamiliar.',
        ifAbnormal: 'Note the process name, PID and path rather than ending it straight away.',
      },
      {
        id: 's4',
        title: 'Review startup items and scheduled tasks',
        detail: 'Run `Get-CimInstance Win32_StartupCommand` and review `Get-ScheduledTask` for recently added or oddly named entries.',
        commandIds: ['get-startup-commands', 'get-scheduledtask'],
        lookFor: 'Items pointing to temp folders, user profile paths or scripts with random names.',
        meaning: 'Persistence mechanisms are a typical sign of unwanted software.',
      },
      {
        id: 's5',
        title: 'Hash and check suspicious files',
        detail: 'Use `Get-FileHash` on a suspect file and look the hash up using the client-approved reputation service. Do not upload files that may contain client data.',
        commandIds: ['get-filehash'],
        lookFor: 'A hash known as malicious or an unsigned file in an unusual location.',
        meaning: 'A known-bad hash confirms malware. Unknown means keep investigating, not safe.',
      },
      {
        id: 's6',
        title: 'Scan and escalate',
        detail: 'Run a full Defender scan if the client allows, and record detections. Escalate per the incident process before any clean-up on a possible compromise.',
        commandIds: ['start-mpscan'],
        lookFor: 'Detections and what was quarantined.',
        meaning: 'A detection suggests other components may remain. A clean scan does not rule out compromise.',
      },
    ],
    causes: [
      { cause: 'Bundled adware or potentially unwanted application', indicators: 'Installed with free software; browser settings changed; nothing deeper found.' },
      { cause: 'Browser extension hijack', indicators: 'Symptoms confined to the browser; unknown extensions.' },
      { cause: 'Remote access tool installed by a scammer', indicators: 'User recalls a call or pop-up leading to installing a remote tool.' },
      { cause: 'Malware with persistence', indicators: 'Unknown startup entries, protection disabled, outbound connections to unknown hosts.' },
      { cause: 'Legitimate software with high resource use', indicators: 'Known vendor, signed, expected location.' },
    ],
    remediation: [
      { title: 'Remove unwanted programs and extensions', detail: 'For confirmed adware or extensions, uninstall via Settings and reset the browser, with client approval.', caution: 'Capture a list of what was removed first.' },
      { title: 'Quarantine through Defender', detail: 'Let the security product quarantine detections and record what it removed.' },
      { title: 'Change credentials from a clean device', detail: 'If credentials may have been exposed, have the user change them from a different, clean device and follow the account compromise workflow.', caution: 'Changing passwords on an infected machine can hand them to the attacker.' },
      { title: 'Rebuild when trust is lost', detail: 'If persistence or a remote tool is confirmed, recommend a reimage and agree this with the client and security lead.', caution: 'Back up data selectively and scan it. Do not wipe before evidence decisions.' },
    ],
    verification: [
      'Unwanted behaviour has stopped after a reboot',
      'No unknown startup items, tasks or suspicious connections remain',
      'Protection is on, current, and a scan completes',
      'Escalation or decision about rebuild is recorded',
    ],
    documentation: [
      'What was observed and when it started',
      'Names, paths and hashes of suspicious items',
      'Whether the device was isolated and why',
      'What was removed and how to restore it if needed',
    ],
    skills: ['incident-response', 'endpoint-security', 'investigation', 'windows'],
  },
  {
    id: 'sec-local-admin-review',
    category: 'Cybersecurity',
    title: 'Local administrator review and least privilege',
    summary:
      'Find out who has administrator rights on a device and whether they should. Remediation reduces risk but needs authorisation and a rollback plan.',
    tags: ['local admin', 'least privilege', 'administrators group', 'laps', 'accounts'],
    symptoms: [
      'Standard users able to install software freely',
      'Unknown accounts in the Administrators group',
      'Shared local administrator password across devices',
      'Audit or security review requests an admin account list',
    ],
    initialChecks: [
      'Is the device domain-joined, Entra-joined or standalone? Admin rights may come from several places.',
      'Who is expected to be an administrator, according to the client?',
      'Is there a managed solution in use (LAPS, Intune policy)? Do not fight it locally.',
      'Are you authorised to change membership? Reviewing is read-only; changing is not.',
    ],
    steps: [
      {
        id: 's1',
        title: 'List the local Administrators group',
        detail: 'Run `net localgroup administrators` or `Get-LocalGroupMember -Group Administrators` in an elevated prompt.',
        commandIds: ['net-localgroup-administrators', 'get-localgroupmember'],
        lookFor: 'Members that are users, groups and the built-in Administrator.',
        meaning: 'Domain or Entra groups may appear as members and hide the people behind them.',
      },
      {
        id: 's2',
        title: 'List local accounts',
        detail: 'Run `Get-LocalUser` and note which are enabled, including the built-in Administrator and any unfamiliar accounts.',
        commandIds: ['get-localuser', 'net-user'],
        lookFor: 'Enabled accounts nobody can explain, and old accounts from former staff.',
        meaning: 'Unexplained enabled accounts are a risk and need investigation.',
      },
      {
        id: 's3',
        title: 'Check the current user’s rights',
        detail: 'Run `whoami /groups` to see the groups and elevation state of the current user.',
        commandIds: ['whoami-all'],
        lookFor: 'Membership of Administrators and whether the token is elevated.',
        meaning: 'Everyday accounts running with admin rights increase impact of malware or mistakes.',
      },
      {
        id: 's4',
        title: 'Check how admin rights are managed',
        detail: 'Find out whether Windows LAPS or another tool manages the built-in Administrator password, and whether Intune or group policy controls Administrators membership.',
        lookFor: 'Evidence of managed local admin passwords, or a shared static one.',
        meaning: 'A shared static local admin password allows lateral movement if one device is compromised.',
        ifAbnormal: 'Raise the recommendation to adopt LAPS rather than inventing a local workaround.',
      },
    ],
    causes: [
      { cause: 'Admin rights granted for convenience and never removed', indicators: 'Everyday user accounts in Administrators.' },
      { cause: 'Leftover accounts from previous staff or vendors', indicators: 'Enabled accounts that nobody recognises.' },
      { cause: 'Shared built-in Administrator password', indicators: 'Same credential used on many devices; no LAPS.' },
      { cause: 'Admin rights inherited through a domain or Entra group', indicators: 'Group members in the local list.' },
    ],
    remediation: [
      { title: 'Remove unnecessary admin membership', detail: 'Move everyday users to Standard and provide a separate admin or elevation process for approved tasks.', caution: 'Needs authorisation, and users may lose the ability to install software. Record the old membership so it can be restored.' },
      { title: 'Disable unused accounts', detail: 'Disable rather than delete stale accounts first, and delete later once confirmed unused.', caution: 'Check nothing depends on the account (services, scheduled tasks).' },
      { title: 'Recommend LAPS', detail: 'Propose Windows LAPS (or an equivalent) for managing the built-in administrator password.' },
    ],
    verification: [
      'Administrators list matches what the client approved',
      'Standard users can still do their normal work',
      'Documented rollback exists and is tested where practical',
    ],
    documentation: [
      'List of members before and after',
      'Authorisation for the change and who gave it',
      'Accounts disabled or removed',
      'Recommendations made (e.g. LAPS)',
    ],
    skills: ['identity-access', 'endpoint-security', 'windows', 'documentation'],
  },
  {
    id: 'sec-encryption-secureboot',
    category: 'Cybersecurity',
    title: 'Encryption, TPM and Secure Boot checks',
    summary:
      'Verify BitLocker status, TPM readiness and Secure Boot, and make sure recovery keys are safely escrowed before any change. Never disable Secure Boot or encryption as a convenience.',
    tags: ['bitlocker', 'tpm', 'secure boot', 'encryption', 'recovery key', 'uefi'],
    symptoms: [
      'Device prompts for a BitLocker recovery key after a hardware or firmware change',
      'Windows reports that BitLocker is off or suspended',
      'Secure Boot is reported as off or unsupported',
      'Security review requires proof of encryption',
    ],
    initialChecks: [
      'Is the recovery key stored somewhere you can retrieve it (Entra ID, Active Directory, client record)? Confirm before changing anything.',
      'Is the device managed? Encryption policy may come from Intune or group policy.',
      'Are you about to change firmware, hardware or boot settings? BitLocker may require recovery afterwards.',
      'Are you authorised to change security settings on this device?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Check BitLocker status',
        detail: 'In an elevated prompt run `manage-bde -status` and note the protection status and conversion status for each volume.',
        commandIds: ['manage-bde-status'],
        lookFor: 'Protection On, encryption percentage, and key protector types.',
        meaning: 'Protection Off or a partial conversion means the data is not fully protected.',
        ifAbnormal: 'Check whether it is suspended, in progress, or never enabled.',
      },
      {
        id: 's2',
        title: 'Check the TPM',
        detail: 'Run `Get-Tpm` in an elevated PowerShell prompt.',
        commandIds: ['get-tpm'],
        lookFor: 'TpmPresent and TpmReady true.',
        meaning: 'No ready TPM means BitLocker needs other protectors or the TPM must be enabled in firmware.',
      },
      {
        id: 's3',
        title: 'Check Secure Boot',
        detail: 'Run `Confirm-SecureBootUEFI` or check System Information (msinfo32) for Secure Boot State and BIOS Mode.',
        commandIds: ['confirm-securebootuefi'],
        lookFor: 'True, or Secure Boot State On with BIOS Mode UEFI.',
        meaning: 'An error on a legacy BIOS system means the device is not running UEFI. False means Secure Boot is off.',
        ifAbnormal: 'Enabling Secure Boot may need a conversion to UEFI. Plan it with a backup and key escrow.',
      },
      {
        id: 's4',
        title: 'Confirm recovery key escrow',
        detail: 'Check the recovery key is stored where the client expects (for example Entra ID or Active Directory) and that it matches the key protector ID shown on the device.',
        lookFor: 'A recovery key present and matching.',
        meaning: 'Without a retrievable key, a recovery prompt can mean permanent data loss.',
        ifAbnormal: 'Escrow the key per the client’s process before any further change.',
      },
    ],
    causes: [
      { cause: 'Encryption never enabled or not enforced by policy', indicators: 'Status shows protection off.' },
      { cause: 'Protection suspended after an update or firmware change', indicators: 'Status shows suspended.' },
      { cause: 'TPM disabled or missing', indicators: 'Get-Tpm shows not present or not ready.' },
      { cause: 'Legacy BIOS install', indicators: 'Secure Boot query fails; BIOS Mode shows legacy.' },
    ],
    remediation: [
      { title: 'Enable or resume BitLocker', detail: 'Turn on encryption through the managed policy or the BitLocker control, and ensure the key is escrowed.', caution: 'Encryption can take time and uses CPU. Escrow the key first.' },
      { title: 'Suspend before firmware changes', detail: 'Before BIOS or firmware updates, suspend BitLocker (for example with Suspend-BitLocker and a reboot count) and resume afterwards.', caution: 'Suspended protection leaves the drive readable. Resume promptly.' },
      { title: 'Enable the TPM in firmware', detail: 'Enable the TPM in firmware settings if present but disabled.', caution: 'Firmware changes can trigger recovery. Have the key available.' },
      { title: 'Plan a UEFI conversion', detail: 'If the device is on legacy BIOS, schedule a supported conversion or reimage.', caution: 'Back up first. Conversion errors can leave the device unbootable.' },
    ],
    verification: [
      'manage-bde -status shows protection on and fully encrypted',
      'TPM is present and ready',
      'Secure Boot reports enabled',
      'Recovery key is escrowed and verified',
    ],
    documentation: [
      'Status values before and after',
      'Where the recovery key is stored (never the key itself)',
      'Firmware or hardware changes made',
      'Authorisation for the change',
    ],
    skills: ['endpoint-security', 'cryptography', 'windows', 'hardware'],
  },
];
