import type { Workflow } from '../types';

/** Networking and printer workflows. Printer content is manufacturer-agnostic: always defer to the model's service manual. */
export const NETWORK_PRINTER_WORKFLOWS: Workflow[] = [
  // =========================================================== NETWORKING
  {
    id: 'net-no-internet',
    category: 'Networking',
    title: 'No internet access',
    summary:
      'A device or site cannot reach the internet. Work up the layers (link, IP address, gateway, DNS, upstream) and establish scope first so you do not chase a single-device fault when the router or ISP is down.',
    tags: ['no internet', 'offline', 'connectivity', 'gateway', 'isp', 'dns'],
    symptoms: [
      'Browser says there is no internet or the page cannot be reached',
      'Network icon shows a warning or "no internet"',
      'Some sites or apps work and others do not',
      'Works on mobile data or another device but not this one',
      'Everything stopped at the same time for several people',
    ],
    initialChecks: [
      'One device, several, or the whole site? Establish scope before touching anything.',
      'Wired or wireless? Is the link light/Wi-Fi connected?',
      'Did anything change recently (power cut, router change, new device, updates)?',
      'Can another device on the same network get out? Can this device get out on a different network?',
      'Are you authorised to change settings on the router or switch? Do not reboot shared equipment without telling the client.',
    ],
    steps: [
      {
        id: 's1',
        title: 'Confirm the link',
        detail: 'Check the cable and port lights, or the Wi-Fi connection state. Confirm airplane mode is off and the adapter is enabled.',
        lookFor: 'Link up with activity lights, or Wi-Fi shown as connected to the correct network.',
        meaning: 'No link means a physical, adapter or Wi-Fi association problem. Link up moves the problem to IP or beyond.',
      },
      {
        id: 's2',
        title: 'Check IP configuration',
        detail: 'Run `ipconfig /all` and read the IPv4 address, subnet mask, default gateway, DHCP server and DNS servers for the active adapter.',
        commandIds: ['ipconfig-all', 'get-netipconfiguration'],
        lookFor: 'A sensible address on the right subnet, a default gateway, and DNS servers. 169.254.x.x means DHCP failed.',
        meaning: 'A self-assigned 169.254 address means the device did not receive a lease. A correct address with no gateway breaks routing.',
        ifAbnormal: 'Go to the DHCP/IP/gateway workflow.',
      },
      {
        id: 's3',
        title: 'Ping the default gateway',
        detail: 'Ping the default gateway address shown in ipconfig.',
        commandIds: ['ping'],
        lookFor: 'Replies with low latency, or timeouts.',
        meaning: 'Replies mean the local link works. Timeouts mean the gateway is unreachable from here or blocks ping. Compare with another device.',
        ifAbnormal: 'Check the cable, port, VLAN or Wi-Fi association and the gateway device.',
      },
      {
        id: 's4',
        title: 'Ping an external IP address',
        detail: 'Ping a well-known public IP such as 1.1.1.1 or 8.8.8.8.',
        commandIds: ['ping'],
        lookFor: 'Replies, or timeouts while the gateway replied.',
        meaning: 'Gateway reachable but external IP failing points past the router: ISP, WAN link, NAT or firewall.',
        ifAbnormal: 'Check the router WAN status and whether other devices are also offline.',
      },
      {
        id: 's5',
        title: 'Test name resolution',
        detail: 'Run `nslookup example.com` and then try a ping by name.',
        commandIds: ['nslookup', 'ping'],
        lookFor: 'A resolved IP address, or a DNS failure while IP pings worked.',
        meaning: 'IP works but names fail means DNS. Go to the DNS workflow.',
      },
      {
        id: 's6',
        title: 'Trace the path',
        detail: 'Run `tracert 1.1.1.1` to see where packets stop.',
        commandIds: ['tracert'],
        lookFor: 'The last responding hop before timeouts.',
        meaning: 'Stopping at the first hop points to the gateway; later hops point to the ISP or beyond. Some hops simply do not reply to trace requests.',
      },
    ],
    causes: [
      { cause: 'Physical link or Wi-Fi association problem', indicators: 'No link lights, adapter disabled, not connected to Wi-Fi.' },
      { cause: 'DHCP failure', indicators: '169.254.x.x address; no gateway or DNS shown.' },
      { cause: 'Gateway or router fault', indicators: 'Gateway does not reply; several devices affected.' },
      { cause: 'ISP or WAN outage', indicators: 'Gateway replies but external IPs fail for all devices.' },
      { cause: 'DNS failure', indicators: 'IP pings succeed; names do not resolve.' },
      { cause: 'Wrong proxy, VPN or firewall setting on the device', indicators: 'Other devices on the same network work; this one does not.' },
    ],
    remediation: [
      { title: 'Fix the physical or Wi-Fi link', detail: 'Reseat or replace the cable, change port, re-join Wi-Fi, enable the adapter.' },
      { title: 'Renew the lease', detail: 'Run `ipconfig /release` then `ipconfig /renew`.', caution: 'Briefly drops the connection. Do not run this over a remote session to the same adapter unless you can reconnect.' },
      { title: 'Restart the router or switch', detail: 'With the client’s agreement, power-cycle the affected network device and wait for it to come fully back.', caution: 'Disrupts everyone on that device. Warn the client first.' },
      { title: 'Engage the ISP', detail: 'If the gateway is healthy but nothing external works for all devices, log a fault with the ISP with times and results of your tests.' },
      { title: 'Reset the network stack', detail: 'As a late step use `netsh winsock reset` and `netsh int ip reset`, then reboot.', caution: 'Record static IP settings first; these reset network configuration and can remove VPN client hooks.' },
    ],
    verification: [
      'Device has a valid IP, gateway and DNS',
      'Gateway and external IP pings succeed',
      'Websites and business apps load',
      'The fix survives a reboot',
    ],
    documentation: [
      'Scope: which devices were affected',
      'ipconfig results (redact addresses where unnecessary)',
      'Where the path broke (link, gateway, WAN, DNS)',
      'What was changed and the time connectivity returned',
    ],
    skills: ['networking', 'troubleshooting', 'problem-solving', 'documentation'],
    tree: {
      start: 'scope',
      nodes: [
        {
          id: 'scope',
          prompt: 'Is anything else on the same network also offline?',
          help: 'Check another device on the same Wi-Fi or switch.',
          options: [
            { label: 'Yes, several devices or the whole site', next: 'gateway-ok' },
            { label: 'No, only this device', next: 'link' },
          ],
        },
        {
          id: 'gateway-ok',
          prompt: 'Can you ping the default gateway from an affected device?',
          options: [
            { label: 'Yes, the gateway replies', next: 'external-ip' },
            { label: 'No', next: 'gateway-down' },
          ],
        },
        {
          id: 'gateway-down',
          prompt: 'Is the router or switch powered with normal lights?',
          options: [
            { label: 'No or abnormal lights', conclusion: 'Likely a power or hardware fault on the router/switch. Check power and cabling, then power-cycle with the client’s agreement. If it remains down, escalate for replacement.' },
            { label: 'Looks normal', conclusion: 'Check the uplink cable/port, VLAN or Wi-Fi radio. Test with a known-good cable and a direct connection to the router. Record results and escalate to whoever manages the network.' },
          ],
        },
        {
          id: 'external-ip',
          prompt: 'Can affected devices ping a public IP such as 1.1.1.1?',
          options: [
            { label: 'No', conclusion: 'The problem is upstream of the router: ISP, WAN link or router NAT. Check the router WAN status page and log a fault with the ISP including times and test results.' },
            { label: 'Yes, but websites fail', next: 'dns-names' },
          ],
        },
        {
          id: 'dns-names',
          prompt: 'Does `nslookup example.com` return an address?',
          options: [
            { label: 'No', conclusion: 'DNS failure. Check the DNS servers on the clients and router, test an alternative resolver with nslookup, and follow the DNS workflow.' },
            { label: 'Yes', conclusion: 'Name resolution is fine. Look at proxy, firewall or content filtering, and test specific sites or ports with Test-NetConnection.' },
          ],
        },
        {
          id: 'link',
          prompt: 'Does the device have link (cable lights or Wi-Fi connected)?',
          options: [
            { label: 'No', conclusion: 'A link problem on this device: check cable, port, adapter enabled and Wi-Fi join. Try a different cable or port or network.' },
            { label: 'Yes', next: 'ip-check' },
          ],
        },
        {
          id: 'ip-check',
          prompt: 'What does ipconfig show for the IPv4 address?',
          options: [
            { label: '169.254.x.x (self-assigned)', conclusion: 'DHCP lease failed. Try `ipconfig /renew`, check the DHCP server and the port/VLAN, and follow the DHCP workflow.' },
            { label: 'A normal address on the right subnet', next: 'gw-local' },
            { label: 'A normal address but on the wrong subnet', conclusion: 'Wrong network or stale static settings. Check the VLAN/SSID, set the adapter to DHCP if intended, and check for a rogue DHCP source.' },
          ],
        },
        {
          id: 'gw-local',
          prompt: 'Can this device ping its default gateway?',
          options: [
            { label: 'No', conclusion: 'Local path problem: check VLAN, port security, firewall or an incorrect gateway address. Compare with a working device on the same switch.' },
            { label: 'Yes', next: 'ext-local' },
          ],
        },
        {
          id: 'ext-local',
          prompt: 'Can this device ping 1.1.1.1 and resolve names?',
          options: [
            { label: 'Pings work, names fail', conclusion: 'Device DNS issue. Check DNS servers set on the adapter, try `ipconfig /flushdns`, and compare with a working device.' },
            { label: 'Neither works but others do', conclusion: 'Device-specific block: VPN client, proxy, firewall rule or a damaged network stack. Disconnect VPN, check proxy settings, and as a late step reset the stack with the caution noted.' },
            { label: 'Both work', conclusion: 'Connectivity is fine from the OS level. Check the specific app, browser profile, proxy settings or content filter.' },
          ],
        },
      ],
    },
  },
  {
    id: 'net-dns',
    category: 'Networking',
    title: 'DNS problems',
    summary:
      'Names do not resolve, resolve to the wrong address, or only fail on some networks or over VPN. Prove whether IP connectivity works, then check which DNS servers are used and what they return.',
    tags: ['dns', 'nslookup', 'name resolution', 'flush dns', 'vpn', 'split dns'],
    symptoms: [
      'Browser reports the server could not be found',
      'Pinging by name fails but pinging by IP works',
      'A site goes to the wrong place or an old address',
      'Internal names fail only when on VPN',
      'Works on one network but not another',
    ],
    initialChecks: [
      'Does connectivity by IP address work (ping 1.1.1.1)?',
      'Is it all names, only internal names, or one site?',
      'Which DNS servers does the device use (ipconfig /all)?',
      'Is the device on a VPN or using a custom DNS setting?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Prove IP connectivity first',
        detail: 'Ping a public IP such as 1.1.1.1. If that fails, solve connectivity first.',
        commandIds: ['ping'],
        lookFor: 'Replies by IP.',
        meaning: 'If IP works but names do not, DNS is the likely layer.',
      },
      {
        id: 's2',
        title: 'Check which DNS servers are in use',
        detail: 'Run `ipconfig /all` and note the DNS Servers listed for the active adapter.',
        commandIds: ['ipconfig-all'],
        lookFor: 'Expected internal or ISP resolvers, not unusual addresses.',
        meaning: 'Wrong or unreachable DNS servers are a leading cause. Public resolvers on domain-joined PCs often break internal names.',
        ifAbnormal: 'Compare with a working device and the DHCP scope options.',
      },
      {
        id: 's3',
        title: 'Query a specific server',
        detail: 'Run `nslookup example.com` then `nslookup example.com <dns-server>` to ask a specific server directly.',
        commandIds: ['nslookup'],
        lookFor: 'Whether the configured server answers and what it returns.',
        meaning: 'Timeouts mean the server is unreachable or not answering. Different answers between servers indicate inconsistent DNS data.',
      },
      {
        id: 's4',
        title: 'Inspect the local DNS cache',
        detail: 'Run `ipconfig /displaydns` and look for the problem name.',
        commandIds: ['ipconfig-displaydns'],
        lookFor: 'A stale or wrong cached record, or a cached failure.',
        meaning: 'A bad cached entry can persist after the real record is fixed.',
      },
      {
        id: 's5',
        title: 'Flush and retest',
        detail: 'Run `ipconfig /flushdns` and test the name again.',
        commandIds: ['ipconfig-flushdns'],
        lookFor: 'Whether behaviour changes after the cache is cleared.',
        meaning: 'If it fixes it, the cache held stale data. If not, the server is returning the bad answer.',
      },
      {
        id: 's6',
        title: 'Check the hosts file and VPN',
        detail: 'Review the hosts file in `C:\\Windows\\System32\\drivers\\etc` for overrides, and test with the VPN disconnected and connected.',
        lookFor: 'Manual entries for the problem name, or behaviour that changes with the VPN.',
        meaning: 'Hosts entries override DNS. VPN split DNS often decides which server answers internal names.',
      },
    ],
    causes: [
      { cause: 'Wrong or unreachable DNS server configured', indicators: 'nslookup to the configured server times out.' },
      { cause: 'Stale cache', indicators: 'Flush fixes it, or cached record differs from the live answer.' },
      { cause: 'DNS record missing or incorrect on the server', indicators: 'The server returns no or wrong data for everyone.' },
      { cause: 'VPN split DNS misconfiguration', indicators: 'Internal names fail only on VPN.' },
      { cause: 'Hosts file override', indicators: 'A manual entry exists for the name.' },
    ],
    remediation: [
      { title: 'Correct the DNS servers', detail: 'Set the adapter to obtain DNS automatically (or the correct servers) and fix the DHCP option if the source is wrong.', caution: 'Changing DHCP options affects all clients. Get approval.' },
      { title: 'Flush the cache', detail: 'Run `ipconfig /flushdns`.' },
      { title: 'Fix the server record', detail: 'Correct or add the record on the authoritative DNS server, with the owner’s agreement, and allow for TTL.', caution: 'Changes to DNS can affect many users; record the previous value.' },
      { title: 'Remove stale hosts entries', detail: 'Delete overrides that are no longer intended.', caution: 'Make sure the entry was not added deliberately.' },
    ],
    verification: [
      'nslookup returns the expected address',
      'The site or service opens by name',
      'The fix works after reboot and with the VPN state the user normally uses',
    ],
    documentation: [
      'DNS servers used before and after',
      'nslookup results (redacted where appropriate)',
      'Whether cache, server or VPN was the cause',
      'Any record or DHCP change made and how to undo it',
    ],
    skills: ['networking', 'troubleshooting', 'windows', 'documentation'],
  },
  {
    id: 'net-dhcp-ip-gateway',
    category: 'Networking',
    title: 'DHCP, IP configuration and gateway problems',
    summary:
      'A device has a 169.254 address, the wrong subnet, a duplicate address, or cannot reach its gateway. Establish whether DHCP is working, whether the lease is correct, and whether the path to the gateway is healthy.',
    tags: ['dhcp', 'apipa', '169.254', 'ip conflict', 'gateway', 'subnet', 'rogue dhcp'],
    symptoms: [
      'Address starts with 169.254',
      'Duplicate IP address warning',
      'Device is on an unexpected subnet',
      'Cannot reach the default gateway',
      'Intermittent connectivity for one device after a lease change',
    ],
    initialChecks: [
      'Is it one device or several? Many devices suggests the DHCP server or scope.',
      'Wired or wireless, and which VLAN or SSID should it be on?',
      'Is the address meant to be static or from DHCP?',
      'Did anything change recently (new router, new access point, scope change)?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Read the full configuration',
        detail: 'Run `ipconfig /all` and note address, mask, gateway, DHCP server, lease times and whether DHCP is enabled.',
        commandIds: ['ipconfig-all', 'get-netipconfiguration'],
        lookFor: 'DHCP enabled, a lease from the expected server, and a correct subnet.',
        meaning: 'DHCP enabled with a 169.254 address means no server answered. A different DHCP server from expected may be rogue.',
      },
      {
        id: 's2',
        title: 'Request a new lease',
        detail: 'Run `ipconfig /release` and `ipconfig /renew`.',
        commandIds: ['ipconfig-release-renew'],
        lookFor: 'A valid address on the right subnet after renewing.',
        meaning: 'Success means the earlier failure was transient or stale. Failure means DHCP is unreachable or exhausted.',
        ifAbnormal: 'Test with a known-good cable/port or another SSID, and check the DHCP server.',
      },
      {
        id: 's3',
        title: 'Test the gateway',
        detail: 'Ping the default gateway and check the neighbour table with `arp -a`.',
        commandIds: ['ping', 'arp-a'],
        lookFor: 'Gateway replies and a MAC address entry for the gateway IP.',
        meaning: 'No reply with an incomplete ARP entry suggests a layer-2 or VLAN problem.',
      },
      {
        id: 's4',
        title: 'Check for address conflicts',
        detail: 'If Windows reports a conflict, use `arp -a` and compare MAC addresses for the IP, and check whether a static address overlaps the DHCP scope.',
        commandIds: ['arp-a', 'getmac'],
        lookFor: 'Two different MAC addresses claiming the same IP, or a static IP inside the DHCP pool.',
        meaning: 'Static addresses inside the pool, or a device with a stale static setting, cause conflicts.',
      },
      {
        id: 's5',
        title: 'Inspect routes',
        detail: 'Run `route print` to check the default route and metrics.',
        commandIds: ['route-print'],
        lookFor: 'One sensible default route; multiple adapters competing.',
        meaning: 'A VPN or second adapter can take precedence and break access.',
      },
    ],
    causes: [
      { cause: 'DHCP server unreachable or scope exhausted', indicators: 'Many devices with 169.254 addresses; lease requests time out.' },
      { cause: 'Wrong VLAN or SSID', indicators: 'Address from an unexpected subnet.' },
      { cause: 'Rogue DHCP server', indicators: 'DHCP server in ipconfig is not the expected one.' },
      { cause: 'Static address conflict', indicators: 'Conflict warnings; static IP inside the pool.' },
      { cause: 'Faulty cable, port or adapter', indicators: 'Intermittent link; works on another port.' },
    ],
    remediation: [
      { title: 'Renew the lease', detail: 'Release and renew, or disable and re-enable the adapter.', caution: 'Drops the connection briefly. Not over remote access to the same adapter.' },
      { title: 'Fix the port or VLAN', detail: 'Correct the switch port VLAN or Wi-Fi SSID with the network owner’s approval.', caution: 'Switch changes affect other devices. Record the old setting.' },
      { title: 'Resolve the conflict', detail: 'Move static addresses out of the DHCP pool or use DHCP reservations.', caution: 'Document the addressing plan before changing.' },
      { title: 'Remove a rogue DHCP source', detail: 'Identify the device by its MAC address and disconnect or reconfigure it, escalating if it is not yours to change.' },
      { title: 'Reset TCP/IP', detail: 'As a late step run `netsh int ip reset` and reboot.', caution: 'Resets IP configuration and may remove static settings. Record them first.' },
    ],
    verification: [
      'Device holds a valid lease on the correct subnet',
      'Gateway and internet pings succeed',
      'No conflict warnings after a reboot',
    ],
    documentation: [
      'ipconfig /all output (redacted)',
      'DHCP server that issued the lease',
      'Cause: scope, VLAN, conflict, rogue or hardware',
      'What was changed and how to roll it back',
    ],
    skills: ['networking', 'troubleshooting', 'network-security', 'documentation'],
  },
  {
    id: 'net-wifi',
    category: 'Networking',
    title: 'Wi-Fi problems',
    summary:
      'A device cannot join, drops, or is slow on Wi-Fi. Separate client faults (driver, power saving, saved profile) from environmental faults (signal, interference, access point, authentication).',
    tags: ['wifi', 'wireless', 'drops', 'signal', 'authentication', 'adapter'],
    symptoms: [
      'Cannot find or join the network',
      'Connects then drops repeatedly',
      'Weak signal or slow speeds only on Wi-Fi',
      'Authentication failure or repeated password prompt',
      'Works on 2.4GHz but not 5GHz (or the reverse)',
    ],
    initialChecks: [
      'Is it one device or several? Several suggests the access point or controller.',
      'Where is the device relative to the access point? Does it happen in one location?',
      'Does a phone or another laptop work in the same place?',
      'Did a driver update, Windows update or network change happen recently?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Check connection details',
        detail: 'Run `netsh wlan show interfaces` and note SSID, signal, radio type, channel and state.',
        commandIds: ['netsh-wlan-show-interfaces'],
        lookFor: 'Signal percentage, band/channel and whether it is associated.',
        meaning: 'Weak signal indicates range or obstruction. The radio type shows which standard the link negotiated.',
      },
      {
        id: 's2',
        title: 'Compare with another device',
        detail: 'Test a known-good device at the same spot on the same SSID.',
        lookFor: 'Whether the other device sees a strong signal and gets online.',
        meaning: 'If it works, the problem is local to the affected device. If not, suspect the access point or the location.',
      },
      {
        id: 's3',
        title: 'Generate the WLAN report',
        detail: 'In an elevated prompt run `netsh wlan show wlanreport` and open the generated HTML report.',
        commandIds: ['netsh-wlan-report'],
        lookFor: 'Disconnect reasons, session durations and error patterns.',
        meaning: 'Repeated disconnect reasons point to authentication, roaming or driver issues.',
      },
      {
        id: 's4',
        title: 'Check the adapter and driver',
        detail: 'In Device Manager review the adapter for errors, and check driver date and version. Look at Power Management settings for the adapter.',
        lookFor: 'Warning icons, very old drivers, and power saving that allows the device to turn off the adapter.',
        meaning: 'Drivers and power saving cause many intermittent drops.',
      },
      {
        id: 's5',
        title: 'Forget and rejoin the network',
        detail: 'Forget the saved profile and join again, entering credentials only on the sign-in prompt.',
        lookFor: 'Whether a fresh profile connects.',
        meaning: 'A corrupted or outdated saved profile (for example after a password change) causes authentication loops.',
      },
      {
        id: 's6',
        title: 'Check the access point side',
        detail: 'With access, review the AP or controller for client count, channel utilisation, signal and any errors for this client.',
        lookFor: 'Overloaded APs, channel interference, or the client being rejected.',
        meaning: 'Congestion and interference reduce reliability regardless of the client.',
      },
    ],
    causes: [
      { cause: 'Weak signal or interference', indicators: 'Low signal; problems in one location; other devices also slow.' },
      { cause: 'Outdated or faulty driver', indicators: 'Frequent disconnects in the WLAN report; adapter errors.' },
      { cause: 'Adapter power saving', indicators: 'Drops after idle or on battery.' },
      { cause: 'Stale saved profile or changed password', indicators: 'Authentication failure; rejoin works.' },
      { cause: 'Overloaded or misconfigured access point', indicators: 'Many clients, high utilisation, roaming issues.' },
    ],
    remediation: [
      { title: 'Forget and rejoin', detail: 'Remove the profile and connect again.' },
      { title: 'Update or roll back the driver', detail: 'Install the manufacturer driver, or roll back if the problem began after an update.', caution: 'Create a restore point or note the current version first.' },
      { title: 'Disable adapter power saving', detail: 'Untick the option that allows the computer to turn off the device to save power.' },
      { title: 'Improve placement or channel plan', detail: 'Move the device or AP, or review the channel plan with the network owner.', caution: 'AP changes affect all users. Get approval.' },
      { title: 'Reset the network stack', detail: 'If nothing else works, use `netsh winsock reset` and reboot.', caution: 'May remove VPN client hooks. Record settings first.' },
    ],
    verification: [
      'Device connects and stays connected over a monitoring period',
      'Signal is acceptable at the working location',
      'Speed and access are normal',
    ],
    documentation: [
      'SSID, band and signal observed',
      'WLAN report findings',
      'Driver version before and after',
      'Environmental factors noted',
    ],
    skills: ['networking', 'troubleshooting', 'hardware', 'customer-support'],
  },
  {
    id: 'net-slow-packet-loss',
    category: 'Networking',
    title: 'Slow network and packet loss',
    summary:
      'Network feels slow or drops packets. Use measurement, not feel: compare wired and wireless, local and external targets, and use pathping to find where loss or latency starts.',
    tags: ['slow network', 'latency', 'packet loss', 'pathping', 'bandwidth', 'duplex'],
    symptoms: [
      'Slow file transfers or web pages',
      'Video calls stutter or drop',
      'Ping shows timeouts or high variation',
      'Slowness at certain times of day',
      'Only certain locations or devices affected',
    ],
    initialChecks: [
      'Slow to everything, or to one service or site?',
      'Wired or Wi-Fi? Does it change if you use the other?',
      'When did it start and does it follow a pattern?',
      'Is a large upload, backup or update running?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Establish a baseline with ping',
        detail: 'Ping the gateway, then a public IP, for at least 50 packets (for example `ping -n 50 <host>`).',
        commandIds: ['ping'],
        lookFor: 'Loss percentage and spread between minimum and maximum time.',
        meaning: 'Loss to the gateway indicates a local problem. Loss only beyond the gateway points to the WAN or ISP.',
      },
      {
        id: 's2',
        title: 'Compare wired and wireless',
        detail: 'Test on a wired connection if possible and repeat the pings.',
        lookFor: 'Whether wired is clean while Wi-Fi is not.',
        meaning: 'A clean wired result isolates the issue to Wi-Fi.',
      },
      {
        id: 's3',
        title: 'Run pathping',
        detail: 'Run `pathping <host>` and wait for it to complete (it takes a few minutes).',
        commandIds: ['pathping', 'tracert'],
        lookFor: 'The first hop where loss or latency appears and continues to later hops.',
        meaning: 'Loss at one hop that does not continue is often just that hop ignoring probes. Loss that continues downstream is real.',
      },
      {
        id: 's4',
        title: 'Check the link and ports',
        detail: 'Inspect cable quality, port speed and duplex on the switch and adapter, and check for error counters if you have access.',
        lookFor: 'A port negotiating at a lower speed than expected, or errors.',
        meaning: 'Bad cables or duplex mismatch cause loss and low throughput.',
      },
      {
        id: 's5',
        title: 'Look for heavy use',
        detail: 'Check Task Manager > Performance > Ethernet/Wi-Fi and the process list for large transfers, and consider sync clients and updates.',
        commandIds: ['netstat-ano'],
        lookFor: 'Unusual network use by a process.',
        meaning: 'One process can saturate a small link.',
      },
    ],
    causes: [
      { cause: 'Wi-Fi congestion, interference or poor signal', indicators: 'Wired is fine; Wi-Fi shows loss and variation.' },
      { cause: 'Faulty cable or port', indicators: 'Errors, low negotiated speed, loss at the first hop.' },
      { cause: 'Saturated WAN link', indicators: 'Slow at busy times; loss beyond the gateway.' },
      { cause: 'ISP fault', indicators: 'Loss at ISP hops for all devices.' },
      { cause: 'Local heavy usage', indicators: 'A backup, update or sync consuming bandwidth.' },
    ],
    remediation: [
      { title: 'Replace the cable or change port', detail: 'Swap with a known-good cable and test another port.' },
      { title: 'Move to wired or improve Wi-Fi', detail: 'Use a cable for critical devices, or adjust AP placement and channels.', caution: 'AP changes affect others. Get approval.' },
      { title: 'Schedule or throttle heavy transfers', detail: 'Move backups and updates out of working hours.' },
      { title: 'Raise an ISP fault', detail: 'Provide pathping results, times and affected services.' },
    ],
    verification: [
      'Ping shows no or negligible loss over a sustained test',
      'Throughput and application performance are acceptable',
      'No recurrence at the previously affected times',
    ],
    documentation: [
      'Baseline ping and pathping results',
      'Wired vs wireless comparison',
      'Hop where loss or latency started',
      'Remediation and retest results',
    ],
    skills: ['networking', 'troubleshooting', 'investigation', 'problem-solving'],
  },
  {
    id: 'net-vpn',
    category: 'Networking',
    title: 'VPN problems',
    summary:
      'A VPN will not connect, or connects without access to resources. Vendor-agnostic: separate the underlying internet connection, authentication, tunnel and routing/DNS layers.',
    tags: ['vpn', 'remote access', 'split tunnel', 'dns', 'authentication', 'certificate'],
    symptoms: [
      'VPN client fails to connect or times out',
      'Authentication or certificate errors',
      'Connects but internal resources are not reachable',
      'Internal names do not resolve on VPN',
      'Disconnects frequently',
    ],
    initialChecks: [
      'Does normal internet work without the VPN?',
      'Which VPN client and profile, and did it work before? What changed?',
      'One user or several? Several suggests the VPN gateway or authentication service.',
      'Is the device on a restrictive network (hotel, guest Wi-Fi) that blocks VPN traffic?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Confirm plain internet access',
        detail: 'Disconnect the VPN and confirm the internet works. Ping a public IP and resolve a name.',
        commandIds: ['ping', 'nslookup'],
        lookFor: 'Reliable internet before the VPN.',
        meaning: 'No base connectivity means solve that first.',
      },
      {
        id: 's2',
        title: 'Read the client error',
        detail: 'Record the exact error text and check the client log if available.',
        lookFor: 'Authentication failure, certificate, timeout or policy message.',
        meaning: 'Authentication errors point to credentials, MFA or account state. Timeouts point to network blocks or a gateway issue.',
      },
      {
        id: 's3',
        title: 'Check time, certificates and account',
        detail: 'Confirm system date and time are right, any required client certificate is present and valid, and the account is enabled with VPN access.',
        lookFor: 'Clock drift, expired certificate, disabled account or missing group membership.',
        meaning: 'These commonly break authentication after an otherwise unchanged setup.',
      },
      {
        id: 's4',
        title: 'Test from another network',
        detail: 'Try the VPN from a different network such as a phone hotspot.',
        lookFor: 'Whether it connects elsewhere.',
        meaning: 'Success elsewhere means the first network blocks VPN traffic or has a conflicting subnet.',
      },
      {
        id: 's5',
        title: 'Check routes and DNS while connected',
        detail: 'With the VPN connected run `ipconfig /all` and `route print`, then test an internal IP and an internal name.',
        commandIds: ['ipconfig-all', 'route-print', 'nslookup', 'test-netconnection'],
        lookFor: 'Routes to internal subnets, DNS servers provided by the VPN, and a conflict with the local subnet.',
        meaning: 'Internal IP works but names fail is a DNS issue. Neither works suggests routing, firewall or a local subnet overlap.',
      },
    ],
    causes: [
      { cause: 'Account, MFA or credential problem', indicators: 'Authentication errors; sign-in logs show failures.' },
      { cause: 'Expired certificate or wrong clock', indicators: 'Certificate error; time is incorrect.' },
      { cause: 'Network blocks VPN ports', indicators: 'Works on another network.' },
      { cause: 'Subnet overlap with home or hotel network', indicators: 'Connects but resources unreachable; local subnet matches the corporate one.' },
      { cause: 'DNS not provided or not used over VPN', indicators: 'Internal IP works; names fail.' },
    ],
    remediation: [
      { title: 'Fix account or credentials', detail: 'Resolve account state or MFA using the authorised process.', caution: 'Verify identity before account changes.' },
      { title: 'Renew certificates and fix the clock', detail: 'Reissue or renew certificates through the client’s process and correct the time settings.' },
      { title: 'Use an alternative network or protocol', detail: 'Use another network or an allowed VPN protocol if available.' },
      { title: 'Adjust DNS or routes', detail: 'Correct the VPN profile’s DNS and routes via the VPN administrator.', caution: 'Profile changes affect all users. Test first.' },
    ],
    verification: [
      'VPN connects reliably',
      'Internal IP and name resolution work',
      'Required applications and shares are accessible',
    ],
    documentation: [
      'Client, profile and error text (no secrets)',
      'Whether the issue was network-specific',
      'Authentication or routing cause',
      'What was changed and by whom',
    ],
    skills: ['networking', 'network-security', 'identity-access', 'troubleshooting'],
  },

  // =========================================================== PRINTERS
  {
    id: 'prn-paper-misfeed',
    category: 'Printers',
    title: 'Paper misfeeds and jams',
    summary:
      'Paper does not pick up, picks several sheets, jams or crumples. Work through the paper path in order, find where it fails, then inspect the components at that point. Always follow the model’s service manual and observe safety around hot and moving parts.',
    tags: ['paper jam', 'misfeed', 'fuser', 'pickup roller', 'registration', 'paper path'],
    symptoms: [
      'Printer reports a paper jam or misfeed',
      'Pages crumple, skew or are damaged on exit',
      'Multiple sheets feed at once',
      'Pickup fails and the tray looks empty to the printer',
      'Jams only from one tray or one paper type',
    ],
    initialChecks: [
      'Power the printer off and let the fuser cool before opening covers. The fuser is HOT.',
      'Which tray, paper size and type? Is the paper in good condition, correctly loaded, and within spec?',
      'Does it jam from every tray, or one, and at the same place each time?',
      'Any error code on the display? Record it exactly and check the manual.',
      'Is the printer under a service contract, and are you authorised to open it?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Reproduce and locate the failure',
        detail: 'With media loaded correctly, run a test print from each tray and note where the paper stops or is damaged: at the tray, before registration, in the fuser or at the exit.',
        lookFor: 'A consistent position along the paper path.',
        meaning: 'The failure point narrows the component set: pickup/separation, feed rollers, registration, transfer, fuser or exit.',
      },
      {
        id: 's2',
        title: 'Check media and tray',
        detail: 'Check paper type, weight, humidity and loading. Fan the stack, remove curled or damp sheets, adjust guides to fit, and confirm tray settings match the paper.',
        lookFor: 'Damp, curled or mixed paper, guides too tight or loose, wrong paper settings.',
        meaning: 'Poor media and tray setup cause many misfeeds without any hardware fault.',
        ifAbnormal: 'Retest with fresh paper from a sealed ream.',
      },
      {
        id: 's3',
        title: 'Inspect the pickup and separation',
        detail: 'With power off, inspect the pickup and feed rollers and the separation pad or roller for glazing, wear, flat spots, contamination or paper dust.',
        lookFor: 'Shiny, hardened or worn rubber, contamination, loose or damaged parts.',
        meaning: 'Worn or contaminated rollers cause no-pickup and multi-feed.',
        ifAbnormal: 'Clean per the manual with an approved cleaner or replace the roller or kit.',
      },
      {
        id: 's4',
        title: 'Follow the feed path',
        detail: 'Check guides, rollers and sensors along the path for debris, torn paper fragments, labels or staples. Rotate rollers by hand where the manual allows.',
        lookFor: 'Obstructions, rollers that do not turn freely, bent guides.',
        meaning: 'Debris and damaged guides catch paper at the same place each time.',
      },
      {
        id: 's5',
        title: 'Inspect registration',
        detail: 'Inspect the registration rollers and sensor, where the paper is squared up before the image is transferred.',
        lookFor: 'Dirt, wear, a stuck sensor flag, or skew starting here.',
        meaning: 'Registration faults cause skew, early or late paper detection and jams before the transfer area.',
      },
      {
        id: 's6',
        title: 'Inspect the fuser and exit',
        detail: 'After the printer has fully cooled and is isolated from mains, inspect the fuser entry, rollers or belt, separation fingers and the exit rollers and sensor, following the manual.',
        lookFor: 'Paper wrapping around the roller, damaged separation fingers, toner build-up, a worn or damaged fuser, and obstructed exit.',
        meaning: 'Wrapping or crumpling at the fuser indicates worn components, contamination or paper issues. Jams at the exit indicate exit roller or sensor faults.',
        ifAbnormal: 'Replace or service the fuser or parts per the manual, or escalate under the service contract.',
      },
      {
        id: 's7',
        title: 'Test and document',
        detail: 'Reassemble, power on and run a good volume of test prints from every tray, including duplex if used.',
        lookFor: 'Clean, consistent output with no jam message.',
        meaning: 'Intermittent faults need a longer test run before closing.',
      },
    ],
    causes: [
      { cause: 'Poor paper, loading or tray settings', indicators: 'Fresh paper fixes it; curled or damp media; wrong settings.' },
      { cause: 'Worn or contaminated pickup or separation rollers', indicators: 'No pickup or multi-feed from one tray; glazed rubber.' },
      { cause: 'Debris or damaged guide in the feed path', indicators: 'Jam at the same location every time; fragments found.' },
      { cause: 'Registration roller or sensor fault', indicators: 'Skew or jams before the image area; sensor flag sticking.' },
      { cause: 'Fuser wear or contamination', indicators: 'Crumpling or wrapping at the fuser; fuser error codes.' },
      { cause: 'Exit roller or sensor fault', indicators: 'Pages jam at exit or sensor reports remaining paper.' },
    ],
    remediation: [
      { title: 'Correct media and tray settings', detail: 'Use fresh, correct-spec paper, load properly and set tray size and type.' },
      { title: 'Clean rollers and paths', detail: 'Clean rollers, guides and sensors per the service manual using approved materials.', caution: 'Power off. Use only cleaners the manual permits.' },
      { title: 'Replace worn rollers or pads', detail: 'Fit the correct pickup, feed or separation parts for the model.', caution: 'Use the right part number. Isolate from mains and observe ESD precautions.' },
      { title: 'Service or replace the fuser', detail: 'Replace the fuser unit or damaged fingers per the manual, or escalate.', caution: 'Fuser components are very hot and can burn. Allow full cooling, isolate power, and do not force parts.' },
      { title: 'Reset maintenance counters if the manual requires', detail: 'Some models need counters reset after replacing parts. Follow the manual exactly.', caution: 'Do not reset counters without actually replacing the part.' },
    ],
    verification: [
      'Test prints complete from every tray with no jams',
      'Duplex (if used) works',
      'No error code remains',
      'User confirms normal output',
    ],
    documentation: [
      'Tray, paper type and where the jam occurred',
      'Error code seen, exactly as displayed',
      'Components inspected and what was found or replaced (part numbers)',
      'Number of test prints and the result',
    ],
    skills: ['printer-engineering', 'hardware', 'troubleshooting', 'customer-support'],
    tree: {
      start: 'where',
      nodes: [
        {
          id: 'where',
          prompt: 'Where does the paper first go wrong?',
          help: 'Run a test print and watch, or inspect the jammed sheet for scuffs, creases or toner smears.',
          options: [
            { label: 'It does not pick up from the tray', next: 'tray' },
            { label: 'Several sheets feed together', next: 'multifeed' },
            { label: 'It jams or skews before reaching the image area', next: 'registration' },
            { label: 'It wraps, crumples or jams in the fuser', next: 'fuser' },
            { label: 'It jams at the exit', next: 'exit' },
          ],
        },
        {
          id: 'tray',
          prompt: 'Is the paper good, correctly loaded and are the tray settings correct?',
          options: [
            { label: 'No or unsure', conclusion: 'Correct the media first: fresh sealed paper, fanned, guides set, tray size and type set. Retest before touching hardware.' },
            { label: 'Yes, it is fine', next: 'pickup' },
          ],
        },
        {
          id: 'pickup',
          prompt: 'Do the pickup roller and separation pad look glazed, worn or dirty?',
          options: [
            { label: 'Yes', conclusion: 'Likely worn or contaminated pickup/separation parts. Clean per the manual, and replace the roller or pad kit if cleaning does not restore pickup.' },
            { label: 'No, they look fine', conclusion: 'Check the pickup clutch/drive and tray lift mechanism and sensors per the manual. If the roller does not turn or the tray does not lift, the drive or sensor is suspect. Escalate to service if beyond your remit.' },
          ],
        },
        {
          id: 'multifeed',
          prompt: 'Does fresh, fanned paper still multi-feed?',
          options: [
            { label: 'No, fresh paper fixed it', conclusion: 'Media issue: static, humidity or damaged edges. Store paper sealed and dry and advise the user.' },
            { label: 'No, it still multi-feeds', conclusion: 'Likely a worn separation pad or roller. Inspect and replace the separation parts per the manual and retest.' },
          ],
        },
        {
          id: 'registration',
          prompt: 'Is there debris, wear or a sticking sensor flag at the feed path or registration rollers?',
          options: [
            { label: 'Yes, found debris or a damaged part', conclusion: 'Remove the debris and clean, or replace the damaged guide or roller. Retest from all trays.' },
            { label: 'No, all looks clean', conclusion: 'Check the registration roller wear, clutch and sensor operation per the manual, and test sensors with the service diagnostics if available. Escalate if you cannot isolate the cause.' },
          ],
        },
        {
          id: 'fuser',
          prompt: 'With the printer cooled and isolated, is paper or toner wrapped around the fuser, or are the separation fingers damaged?',
          options: [
            { label: 'Yes', conclusion: 'Likely fuser wear or contamination. Clean what the manual allows and replace damaged fingers or the fuser unit as specified. HOT parts: allow full cooling and isolate power.' },
            { label: 'No, the fuser looks fine', conclusion: 'Check the fuser entry guide, the paper type setting (heavier media needs the right mode), and any fuser error code. If the code indicates the fuser, service the unit per the manual or escalate.' },
          ],
        },
        {
          id: 'exit',
          prompt: 'Are the exit rollers and exit sensor clean and moving freely?',
          options: [
            { label: 'No, dirty or sticking', conclusion: 'Clean the exit rollers and sensor flag per the manual, and replace worn exit rollers.' },
            { label: 'Yes', conclusion: 'Check the output tray full sensor, the duplex path diverter and curled output from the fuser. Escalate if the diverter or drive needs a service replacement.' },
          ],
        },
      ],
    },
  },
  {
    id: 'prn-queue-spooler',
    category: 'Printers',
    title: 'Print queue and spooler problems',
    summary:
      'Jobs stick in the queue, show Printing forever, disappear or crash the spooler. Decide if it is the client, the print server, the spooler service or the device before clearing anything.',
    tags: ['print queue', 'spooler', 'stuck job', 'printing', 'print server'],
    symptoms: [
      'Job stuck as printing or deleting',
      'Queue will not clear',
      'Spooler service stops or restarts',
      'Jobs vanish with no output',
      'Printer shows offline although the device is on',
    ],
    initialChecks: [
      'Is it one user, one printer, or all printers? Is there a print server or are users printing directly?',
      'Is the printer itself online and showing errors?',
      'Can anyone else print to this printer?',
      'Do other users have jobs waiting that a queue clear would delete?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Check the queue and printer state',
        detail: 'Open the printer queue and note job states and the printer status. Use `Get-Printer` and `Get-PrintJob -PrinterName <name>`.',
        commandIds: ['get-printer', 'get-printjob'],
        lookFor: 'Jobs in error, an offline printer, or one very large job at the head.',
        meaning: 'A single bad job blocks the queue behind it. An offline state points to connectivity.',
      },
      {
        id: 's2',
        title: 'Test the device directly',
        detail: 'Print a test page or configuration page from the device itself.',
        lookFor: 'Device prints its own page normally.',
        meaning: 'If the device is healthy, the fault is in the queue, driver or network path.',
      },
      {
        id: 's3',
        title: 'Check the spooler service',
        detail: 'Check that the Print Spooler service is running with `Get-Service Spooler`.',
        commandIds: ['get-service', 'sc-query'],
        lookFor: 'Running status, and repeated stops in the System event log.',
        meaning: 'A crashing spooler usually points to a driver problem.',
      },
      {
        id: 's4',
        title: 'Restart the spooler',
        detail: 'Restart the spooler service and retest.',
        commandIds: ['restart-spooler'],
        lookFor: 'Whether jobs move or the status recovers.',
        meaning: 'A restart fixes a hung spooler but does not fix the cause.',
      },
      {
        id: 's5',
        title: 'Clear the queue if required',
        detail: 'If jobs remain stuck, stop the spooler, clear the spool files and start it again.',
        commandIds: ['clear-print-queue'],
        lookFor: 'An empty queue and a working test print.',
        meaning: 'A corrupt job file was blocking the spooler.',
        ifAbnormal: 'If it returns quickly, investigate the driver or the document that causes it.',
      },
      {
        id: 's6',
        title: 'Check the driver and port',
        detail: 'Review the driver version and the port with `Get-PrinterDriver` and `Get-PrinterPort`.',
        commandIds: ['get-printerdriver', 'get-printerport'],
        lookFor: 'The wrong driver, outdated version, or a port pointing at an old IP.',
        meaning: 'A wrong driver or stale port causes repeated queue faults.',
      },
    ],
    causes: [
      { cause: 'Corrupt job or spool file', indicators: 'One job blocks others; clearing the queue fixes it.' },
      { cause: 'Spooler service hung or crashing', indicators: 'Service stops; restart helps temporarily.' },
      { cause: 'Faulty or incompatible driver', indicators: 'Repeated spooler failures after a driver change.' },
      { cause: 'Device offline or wrong port', indicators: 'Printer shows offline; port IP differs from the device.' },
      { cause: 'Insufficient permissions or print server issue', indicators: 'Only some users affected; server logs show errors.' },
    ],
    remediation: [
      { title: 'Restart the spooler', detail: 'Restart the service and retest.' },
      { title: 'Clear the queue', detail: 'Stop the spooler, delete files in the spool folder, and start it.', caution: 'Deletes every queued job for all users of that machine. Tell users and check for important jobs first.' },
      { title: 'Replace the driver', detail: 'Remove the printer and driver and install the correct vendor driver.', caution: 'On a print server this affects every connected client.' },
      { title: 'Fix the port', detail: 'Point the port at the device’s current IP or use a DHCP reservation.' },
    ],
    verification: [
      'A test page prints from the affected machine',
      'The queue is empty and spooler stays running',
      'Other users can also print',
    ],
    documentation: [
      'Printer name, scope of the problem and job states',
      'Spooler or driver events seen',
      'Whether queue contents were deleted and who was told',
      'Driver or port changes made',
    ],
    skills: ['printer-engineering', 'windows', 'troubleshooting', 'customer-support'],
  },
  {
    id: 'prn-network-connectivity',
    category: 'Printers',
    title: 'Printer network connectivity',
    summary:
      'A network printer shows offline or cannot be reached. Check the device’s own network settings, its IP address, the port type on the client, and any firewall or VLAN between them.',
    tags: ['printer offline', 'ip address', 'tcp/ip port', 'wsd', 'dhcp reservation', 'vlan'],
    symptoms: [
      'Printer shows offline on one or more PCs',
      'Worked until the printer or router was restarted',
      'Printer can print from some PCs but not others',
      'Printing works on the same subnet but not across VLANs',
    ],
    initialChecks: [
      'Does the device show a valid IP address on its own display or configuration page?',
      'Is the printer address static, DHCP or reserved?',
      'Which port type does the client use: standard TCP/IP, WSD or a print server share?',
      'Is the problem one PC or all?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Get the device’s IP from the device',
        detail: 'Print a configuration page or read the IP from the control panel, rather than trusting what Windows shows.',
        lookFor: 'The current IP, subnet mask, gateway and whether it is DHCP or static.',
        meaning: 'The device’s own view is the truth. A changed IP is a very common cause.',
      },
      {
        id: 's2',
        title: 'Ping the printer from the client',
        detail: 'Ping the printer’s IP from the affected PC.',
        commandIds: ['ping', 'test-netconnection'],
        lookFor: 'Replies, and whether the printing port (commonly 9100 for raw printing) responds with `Test-NetConnection <ip> -Port 9100`.',
        meaning: 'No reply means network path or the device is down. Reply on ping but not the port suggests the port is closed or filtered.',
      },
      {
        id: 's3',
        title: 'Compare with the client port configuration',
        detail: 'Check the printer port with `Get-PrinterPort` and the printer properties.',
        commandIds: ['get-printerport', 'get-printer'],
        lookFor: 'The port address matching the device’s current IP.',
        meaning: 'A mismatch explains offline status after an IP change. WSD ports can break after network changes.',
      },
      {
        id: 's4',
        title: 'Check the network between them',
        detail: 'Check VLAN, firewall and any wireless isolation between the client and the printer, and compare with a PC that works.',
        lookFor: 'Differences in subnet or rules between working and non-working clients.',
        meaning: 'Segmentation commonly blocks printing across VLANs.',
      },
    ],
    causes: [
      { cause: 'Printer IP changed through DHCP', indicators: 'Device IP differs from the port address.' },
      { cause: 'Wrong or WSD port type', indicators: 'Offline after network changes; WSD port in use.' },
      { cause: 'Firewall, VLAN or Wi-Fi isolation', indicators: 'Works from one subnet but not another.' },
      { cause: 'Device network fault', indicators: 'Device itself has no link or a wrong address.' },
    ],
    remediation: [
      { title: 'Update the port to the current IP', detail: 'Change the port address, or create a standard TCP/IP port.' },
      { title: 'Set a DHCP reservation or static address', detail: 'Give the device a fixed address so it does not change again.', caution: 'Coordinate with the network owner to avoid address conflicts.' },
      { title: 'Open the required path', detail: 'Ask the network owner to allow the printing ports between client and printer VLANs.', caution: 'Firewall changes need authorisation.' },
    ],
    verification: [
      'Ping and the print port respond',
      'A test page prints from the affected PC',
      'Status stays online after a printer restart',
    ],
    documentation: [
      'Device IP, port type and address, before and after',
      'Whether DHCP reservation or static IP was used',
      'Network path changes requested',
      'Test results',
    ],
    skills: ['printer-engineering', 'networking', 'troubleshooting', 'documentation'],
  },
  {
    id: 'prn-print-quality',
    category: 'Printers',
    title: 'Print quality problems',
    summary:
      'Streaks, ghosting, smearing, faded or spotted output. Identify the defect, whether it repeats at a fixed interval, and which part of the image path (toner, drum, transfer, fuser) it corresponds to, then work from simple causes to parts.',
    tags: ['print quality', 'streaks', 'ghosting', 'smear', 'toner', 'drum', 'banding'],
    symptoms: [
      'Vertical lines or streaks on the page',
      'Ghost images repeating down the page',
      'Toner smears or rubs off',
      'Faded or uneven density',
      'Spots or marks that repeat at regular intervals',
    ],
    initialChecks: [
      'Does the defect appear on a printed configuration page from the device, or only from one application?',
      'Is it all colours or one? Is it all the page or part?',
      'What is the status of toner, drum and waste containers?',
      'How many pages has the device printed and what maintenance was last done?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Print a test page from the device',
        detail: 'Print a configuration or diagnostic page directly from the device.',
        lookFor: 'Whether the defect appears on the internal page.',
        meaning: 'If it appears, it is a device fault. If not, check the driver, application or document.',
      },
      {
        id: 's2',
        title: 'Check consumables',
        detail: 'Check toner levels, drum life and any waste container, and check that consumables are correct for the model.',
        lookFor: 'Low or empty toner, worn drum, full waste container, non-genuine or incorrect parts.',
        meaning: 'Consumables cause many faults. Fading often means low toner; streaks may be damaged drum.',
      },
      {
        id: 's3',
        title: 'Measure the repeat interval',
        detail: 'If marks repeat, measure the distance between repeats on the page and compare with the manual’s roller circumference table if provided.',
        lookFor: 'A consistent distance between marks.',
        meaning: 'A repeat distance points at a specific roller, drum or fuser component matching that circumference.',
      },
      {
        id: 's4',
        title: 'Clean and calibrate',
        detail: 'Run the device’s cleaning and calibration routines from its menu, and clean accessible paths per the manual.',
        lookFor: 'Improvement after cleaning or calibration.',
        meaning: 'Improvement indicates dirt or drift. No change moves to parts.',
      },
      {
        id: 's5',
        title: 'Distinguish toner from fuser faults',
        detail: 'If toner smears or rubs off, check whether the fuser is reaching temperature and whether the paper type setting matches the media.',
        lookFor: 'Toner not bonding to paper, or fuser error codes.',
        meaning: 'Smearing on otherwise good images points to fusing, not imaging.',
      },
    ],
    causes: [
      { cause: 'Low or incorrect toner / worn drum', indicators: 'Faded output or streaks that follow the consumable.' },
      { cause: 'Dirty charge, laser or transfer components', indicators: 'Streaks or uneven density that cleaning improves.' },
      { cause: 'Fuser failure or wrong media setting', indicators: 'Toner rubs off or smears; fuser codes.' },
      { cause: 'Driver or application setting', indicators: 'Device test page is clean.' },
      { cause: 'Damaged roller or drum', indicators: 'Marks repeat at a fixed interval.' },
    ],
    remediation: [
      { title: 'Replace or reseat consumables', detail: 'Replace the toner, drum or imaging unit with the correct parts.', caution: 'Do not expose a drum to light for long. Handle toner carefully and clean spills with a suitable vacuum or damp cloth.' },
      { title: 'Run cleaning and calibration', detail: 'Use the device’s built-in routines.' },
      { title: 'Match media settings', detail: 'Set the paper type correctly so the fuser temperature is appropriate.' },
      { title: 'Replace the faulty component', detail: 'Based on repeat interval, replace the roller, drum or fuser per the manual.', caution: 'Isolate power, let hot parts cool, and use the correct part numbers.' },
    ],
    verification: [
      'Test and configuration pages are clean',
      'A few real user documents print correctly',
      'No recurrence of the defect pattern',
    ],
    documentation: [
      'Description of the defect and repeat interval measured',
      'Consumable status',
      'Cleaning or parts done (part numbers)',
      'Final test result',
    ],
    skills: ['printer-engineering', 'hardware', 'investigation', 'troubleshooting'],
  },
  {
    id: 'prn-driver-error-codes',
    category: 'Printers',
    title: 'Driver problems and device error codes',
    summary:
      'Wrong or conflicting drivers, or an error code on the device. Record the code exactly, look it up in the model’s manual, and use the right driver for the OS and printer language.',
    tags: ['printer driver', 'error code', 'universal driver', 'pcl', 'postscript', 'manual'],
    symptoms: [
      'Garbled output or missing fonts',
      'Printer features not available (duplex, trays)',
      'Printing broke after a Windows or driver update',
      'The device displays an error code or service message',
    ],
    initialChecks: [
      'Exact error code or message, as displayed, and any LED pattern.',
      'Model number and firmware version.',
      'Driver in use, its version and where it came from.',
      'Did the problem begin after an update?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Record the code and model',
        detail: 'Write down the exact code, the model and serial number, and firmware version from the configuration page.',
        lookFor: 'A precise code and identifiers.',
        meaning: 'Codes are manufacturer-specific. Never guess the meaning from a similar model.',
      },
      {
        id: 's2',
        title: 'Look the code up in the manual',
        detail: 'Find the code in the service or user manual for this exact model and follow the manual’s recommended action.',
        lookFor: 'The manual’s stated cause and procedure.',
        meaning: 'The manual separates user-fixable faults from those needing a service engineer.',
        ifAbnormal: 'If the manual says service required, escalate under the contract instead of improvising.',
      },
      {
        id: 's3',
        title: 'Check the installed driver',
        detail: 'Use `Get-PrinterDriver` and the printer properties to check name, version and architecture, and compare with the vendor’s current driver for the OS.',
        commandIds: ['get-printerdriver', 'get-printer'],
        lookFor: 'Generic or mismatched drivers, or several drivers for one device.',
        meaning: 'The wrong driver or a mismatched page description language causes garbled output and missing features.',
      },
      {
        id: 's4',
        title: 'Test with a clean install',
        detail: 'Install the vendor driver in a test queue and print the same document.',
        lookFor: 'Whether the output is correct with the clean driver.',
        meaning: 'If it works, the old driver or settings were the cause.',
      },
    ],
    causes: [
      { cause: 'Incorrect or generic driver', indicators: 'Missing features; garbled output.' },
      { cause: 'Driver conflict or update regression', indicators: 'Started after an update; rolling back fixes it.' },
      { cause: 'Hardware fault flagged by a code', indicators: 'Manual lists the code as a component fault.' },
      { cause: 'Firmware mismatch', indicators: 'Problems resolved by a firmware update per vendor notes.' },
    ],
    remediation: [
      { title: 'Install the correct vendor driver', detail: 'Remove stale drivers and install the right version and language for the OS.', caution: 'On a print server it affects all clients. Test first.' },
      { title: 'Roll back a bad update or driver', detail: 'Return to the last known good driver and pause the update if needed.' },
      { title: 'Follow the manual’s recovery steps', detail: 'Carry out only the steps the manual lists for the code.', caution: 'Do not bypass interlocks or safety features.' },
      { title: 'Escalate to the vendor or service provider', detail: 'Provide the model, serial, code and what you tried.' },
    ],
    verification: [
      'Output is correct with all expected features available',
      'The error code does not return after restart and test prints',
      'Driver version is recorded',
    ],
    documentation: [
      'Model, serial, firmware and exact error code',
      'Driver name and version before and after',
      'Manual reference used',
      'Escalation details if any',
    ],
    skills: ['printer-engineering', 'windows', 'documentation', 'troubleshooting'],
  },
  {
    id: 'prn-scan-auth',
    category: 'Printers',
    title: 'Scan-to-email/folder and authentication problems',
    summary:
      'Scan destinations fail or users cannot authenticate at the device. Check the destination protocol and permissions, then the authentication method. Never enter or record real passwords in notes.',
    tags: ['scan to folder', 'scan to email', 'smtp', 'smb', 'user authentication', 'pin'],
    symptoms: [
      'Scan to folder reports a connection or access error',
      'Scan to email fails to send',
      'Users cannot log in at the device with code, PIN or card',
      'It worked until a password or server change',
    ],
    initialChecks: [
      'Which function fails (folder, email, authentication)? One user or all?',
      'What changed recently (password change, server migration, security update, new SMB policy)?',
      'What account does the device use for the destination, and who owns it?',
      'Are you authorised to change device settings and the destination share or mail settings?',
    ],
    steps: [
      {
        id: 's1',
        title: 'Read the device’s error',
        detail: 'Record the exact error or result code on the device panel or log.',
        lookFor: 'A specific connection, authentication or path error.',
        meaning: 'The error type separates network reachability, credential and permission issues.',
      },
      {
        id: 's2',
        title: 'Test network reachability from the device',
        detail: 'Use the device’s own network test or ping function to reach the destination server, and test the same from a PC with `Test-NetConnection <server> -Port 445` for shares.',
        commandIds: ['test-netconnection', 'ping'],
        lookFor: 'Reachable server and open port.',
        meaning: 'No reach means DNS, routing or firewall. Reachable moves to credentials and permissions.',
      },
      {
        id: 's3',
        title: 'Check the destination account and share',
        detail: 'Confirm the service account exists, is enabled, is not locked or expired, and has the minimum required permissions to the share.',
        lookFor: 'Locked or expired accounts, missing share or NTFS permissions.',
        meaning: 'A password change or lockout is the most common reason a working scan setup stops.',
        ifAbnormal: 'Update the stored credential through the secure process, not in notes or tickets.',
      },
      {
        id: 's4',
        title: 'Check protocol compatibility',
        detail: 'Confirm the device supports the SMB version or SMTP security settings the server requires (for example older devices that only support old SMB versions).',
        lookFor: 'A server that refuses older protocols or requires modern TLS or authentication.',
        meaning: 'Security hardening can break older devices. The right answer is a firmware update or a supported alternative, not weakening server security.',
      },
      {
        id: 's5',
        title: 'Check user authentication',
        detail: 'For code, PIN or card login, check the user exists in the device’s address book or directory link, the card is registered, and directory connection works.',
        lookFor: 'Missing or disabled users, broken directory link.',
        meaning: 'Authentication problems at the panel are usually data or directory problems.',
      },
    ],
    causes: [
      { cause: 'Service account password changed, locked or expired', indicators: 'Authentication error after a password policy or change.' },
      { cause: 'Missing share or file permissions', indicators: 'Connection succeeds but access denied.' },
      { cause: 'Protocol or TLS incompatibility', indicators: 'Server refuses the device’s older protocol.' },
      { cause: 'SMTP relay or authentication change', indicators: 'Scan to email fails after mail setting changes.' },
      { cause: 'Directory or user data problem', indicators: 'Specific users cannot log in at the device.' },
    ],
    remediation: [
      { title: 'Update the stored credential securely', detail: 'Re-enter the service account credential on the device through the proper process.', caution: 'Do not write the password in tickets or ForgeTools.' },
      { title: 'Fix share or mailbox permissions', detail: 'Grant the least privilege needed to the service account.', caution: 'Avoid broad access or reusing admin accounts.' },
      { title: 'Update firmware or switch method', detail: 'Update device firmware or move to a supported secure method.', caution: 'Do not weaken server security to suit an old device without approval.' },
      { title: 'Correct user and directory data', detail: 'Fix user records, card registrations or the directory link.' },
    ],
    verification: [
      'A test scan reaches the folder or mailbox',
      'Affected users can log in at the device',
      'Setup still works after a device restart',
    ],
    documentation: [
      'Which function failed and the device error',
      'Account and permission changes (no passwords)',
      'Protocol or firmware changes',
      'Test results',
    ],
    skills: ['printer-engineering', 'identity-access', 'networking', 'documentation'],
  },
];
