/**
 * Guides for the daily, weekly and extra monthly checks. General good practice written as a starting point:
 * adapt to your own tools (RMM, backup and security consoles) and procedures. Placeholders only, no customer details.
 */
import type { CheckGuide } from './checkGuides';

export const ROUTINE_GUIDES: CheckGuide[] = [
  // ---------- daily ----------
  {
    id: 'd-backup', frequency: 'daily', title: 'Check backup status (local and cloud)', match: /backup status/i,
    task: 'Check backup status (local and cloud): confirm successful completion & troubleshoot failures',
    summary: 'Confirm last night’s backups finished, both on site and in the cloud, and deal with any failure the same day.',
    before: ['Access to the backup console or the RMM backup report.', 'The list of protected systems and their schedules.'],
    steps: [
      { text: 'Open the backup report or console and look at the result of the last run for every protected system.' },
      { text: 'Check each one finished successfully, finished on time, and has a recent restore point. A missing report counts as a failure.' },
      { text: 'Check the cloud or off-site copy has completed as well as the local one.' },
      { text: 'Look for warnings that are not failures yet: much longer run times, much smaller or larger backups, storage nearly full.' },
      { text: 'For each failure find the cause (credentials, full disk, snapshot or VSS error, network, agent offline) and fix it, then re-run the job.', command: 'vssadmin list writers' },
      { text: 'If it cannot be fixed today, raise it as a ticket with the cause and tell whoever owns the risk. Record what you found.' },
    ],
    monitor: ['Same system failing on consecutive days.', 'Time since the last successful backup for each system.', 'Backup storage free space and retention.', 'Alerts from the backup tool reaching a person, not just a mailbox.'],
    evidence: ['Date and who checked.', 'Counts: succeeded, warned, failed.', 'Failures and the fix or ticket raised.'],
    cautions: ['A green job is not a restore: the weekly test restore proves the data is usable.', 'Do not delete old backups to free space without checking retention rules.', 'Run the VSS command only on the server being investigated.'],
  },
  {
    id: 'd-alerts', frequency: 'daily', title: 'Monitor critical alerts', match: /critical alerts/i,
    task: 'Monitor critical alerts: review RMM / monitoring dashboards for servers, firewalls, and network devices',
    summary: 'Start the day by seeing what the monitoring has already noticed on servers, firewalls and network devices.',
    before: ['Access to the RMM or monitoring dashboards.', 'Known issues and planned maintenance, so you can tell expected alerts from new ones.'],
    steps: [
      { text: 'Open the dashboards and filter to critical and high alerts first.' },
      { text: 'Sort them: new since yesterday, still open, repeating, and expected because of planned work.' },
      { text: 'For each new critical alert check that it is real (device up, service running, link up) before acting.' },
      { text: 'Fix what you can now. Raise a ticket for the rest with the alert wording, time and what you tried.' },
      { text: 'Look at repeating alerts: if the same one fires every few days, fix the cause or tune the threshold with a note on why.' },
      { text: 'Check that monitoring itself is healthy: agents reporting in, no device silent for a long time.' },
    ],
    monitor: ['Count of open critical alerts, trending down.', 'Devices that stopped reporting.', 'Alert noise: the same alert closed repeatedly without a fix.', 'Time from alert to someone looking at it.'],
    evidence: ['Date checked.', 'Alerts by severity and what was done.'],
    cautions: ['Silence is not safe: no alerts can mean monitoring is broken.', 'Do not mute an alert without a recorded reason and an end date.'],
  },
  {
    id: 'd-av', frequency: 'daily', title: 'Check antivirus / EDR dashboards', match: /antivirus \/ EDR|antivirus.*EDR/i,
    task: 'Check antivirus / EDR dashboards: ensure all endpoints are protected and up to date',
    summary: 'Make sure every endpoint is protected, reporting and up to date, and that detections are dealt with.',
    before: ['Access to the antivirus or EDR console.', 'A rough count of how many endpoints should be protected.'],
    steps: [
      { text: 'Open the console and compare protected endpoints with the number there should be. Investigate anything missing.' },
      { text: 'Check for endpoints with protection switched off, out of date definitions, or not seen for several days.', command: 'Get-MpComputerStatus | Select-Object AMServiceEnabled, RealTimeProtectionEnabled, AntivirusSignatureLastUpdated' },
      { text: 'Review new detections and quarantine items. Confirm each was contained and decide if it needs a deeper look.' },
      { text: 'For anything suspicious such as repeated detections on one device, isolate it if your procedure says so and escalate.' },
      { text: 'Fix unprotected or out-of-date endpoints (agent repair, reinstall, update) and recheck.' },
      { text: 'Record counts and anything raised.' },
    ],
    monitor: ['Endpoints not reporting or with old definitions.', 'Repeated detections on the same device or user.', 'Protection switched off or tampering alerts.', 'Detections that were not contained.'],
    evidence: ['Date checked.', 'Protected versus expected counts.', 'Detections handled and escalations.'],
    cautions: ['The Defender command only applies to devices using Microsoft Defender: use your own product’s console otherwise.', 'Treat repeated detections as a possible compromise, not just noise.'],
  },
  {
    id: 'd-patch', frequency: 'daily', title: 'Check patch deployment status', match: /patch deployment/i,
    task: 'Check patch deployment status',
    summary: 'See whether the latest patches reached the devices that should have them, and chase failures.',
    before: ['Access to the patch management or RMM report.', 'The patch schedule and any deferrals agreed.'],
    steps: [
      { text: 'Open the patch deployment report and look at the latest deployment: installed, pending, failed and not reported.' },
      { text: 'List devices with failures or that are waiting for a restart.' },
      { text: 'For a failed device, check the reason (disk space, service stopped, conflicting update) and retry.', command: 'Get-WinEvent -LogName "Microsoft-Windows-WindowsUpdateClient/Operational" -MaxEvents 30' },
      { text: 'Check that devices which have not reported are online and the agent is healthy.' },
      { text: 'Make a note of anything that needs a restart outside working hours and arrange it.' },
      { text: 'Record the counts and raise tickets for stubborn failures.' },
    ],
    monitor: ['Devices not patched within your target time.', 'Same update failing on many devices.', 'Devices missing a restart for days.', 'Critical security updates outstanding.'],
    evidence: ['Date checked.', 'Counts installed, pending, failed.', 'Tickets raised.'],
    cautions: ['Do not force restarts on servers or during working hours without agreement.', 'Check an update is safe for line-of-business software before widening a deployment.'],
  },
  {
    id: 'd-helpdesk', frequency: 'daily', title: 'Review helpdesk queue for repeated issues', match: /helpdesk queue/i,
    task: 'Review helpdesk queue: identify repeated issues that could indicate underlying problems',
    summary: 'Look across the queue, not just at each ticket, to spot problems that are really one problem.',
    before: ['Access to the helpdesk queue (read only is enough).'],
    steps: [
      { text: 'Scan the open and recently closed tickets for the same symptom, device type, location or software.' },
      { text: 'Group tickets that look alike. Ask: what do they have in common (a recent change, an update, a site, a device model)?' },
      { text: 'Check whether a recent change or outage could explain the group. If so, link the tickets to it.' },
      { text: 'For a real pattern, raise one problem record with the symptoms, the number of tickets and your suspected cause.' },
      { text: 'Tell the people working the tickets, so they stop treating them as separate issues.' },
      { text: 'Note the pattern for the monthly trends review.' },
    ],
    monitor: ['Tickets reopened more than once.', 'Count of tickets per category compared with last week.', 'Tickets nearing their response or update times.', 'Problems raised but not progressed.'],
    evidence: ['Patterns found and the problem record raised.', 'Counts, not names.'],
    cautions: ['Keep ticket details in the ticket system. Note only patterns and counts here.'],
  },
  {
    id: 'd-disk', frequency: 'daily', title: 'Monitor disk usage on critical servers', match: /disk usage/i,
    task: 'Monitor disk usage on critical servers and systems',
    summary: 'Catch drives filling up before a server stops working.',
    before: ['Disk monitoring in the RMM, or access to the servers.', 'Your thresholds, for example warn at 80% and act at 90%.'],
    steps: [
      { text: 'Open the disk report for critical servers and systems and sort by least free space.' },
      { text: 'Check free space against your thresholds, and how fast it changed since last time.', command: 'Get-Volume | Select-Object DriveLetter, SizeRemaining, Size' },
      { text: 'For any drive close to the threshold find what grew: logs, backups, temporary files, a database, shadow copies.' },
      { text: 'Free space safely (rotate logs, clear temporary files) or plan to extend the drive. Never delete data you cannot identify.' },
      { text: 'Raise a ticket for anything needing more storage, with the growth rate.' },
      { text: 'Record anything you changed.' },
    ],
    monitor: ['Free space trend for each critical drive.', 'Sudden jumps in used space.', 'Alert thresholds present and working on every critical drive.'],
    evidence: ['Drives near threshold and the action taken.'],
    cautions: ['A full system drive can stop updates, logging and the server itself: act early.', 'Do not delete shadow copies, backups or database files to make space without checking.'],
  },
  {
    id: 'd-resources', frequency: 'daily', title: 'Review resource utilization (CPU, RAM)', match: /resource utili[sz]ation/i,
    task: 'Review resource utilization (CPU, RAM) on key servers for signs of stress',
    summary: 'Spot servers that are struggling before users notice.',
    before: ['Access to performance graphs in the RMM or monitoring tool.', 'What normal looks like for each server.'],
    steps: [
      { text: 'Open the CPU and memory graphs for the key servers for the last day and the last week.' },
      { text: 'Compare with normal. Look for long periods of high use, not short spikes.' },
      { text: 'On a server that looks stressed, see what is using the resources.', command: 'Get-Process | Sort-Object CPU -Descending | Select-Object -First 10 Name, CPU, WorkingSet' },
      { text: 'Decide the likely cause: a runaway process, a scheduled job, a memory leak, or genuine growth.' },
      { text: 'Fix or schedule the fix. If it is growth, note it for the capacity review.' },
      { text: 'Record the server, what you saw and what you did.' },
    ],
    monitor: ['Sustained high CPU or low free memory.', 'Pagefile or swap use climbing.', 'Servers that need frequent restarts to stay healthy.'],
    evidence: ['Servers checked and any that were stressed, with the cause.'],
    cautions: ['Do not kill a process on a production server unless you know what it does.', 'Short spikes are normal: judge by duration.'],
  },
  // ---------- weekly ----------
  {
    id: 'w-restore', frequency: 'weekly', title: 'Test restore from backup', match: /test restore from backup/i,
    task: 'Test restore from backup: restore a small file or folder to verify integrity',
    summary: 'Prove a backup can actually be restored, with a small file or folder.',
    before: ['Access to the backup tool and permission to restore.', 'A safe place to restore to, not over live data.'],
    steps: [
      { text: 'Pick a system and a file or folder. Vary the system each week so everything is covered over time.' },
      { text: 'Restore it from a recent restore point to a separate location, never over the original.' },
      { text: 'Time how long it took from starting to having the file.' },
      { text: 'Open the restored file and check it is complete and readable. Compare size or a checksum if you can.', command: 'Get-FileHash <restored-file> -Algorithm SHA256' },
      { text: 'Delete the test restore when finished.' },
      { text: 'Record the system, restore point age, time taken and result. Raise a ticket for any failure.' },
    ],
    monitor: ['Which systems have not been restore-tested recently.', 'Restore time against what the business expects.', 'Failures and how quickly they were fixed.'],
    evidence: ['System tested, date, restore point age, time taken, pass or fail.'],
    cautions: ['Never restore over live data as a test.', 'Remove restored copies afterwards: they may hold sensitive data.'],
  },
  {
    id: 'w-firewall', frequency: 'weekly', title: 'Review firewall and security appliance logs', match: /firewall and security appliance logs/i,
    task: 'Review firewall and security appliance logs: look for blocked connections, intrusion attempts, etc',
    summary: 'Look through firewall and security logs for blocked traffic and attempts that need a closer look.',
    before: ['Access to the firewall and security appliance logs or reports.', 'What normal traffic looks like.'],
    steps: [
      { text: 'Open the last week of logs or the summary report for each firewall and security appliance.' },
      { text: 'Look at the top blocked sources and destinations, and at intrusion prevention events by severity.' },
      { text: 'Look for patterns: one source hitting many ports, repeated sign-in attempts to remote access, traffic to unusual countries.' },
      { text: 'Check for changes: new rules, changed rules, new admin sign-ins.' },
      { text: 'For anything suspicious follow your incident procedure: block, escalate, and record.' },
      { text: 'Record what you reviewed and anything raised.' },
    ],
    monitor: ['Spikes in blocked traffic or intrusion events.', 'Repeated failed remote access logins.', 'Rule and admin changes (should match approved changes).', 'Logs actually being kept and forwarded.'],
    evidence: ['Date reviewed, devices covered, notable events and actions.'],
    cautions: ['Blocked traffic is the firewall working: look for what got through or what is persistent.', 'Do not copy raw logs with personal data into this app.'],
  },
  {
    id: 'w-updates', frequency: 'weekly', title: 'Check pending Windows and third-party updates', match: /pending windows/i,
    task: 'Check pending Windows & third-party updates: approve/deploy as needed',
    summary: 'Decide which updates to approve and schedule, for Windows and for third-party software.',
    before: ['Access to the patch tool.', 'The maintenance windows and the list of business-critical applications.'],
    steps: [
      { text: 'Open the list of pending Windows and third-party updates.' },
      { text: 'Read the notes for security updates and for anything rated critical. Note known issues.' },
      { text: 'Approve security updates for a small test group first, then wider.' },
      { text: 'Hold back anything that could affect a line-of-business application until it is checked.' },
      { text: 'Schedule installs and restarts for the agreed windows.' },
      { text: 'Record what was approved, deferred and why.' },
    ],
    monitor: ['Critical security updates waiting more than your target time.', 'Third-party apps with known exploited flaws.', 'Deferrals that keep getting extended.'],
    evidence: ['Approved, deferred and the reasons.'],
    cautions: ['Do not approve everything at once: test group first.', 'Check vendor advisories for third-party software, which is often forgotten.'],
  },
  {
    id: 'w-docs', frequency: 'weekly', title: 'Update documentation (weekly changes)', match: /update documentation: note/i,
    task: 'Update documentation: note infrastructure changes, new users, device additions, config changes',
    summary: 'Keep the record of what exists and what changed up to date, week by week.',
    before: ['Access to the documentation system.', 'The week’s change records and tickets.'],
    steps: [
      { text: 'List the week’s changes from tickets and change records: infrastructure, users joined or left, devices added or removed, configuration changes.' },
      { text: 'Update the asset list and any diagrams that the changes affect.' },
      { text: 'Record configuration changes with the date, what changed and why.' },
      { text: 'Check the documentation for each new device or user is complete (role, location, support details) without storing secrets.' },
      { text: 'Note anything you could not document and why, so it is not lost.' },
    ],
    monitor: ['Changes made with no matching record.', 'Documents not reviewed for a long time.', 'New devices missing from the asset list.'],
    evidence: ['Date updated and a count of items changed.'],
    cautions: ['Passwords and keys belong in the approved password vault, never in documents.', 'Keep customer-identifying details in the system that is meant to hold them, not in this app.'],
  },
  {
    id: 'w-accounts', frequency: 'weekly', title: 'Review user account changes', match: /user account changes/i,
    task: 'Review user account changes: check for stale, disabled, or suspicious accounts',
    summary: 'Check who was created, changed, disabled or locked out this week, and spot anything odd.',
    before: ['Access to directory audit logs or identity reports.', 'The week’s joiner, mover and leaver notes.'],
    steps: [
      { text: 'List accounts created, disabled, deleted and changed in the last 7 days from the audit log.', command: 'Get-WinEvent -FilterHashtable @{LogName="Security"; Id=4720,4725,4726,4738,4740; StartTime=(Get-Date).AddDays(-7)}' },
      { text: 'Match each creation and disablement to a real request, joiner or leaver. Investigate any that have none.' },
      { text: 'Look for accounts added to privileged groups, and for repeated lockouts.' },
      { text: 'Check for stale accounts: enabled but not used for a long time.' },
      { text: 'Disable or escalate suspicious ones following your procedure, and record the action.' },
    ],
    monitor: ['Changes to privileged groups (alert on every change).', 'Accounts created outside normal hours or by unexpected people.', 'Repeated lockouts of one account.', 'Leavers whose accounts are still enabled.'],
    evidence: ['Counts created, disabled, changed and any suspicious accounts handled.'],
    cautions: ['Run the command on a domain controller you are authorised to query.', 'Keep names out of this app: note counts and outcomes.'],
  },
  {
    id: 'w-ups', frequency: 'weekly', title: 'Verify UPS status and logs', match: /UPS status/i,
    task: 'Verify UPS status & logs: battery health and recent events',
    summary: 'Make sure the battery backup would actually carry the load in a power cut.',
    before: ['Access to the UPS management page or software.', 'Knowing what the UPS protects.'],
    steps: [
      { text: 'Open the UPS status page. Check it is online, on mains power and not in alarm.' },
      { text: 'Check battery health, expected runtime and the date the battery was last replaced or tested.' },
      { text: 'Read the event log for the week: power cuts, brownouts, overloads, failed self-tests.' },
      { text: 'Check load against capacity. A UPS running near its limit will not give the runtime you expect.' },
      { text: 'Raise a ticket to replace batteries that are old, failing or showing reduced runtime.' },
      { text: 'Record the status and any events.' },
    ],
    monitor: ['Battery age and runtime trend.', 'Failed self-tests.', 'Repeated power events at one site.', 'Load creeping up as equipment is added.'],
    evidence: ['Date checked, status, runtime and events.'],
    cautions: ['Do not run a runtime test on a UPS carrying live critical equipment without a plan.', 'Replacing batteries may need a short outage: plan it.'],
  },
  {
    id: 'w-cloud', frequency: 'weekly', title: 'Check cloud service health dashboards', match: /cloud service health/i,
    task: 'Check cloud service health dashboards: Microsoft 365, Google Workspace, etc',
    summary: 'Know about provider incidents before users report them, and keep advisories in mind.',
    before: ['Access to the service health pages for the cloud services in use.'],
    steps: [
      { text: 'Microsoft 365: open the admin center, Health, Service health, and read active incidents and advisories.' },
      { text: 'Google Workspace: check the Workspace Status Dashboard for current and recent incidents.' },
      { text: 'Check other cloud services you rely on in the same way.' },
      { text: 'Note any incident that explains user reports, and any planned change that needs preparation.' },
      { text: 'Tell the team about anything that affects users, and record it.' },
    ],
    monitor: ['Incidents that repeat for the same service.', 'Message center or advisory items with dates and actions for you.', 'Differences between the provider dashboard and what users experience.'],
    evidence: ['Date checked and notable incidents or advisories.'],
    cautions: ['Provider dashboards can lag: a user report may come first.'],
  },
  {
    id: 'w-vuln', frequency: 'weekly', title: 'Run a basic vulnerability scan', match: /vulnerability scan \(basic\)/i,
    task: 'Run vulnerability scan (basic): spot new issues',
    summary: 'A light weekly scan to spot new problems between the fuller quarterly assessments.',
    before: ['Written authorisation for what may be scanned.', 'An approved scanner and a quiet time.'],
    steps: [
      { text: 'Confirm scope and timing, and that the people watching alerts know a scan is running.' },
      { text: 'Run the scan with the standard, gentle profile against the agreed ranges.' },
      { text: 'Compare with last week: what is new, what has gone, what is still open.' },
      { text: 'Triage the new findings by severity and by exposure, and drop false positives.' },
      { text: 'Fix or raise a ticket for critical and high items. Record accepted risks with sign-off.' },
      { text: 'Record the counts.' },
    ],
    monitor: ['Count of critical and high findings.', 'Age of open findings.', 'New devices that appear in a scan but not in the asset list.'],
    evidence: ['Date, scope, counts by severity, actions raised.'],
    cautions: ['Only scan what you are authorised to scan.', 'Gentle settings and a quiet window: older printers and embedded devices can crash under aggressive scans.', 'Treat results as sensitive.'],
  },
  {
    id: 'w-hardware', frequency: 'weekly', title: 'Inspect key server hardware logs', match: /hardware logs/i,
    task: 'Inspect key server hardware logs: RAID, temperature, fan issues',
    summary: 'Find failing disks, overheating and fan problems before they become an outage.',
    before: ['Access to the server management interface or hardware monitoring.'],
    steps: [
      { text: 'Open the hardware or management log for each key server (the vendor’s management controller or monitoring tool).' },
      { text: 'Check storage: RAID state, degraded or rebuilding arrays, disks with predictive failure or growing error counts.' },
      { text: 'Check temperatures and fans against normal for that server, and power supply redundancy.' },
      { text: 'Check for memory error warnings and unexpected restarts.' },
      { text: 'Raise a ticket and a vendor support case for any warning, with the log entry and date.' },
      { text: 'Record the servers checked and what you found.' },
    ],
    monitor: ['Any degraded array or predictive-failure disk (act the same day).', 'Rising temperatures or fan speeds.', 'Hardware warranty status for servers showing faults.'],
    evidence: ['Servers checked, date and any faults raised.'],
    cautions: ['Do not replace a disk in a degraded array without confirming the backup is good.', 'Follow the vendor procedure for hot-swap parts.'],
  },
  // ---------- extra monthly ----------
  {
    id: 'm-patch', frequency: 'monthly', title: 'Detailed patch review', match: /detailed patch review/i,
    task: 'Detailed patch review: analyze what was installed, what failed, and why',
    summary: 'Look back over the month’s patching: what went in, what failed and why, and what to change.',
    before: ['The month’s patch reports.', 'Notes from daily and weekly patch checks.'],
    steps: [
      { text: 'Pull the month’s report: installed, failed, deferred and pending, by device group.' },
      { text: 'Check the compliance rate against your target and for critical security updates in particular.' },
      { text: 'Group failures by cause (space, service, conflicting software, offline devices) and count each.' },
      { text: 'Fix the causes that affect many devices rather than repairing devices one by one.' },
      { text: 'Review deferrals: are any older than agreed? Decide to install or accept with sign-off.' },
      { text: 'Record the results and any process changes.' },
    ],
    monitor: ['Patch compliance trend by month.', 'Time from release to installed for critical updates.', 'Devices that fail every month.'],
    evidence: ['Compliance rate, failure causes by count, deferrals and sign-offs.'],
    cautions: ['A high percentage can hide a few critical devices: look at the oldest and most exposed first.'],
  },
  {
    id: 'm-docs', frequency: 'monthly', title: 'Update documentation fully', match: /update documentation fully/i,
    task: 'Update documentation fully: network diagrams, asset lists, admin credentials vault',
    summary: 'A full monthly refresh of the documentation: diagrams, assets and the credentials vault.',
    before: ['Access to the documentation system, asset list and the approved password vault.', 'The weekly change notes.'],
    steps: [
      { text: 'Review the network diagrams against what is really there. Fix differences and add anything new.' },
      { text: 'Reconcile the asset list with discovery or RMM data: add new devices, retire removed ones, correct locations and roles.' },
      { text: 'Open the credentials vault and check entries are current: remove ones for retired systems and confirm admin accounts that should exist.' },
      { text: 'Check recovery steps and contact lists in the runbook are still right.' },
      { text: 'Check the documentation backup and who has access to it.' },
      { text: 'Record the review date and what changed.' },
    ],
    monitor: ['Devices found by discovery but missing from the asset list.', 'Vault entries with no recent change or owner.', 'Documents that have not been reviewed in a long time.'],
    evidence: ['Date, items updated by count, gaps found.'],
    cautions: ['Never copy credentials into notes, tickets or this app: the vault is the only place.', 'Restrict who can read the vault and the documentation.'],
  },
  {
    id: 'm-disk', frequency: 'monthly', title: 'Review disk space trends', match: /disk space trends/i,
    task: 'Review disk space trends: project growth and plan upgrades',
    summary: 'Use a month of data to forecast when storage runs out and plan upgrades.',
    before: ['Disk usage history for at least 3 months.', 'Known growth: new users, projects, data-heavy systems.'],
    steps: [
      { text: 'Pull used space over time for each critical volume and for the main file stores.' },
      { text: 'Work out the growth per month and the date each would reach its limit.', command: 'Get-Volume | Select-Object DriveLetter, SizeRemaining, Size' },
      { text: 'Find what is driving growth: backups, logs, mailboxes, user data, databases.' },
      { text: 'Decide for each: clean up, archive, change retention, or add capacity.' },
      { text: 'Write the upgrades into a plan with dates before the limits, and a rough cost.' },
      { text: 'Record the forecast for the quarterly capacity review.' },
    ],
    monitor: ['Months until full for each volume.', 'Growth rate changes.', 'Backup storage growth as well as production storage.'],
    evidence: ['Forecast dates and the actions agreed.'],
    cautions: ['Allow time to buy and install: plan well before the full date.', 'Archive only with agreement on retention.'],
  },
  {
    id: 'm-av-scan', frequency: 'monthly', title: 'Run a full AV / malware scan on servers', match: /full AV/i,
    task: 'Run full AV / malware scan on servers',
    summary: 'A full scan of the servers, scheduled so it does not disturb the business.',
    before: ['An agreed window, ideally out of hours.', 'Access to the antivirus console.', 'Knowledge of any exclusions that are in place.'],
    steps: [
      { text: 'Schedule or start a full scan on each server in the agreed window, one at a time for heavily used servers.', command: 'Start-MpScan -ScanType FullScan' },
      { text: 'Check the scans started and finished. Note any that were cut short.' },
      { text: 'Review the results and any detections. Confirm each was quarantined or removed.' },
      { text: 'Investigate any detection on a server as possibly serious: how did it get there?' },
      { text: 'Review the exclusions list: remove any that are no longer needed.' },
      { text: 'Record the scan dates and results.' },
    ],
    monitor: ['Scans that did not complete.', 'Detections on servers, which should be rare.', 'Growing exclusion lists.'],
    evidence: ['Servers scanned, dates and results.'],
    cautions: ['Full scans use a lot of CPU and disk: do not run them in business hours.', 'The command applies to Microsoft Defender: use your own product’s scan otherwise.'],
  },
  {
    id: 'm-licence', frequency: 'monthly', title: 'Check licensing compliance', match: /licensing compliance/i,
    task: 'Check licensing compliance: software, Microsoft 365, security tools',
    summary: 'Make sure licences match use: no one without a licence they need, and none paid for and unused.',
    before: ['Licence and subscription portals, with read access.', 'The purchased counts and renewal dates.'],
    steps: [
      { text: 'Microsoft 365: compare licences bought with licences assigned, and look for unlicensed users and unused licences.' },
      { text: 'Check security tools (antivirus, backup, email security) cover every device or user they should.' },
      { text: 'Check server and application licences against what is installed.' },
      { text: 'Reclaim licences from leavers and unused accounts, and note shortfalls.' },
      { text: 'List renewals in the next 90 days with their dates.' },
      { text: 'Raise purchases or reductions through your process, and record the findings.' },
    ],
    monitor: ['Licences assigned to disabled accounts.', 'Shortfalls against installed or active counts.', 'Renewal dates approaching.'],
    evidence: ['Counts bought versus used per product, renewals due, actions raised.'],
    cautions: ['Under-licensing is a compliance risk and over-licensing wastes money: report both.', 'Keep licence keys in the vault, not in notes.'],
  },
  {
    id: 'm-helpdesk', frequency: 'monthly', title: 'Review helpdesk trends', match: /helpdesk trends/i,
    task: 'Review helpdesk trends: identify recurring issues and plan remediation',
    summary: 'Use the month’s ticket data to find the problems worth fixing properly.',
    before: ['The month’s ticket report by category, priority and age.', 'The daily pattern notes.'],
    steps: [
      { text: 'Pull the month’s tickets by category and compare with the previous months.' },
      { text: 'Find the top recurring issues and what share of the workload they take.' },
      { text: 'For each one decide the real fix: a configuration change, a replacement, training, a documentation fix, or automation.' },
      { text: 'Check response and update times against the priority table, and note misses and why.' },
      { text: 'Pick the few with the best payoff, give them an owner and a date.' },
      { text: 'Record the findings for the quarterly business review.' },
    ],
    monitor: ['Tickets per category month on month.', 'Reopened tickets.', 'Response and update time misses.', 'Problem records still open.'],
    evidence: ['Top issues by count, actions and owners.'],
    cautions: ['Use counts and categories. Keep names and details in the ticket system.'],
  },
  // ---------- optional but recommended ----------
  {
    id: 'o-automate', frequency: 'quarterly', title: 'Automate checks with RMM tools', match: /automate checks with RMM/i,
    task: 'Automate checks with RMM tools and get daily/weekly summary reports',
    summary: 'Let the RMM do the routine checking and send a summary, so people spend time on the exceptions.',
    before: ['An RMM or monitoring tool with scripting, monitors and reports.', 'The list of daily and weekly checks.'],
    steps: [
      { text: 'List the daily and weekly checks and mark which are mechanical (counts, thresholds, status) and which need judgement.' },
      { text: 'For each mechanical check set up a monitor or script with a clear threshold and a sensible alert level.' },
      { text: 'Set up a daily and weekly summary report sent to the right people.' },
      { text: 'Run the automation alongside the manual check for a couple of weeks and compare.' },
      { text: 'When they agree, switch the manual check to a quick review of the summary.' },
      { text: 'Review the monitors each quarter for noise and gaps.' },
    ],
    monitor: ['Automations that stopped running.', 'Alert noise.', 'Checks that exist only in someone’s head.'],
    evidence: ['Checks automated, summary reports in place.'],
    cautions: ['Automation can fail silently: monitor the monitors.', 'Keep a human review of the summary.'],
  },
  {
    id: 'o-runbook', frequency: 'quarterly', title: 'Maintain a runbook per client', match: /runbook per client/i,
    task: 'Maintain a runbook per client: unique systems, recovery steps, contact lists',
    summary: 'Keep a short, accurate runbook for each client so anyone can support and recover them.',
    before: ['The documentation system where runbooks live (not this app).', 'The latest DR test results.'],
    steps: [
      { text: 'Check each runbook lists what is unusual about that environment: systems, dependencies and who owns them.' },
      { text: 'Check recovery steps are current and match the last DR test.' },
      { text: 'Check the contact and escalation lists are current and that the people still hold those roles.' },
      { text: 'Check how to get to credentials, which should point to the vault and never contain them.' },
      { text: 'Have someone else read one runbook and try to follow it.' },
      { text: 'Record the review date.' },
    ],
    monitor: ['Runbooks not reviewed within the quarter.', 'Contacts that bounced or are out of date.', 'Changes with no runbook update.'],
    evidence: ['Runbooks reviewed by count and the date.'],
    cautions: ['Keep client names and contact details in your documentation system, not in this app.', 'No credentials in runbooks.'],
  },
  {
    id: 'o-training', frequency: 'quarterly', title: 'Encourage user training', match: /user training/i,
    task: 'Encourage user training: phishing simulations or security awareness updates (quarterly or monthly)',
    summary: 'Help users spot phishing and other common attacks through regular, short training.',
    before: ['A way to send training or simulations (a platform, or simple messages).', 'Agreement from the client.'],
    steps: [
      { text: 'Agree the programme: phishing simulations, short awareness messages, or both, and how often.' },
      { text: 'Pick a short theme for the period, such as spotting fake invoices, shared-file links or urgent requests.' },
      { text: 'Send the training or simulation and tell the client when it is happening.' },
      { text: 'Measure results as counts: how many reported, how many clicked, how many did nothing.' },
      { text: 'Follow up with short, friendly help for anyone who struggled, and thank the people who reported.' },
      { text: 'Include the trend in the quarterly business review.' },
    ],
    monitor: ['Report rate and click rate over time.', 'Real phishing reports from users.', 'Repeat clickers needing extra help.'],
    evidence: ['Dates, themes and aggregate results.'],
    cautions: ['Agree simulations in advance and keep them fair, not punishing.', 'Report results as counts, not names.'],
  },
];
