import type { CheckList } from './hardening';
export const OPS_CHECKS: CheckList[] = [
  { id: 'incident', title: 'First response to a suspected incident', intro: 'For the first minutes. Follow the customer\'s own incident process as soon as you can find it.', items: [
    'Stay calm and write down the time you were told',
    'Do not delete anything, switch off or wipe the device unless told to',
    'Ask what was seen and what was done, in the user\'s own words',
    'Disconnect the device from the network (cable or Wi-Fi) if the process allows it',
    'Tell the person responsible for security straight away',
    'Do not use the affected account or device to tell anyone',
    'Note which accounts may be affected, without writing down any passwords',
    'Reset passwords and revoke sessions only from a clean device and with approval',
    'Check for new forwarding rules, new devices and new admin accounts',
    'Keep alerts, screenshots and logs as they are',
    'Write a timeline in the ticket as things happen',
    'Do not contact the sender or the attacker',
    'Hand over with a short summary of what you saw and what you changed' ] },
  { id: 'restore', title: 'Backup restore test', intro: 'A backup that has never been restored is only a hope. Do this with the owner of the data.', items: [
    'Agree a date and who needs to know',
    'Choose a small, harmless item to restore, not live data',
    'Restore it to a different place from the original',
    'Check the item opens and is complete',
    'Note how long it took and who did it',
    'Confirm the backup job has run recently and without errors',
    'Check backups are kept somewhere that survives the building being lost',
    'Check the backups cannot be deleted by the accounts users sign in with',
    'Check how many past versions are kept and for how long',
    'Check the recovery steps are written down and someone else could follow them',
    'Record the result and the date of the next test' ] },
  { id: 'starter', title: 'New starter', intro: 'Run through with the customer\'s own request form. Do not guess permissions.', items: [
    'Confirm the request came from an authorised person',
    'Create the account with the agreed name format and the right licence',
    'Add to only the groups and mailboxes the role needs',
    'Set up multi-factor sign-in with the user, not for them',
    'Give the first sign-in details by a different route from the username',
    'Check the device is encrypted, updated and in the asset records',
    'Install only the agreed software',
    'Set up printers and scanning with the user',
    'Show how to report problems and phishing',
    'Test a real sign-in, a send and receive, and a print' ] },
  { id: 'leaver', title: 'Leaver', intro: 'Speed matters, but so does keeping the data. Confirm what to keep first.', items: [
    'Confirm the leaving date and the request came from an authorised person',
    'Agree who takes over the mailbox and the files',
    'Block sign-in and end active sessions at the agreed time',
    'Remove from groups and shared mailboxes',
    'Remove multi-factor methods and registered devices',
    'Keep or convert the mailbox as agreed before removing the licence',
    'Collect the device and any tokens or cards',
    'Check for forwarding rules and automatic replies set by agreement only',
    'Wipe the device only after the data is safe',
    'Remove from the printer address books and scan accounts if they were personal',
    'Record what was done and when' ] },
  { id: 'visit', title: 'Before leaving a site', intro: 'The last look before you close the visit.', items: [
    'Test the thing you were asked to fix, as the user would use it',
    'Test that nothing next to it broke',
    'Put things back as found: cables, covers, settings',
    'Remove anything you installed for the visit',
    'Check you left no passwords, notes or test pages behind',
    'Tell the user what changed and what to do if it returns',
    'Update the ticket before you leave the building',
    'Take all your kit with you' ] },
];
