import type { CommandEntry } from './types';

/**
 * CMD / PowerShell reference. Examples use fictional data only
 * (documentation ranges 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24, example.co.uk, contoso.com).
 */
export const COMMANDS: CommandEntry[] = [
  // ============================================================ NETWORKING
  {
    id: 'ipconfig', group: 'Networking', name: 'ipconfig', shell: 'both',
    syntax: 'ipconfig',
    purpose: 'Show the basic IP configuration of each network adapter.',
    example: 'ipconfig',
    explanation: 'Lists each adapter with its IPv4/IPv6 address, subnet mask and default gateway. Use /all for the full picture including DNS servers and DHCP details.',
    expectedOutput: 'Healthy: a valid IPv4 address on the expected subnet and a default gateway. Unhealthy: an address starting 169.254 (no DHCP lease), "Media disconnected", or no gateway.',
    whenToUse: 'First look at any connectivity problem. Not enough on its own when you need DNS servers or the DHCP server, so move to ipconfig /all.',
    risks: 'Read-only. No changes made.', risk: 'safe', needsAdmin: false,
    related: ['ipconfig-all', 'ping', 'get-netipconfiguration'], keywords: ['ip address', 'gateway', 'adapter', 'network'],
  },
  {
    id: 'ipconfig-all', group: 'Networking', name: 'ipconfig /all', shell: 'both',
    syntax: 'ipconfig /all',
    purpose: 'Show full adapter details: MAC, DHCP, lease times, DNS servers.',
    example: 'ipconfig /all',
    explanation: 'Expands ipconfig with the physical (MAC) address, whether DHCP is enabled, which DHCP server issued the lease, lease obtained/expires times and the DNS servers.',
    expectedOutput: 'Healthy: DHCP Enabled Yes with a lease from the expected server and sensible DNS servers. Unhealthy: Autoconfiguration IPv4 address (169.254.x.x), unexpected DHCP server, or missing/odd DNS servers.',
    whenToUse: 'Diagnosing DHCP, DNS and wrong-network problems. Redact MAC and IP addresses before putting output in tickets where they are not needed.',
    risks: 'Read-only. Output contains identifying network details, so redact before sharing.', risk: 'safe', needsAdmin: false,
    related: ['ipconfig', 'ipconfig-release-renew', 'nslookup', 'getmac'], keywords: ['dhcp', 'dns servers', 'mac address', 'lease', 'apipa'],
  },
  {
    id: 'ipconfig-release-renew', group: 'Networking', name: 'ipconfig /release and /renew', shell: 'both',
    syntax: 'ipconfig /release [<adapter>]\nipconfig /renew [<adapter>]',
    purpose: 'Drop the current DHCP lease and request a new one.',
    example: 'ipconfig /release\nipconfig /renew',
    explanation: 'Release gives up the current lease, so the adapter loses its address. Renew asks the DHCP server for a lease again. Together they refresh a stale or wrong lease.',
    expectedOutput: 'Healthy: after renew, a valid address on the expected subnet. Unhealthy: the adapter keeps or returns to a 169.254.x.x address, or the renew command times out, which suggests no DHCP server is reachable.',
    whenToUse: 'Wrong subnet, stale lease, or after moving a device between networks. Not useful for static addresses.',
    risks: 'Drops the connection briefly. Do not run it over a remote session on the same adapter unless you can reconnect. Does not change static settings.', risk: 'caution', needsAdmin: true,
    related: ['ipconfig-all', 'netsh-int-ip-reset', 'ping'], keywords: ['renew lease', 'release', 'dhcp', 'refresh ip'],
  },
  {
    id: 'ipconfig-flushdns', group: 'Networking', name: 'ipconfig /flushdns', shell: 'both',
    syntax: 'ipconfig /flushdns',
    purpose: 'Clear the local DNS resolver cache.',
    example: 'ipconfig /flushdns',
    explanation: 'Removes cached name lookups so the next lookup asks the DNS server again. Useful after a DNS record is corrected.',
    expectedOutput: 'Healthy: "Successfully flushed the DNS Resolver Cache." If it reports a function failure, you are probably not elevated.',
    whenToUse: 'A name resolves to an old or wrong address, or after fixing a DNS record. It does not fix a wrong DNS server setting.',
    risks: 'Low. Names will be looked up again, which may cause a brief delay.', risk: 'caution', needsAdmin: true,
    related: ['ipconfig-displaydns', 'nslookup', 'ipconfig-all'], keywords: ['dns cache', 'stale dns', 'clear cache'],
  },
  {
    id: 'ipconfig-displaydns', group: 'Networking', name: 'ipconfig /displaydns', shell: 'both',
    syntax: 'ipconfig /displaydns',
    purpose: 'Show the contents of the local DNS cache.',
    example: 'ipconfig /displaydns | findstr /i example.co.uk',
    explanation: 'Prints cached DNS records with their remaining time to live. Filtering with findstr keeps the output manageable.',
    expectedOutput: 'Healthy: records for recently visited names with plausible addresses. Unhealthy: an old or wrong address for the name you are testing, or a cached failure record.',
    whenToUse: 'To see whether a wrong answer is coming from the local cache before blaming the server.',
    risks: 'Read-only. Output reveals sites visited, so treat it as private.', risk: 'safe', needsAdmin: false,
    related: ['ipconfig-flushdns', 'nslookup'], keywords: ['dns cache', 'cached records'],
  },
  {
    id: 'ping', group: 'Networking', name: 'ping', shell: 'both',
    syntax: 'ping <host> [-n <count>] [-t] [-l <size>] [-4]',
    purpose: 'Test whether a host replies and measure round-trip time.',
    example: 'ping -n 20 192.0.2.1',
    explanation: 'Sends ICMP echo requests and reports replies, time and loss. -t pings until stopped (Ctrl+C), -n sets the count, -l the packet size, -4 forces IPv4.',
    expectedOutput: 'Healthy: replies with stable low times and 0% loss. Unhealthy: "Request timed out" (no reply, or ICMP blocked), high or varying times, or "Destination host unreachable" from a router.',
    whenToUse: 'Basic reachability and loss tests. A failed ping does not always mean the host is down, because firewalls often block ICMP.',
    risks: 'Read-only. Avoid large, continuous pings to third-party hosts.', risk: 'safe', needsAdmin: false,
    related: ['tracert', 'pathping', 'test-netconnection'], keywords: ['connectivity', 'latency', 'packet loss', 'reachable'],
  },
  {
    id: 'tracert', group: 'Networking', name: 'tracert', shell: 'both',
    syntax: 'tracert [-d] [-h <max_hops>] <host>',
    purpose: 'Show the path packets take to a destination.',
    example: 'tracert -d 198.51.100.10',
    explanation: 'Lists each router (hop) on the way with three response times. -d skips name lookups so it runs faster.',
    expectedOutput: 'Healthy: hops responding with gradually increasing times until the destination. Unhealthy: timeouts from a hop onwards. Note that some routers simply do not answer trace probes.',
    whenToUse: 'Finding where along the path traffic stops or slows. Use pathping for loss per hop.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['pathping', 'ping', 'route-print'], keywords: ['trace route', 'hops', 'path'],
  },
  {
    id: 'pathping', group: 'Networking', name: 'pathping', shell: 'both',
    syntax: 'pathping [-n] [-q <queries>] <host>',
    purpose: 'Combine ping and tracert to measure loss and latency at each hop.',
    example: 'pathping -n -q 50 198.51.100.10',
    explanation: 'Traces the route, then sends probes to every hop for a period and reports the loss percentage at each. It takes minutes to complete.',
    expectedOutput: 'Healthy: little or no loss. Unhealthy: loss that starts at a hop and continues in later hops. Loss only on one hop that does not continue is usually that router de-prioritising probes.',
    whenToUse: 'Intermittent packet loss and slowness where ping alone does not show where the problem starts.',
    risks: 'Read-only, but generates traffic for a few minutes.', risk: 'safe', needsAdmin: false,
    related: ['tracert', 'ping'], keywords: ['packet loss', 'slow network', 'latency by hop'],
  },
  {
    id: 'nslookup', group: 'Networking', name: 'nslookup', shell: 'both',
    syntax: 'nslookup <name> [<dns-server>]\nnslookup -type=<type> <name> [<dns-server>]',
    purpose: 'Query a DNS server for a name.',
    example: 'nslookup example.co.uk 192.0.2.53',
    explanation: 'Asks your default (or a specified) DNS server to resolve a name, showing which server answered and the result. -type=MX, TXT, NS and others query other record types.',
    expectedOutput: 'Healthy: the server name and a "Name/Address" answer. Unhealthy: "DNS request timed out", "Non-existent domain" (NXDOMAIN) or "Can\'t find".',
    whenToUse: 'Checking what a specific DNS server returns, and comparing servers. Note that nslookup uses its own resolver logic, so also test with ping or Resolve-DnsName.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['ipconfig-flushdns', 'ipconfig-all', 'ping'], keywords: ['dns', 'resolve', 'name resolution', 'mx record'],
  },
  {
    id: 'arp-a', group: 'Networking', name: 'arp -a', shell: 'both',
    syntax: 'arp -a [<ip>]',
    purpose: 'Show the ARP cache that maps IP addresses to MAC addresses.',
    example: 'arp -a',
    explanation: 'Lists IPv4 addresses the machine has recently talked to on the local network, with their MAC addresses.',
    expectedOutput: 'Healthy: the gateway has a MAC entry after you ping it. Unhealthy: gateway "incomplete" or two IPs sharing a suspicious MAC, which can indicate a conflict.',
    whenToUse: 'Checking local reachability and hunting address conflicts or identifying a device by MAC.',
    risks: 'Read-only in this form. Avoid arp -d unless you know why.', risk: 'safe', needsAdmin: false,
    related: ['getmac', 'ping', 'ipconfig-all'], keywords: ['mac address', 'ip conflict', 'neighbour'],
  },
  {
    id: 'netstat-ano', group: 'Networking', name: 'netstat -ano', shell: 'both',
    syntax: 'netstat -ano [| findstr <text>]',
    purpose: 'List network connections and listening ports with the owning process ID.',
    example: 'netstat -ano | findstr ESTABLISHED',
    explanation: 'Shows protocol, local and remote address, state and PID for each connection. Match the PID to a process with tasklist or Get-Process.',
    expectedOutput: 'Healthy: connections that match known applications. Unhealthy: unexplained outbound connections or unfamiliar listening ports owned by odd processes. Verify before concluding anything.',
    whenToUse: 'Finding what is using a port or what a process is connected to. Useful in suspicious software triage.',
    risks: 'Read-only. Output shows remote addresses, so treat it as private.', risk: 'safe', needsAdmin: false,
    related: ['tasklist', 'get-process', 'test-netconnection'], keywords: ['open ports', 'connections', 'listening', 'pid'],
  },
  {
    id: 'route-print', group: 'Networking', name: 'route print', shell: 'both',
    syntax: 'route print',
    purpose: 'Display the IP routing table.',
    example: 'route print -4',
    explanation: 'Shows the routes Windows uses, including the default route (0.0.0.0) and metrics. Several adapters or a VPN can add competing routes.',
    expectedOutput: 'Healthy: one clear default route via the expected gateway. Unhealthy: multiple default routes, a VPN route taking precedence, or no route to the subnet you need.',
    whenToUse: 'Connected to the network but cannot reach a subnet, or traffic goes the wrong way over VPN.',
    risks: 'Read-only here. route add/delete change routing and can cut off connectivity.', risk: 'safe', needsAdmin: false,
    related: ['ipconfig-all', 'tracert'], keywords: ['routing table', 'default route', 'vpn routes'],
  },
  {
    id: 'getmac', group: 'Networking', name: 'getmac', shell: 'both',
    syntax: 'getmac [/v] [/fo table]',
    purpose: 'Show the MAC address of each network adapter.',
    example: 'getmac /v /fo table',
    explanation: 'Lists adapter names and physical addresses. /v adds the connection name and transport.',
    expectedOutput: 'A table of adapter names and MAC addresses. "Media disconnected" appears for adapters that are not connected.',
    whenToUse: 'You need the MAC to register a device, create a DHCP reservation, or match it in ARP or switch tables.',
    risks: 'Read-only. MAC addresses are identifiers, so redact in shared notes.', risk: 'safe', needsAdmin: false,
    related: ['arp-a', 'ipconfig-all'], keywords: ['mac address', 'physical address'],
  },
  {
    id: 'test-netconnection', group: 'Networking', name: 'Test-NetConnection', shell: 'powershell',
    syntax: 'Test-NetConnection -ComputerName <host> [-Port <port>] [-InformationLevel Detailed]',
    purpose: 'Test connectivity to a host and optionally a TCP port.',
    example: 'Test-NetConnection -ComputerName 192.0.2.20 -Port 9100',
    explanation: 'Pings the host and, if a port is given, tests a TCP connection to that port. Shows the source address and interface used. The alias is tnc.',
    expectedOutput: 'Healthy: TcpTestSucceeded : True. Unhealthy: TcpTestSucceeded : False (port closed, filtered or service down) while ping succeeds.',
    whenToUse: 'Checking a service port, such as 445 for file shares, 443 for HTTPS or 9100 for printing, rather than just ICMP.',
    risks: 'Read-only. A successful test only shows the port accepts connections.', risk: 'safe', needsAdmin: false,
    related: ['ping', 'netstat-ano', 'tracert'], keywords: ['tnc', 'port test', 'tcp port', 'telnet'],
  },
  {
    id: 'get-netipconfiguration', group: 'Networking', name: 'Get-NetIPConfiguration', shell: 'powershell',
    syntax: 'Get-NetIPConfiguration [-Detailed] [-InterfaceAlias <name>]',
    purpose: 'Show IP, gateway and DNS configuration in a compact PowerShell view.',
    example: 'Get-NetIPConfiguration -Detailed',
    explanation: 'Summarises each interface with its IPv4/IPv6 addresses, default gateway and DNS servers. -Detailed adds profile and DHCP information.',
    expectedOutput: 'Healthy: each connected interface shows an address, gateway and DNS servers. Unhealthy: missing gateway or DNS, or an unexpected interface order.',
    whenToUse: 'A quick, readable alternative to ipconfig /all in PowerShell, and easy to filter.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['ipconfig-all', 'route-print'], keywords: ['ip config', 'dns servers', 'powershell'],
  },
  {
    id: 'netsh-wlan-show-interfaces', group: 'Networking', name: 'netsh wlan show interfaces', shell: 'both',
    syntax: 'netsh wlan show interfaces',
    purpose: 'Show details of the current Wi-Fi connection.',
    example: 'netsh wlan show interfaces',
    explanation: 'Reports the SSID, BSSID, radio type, channel, signal strength, receive and transmit rates and authentication used.',
    expectedOutput: 'Healthy: State connected, strong signal and a modern radio type. Unhealthy: low signal, an old radio type, or a state that flips between connected and disconnected.',
    whenToUse: 'Diagnosing weak signal, wrong band or roaming problems from the client side.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['netsh-wlan-report', 'ipconfig-all'], keywords: ['wifi', 'signal', 'ssid', 'wireless'],
  },
  {
    id: 'netsh-wlan-report', group: 'Networking', name: 'netsh wlan show wlanreport', shell: 'both',
    syntax: 'netsh wlan show wlanreport',
    purpose: 'Generate an HTML report of recent Wi-Fi sessions and disconnect reasons.',
    example: 'netsh wlan show wlanreport',
    explanation: 'Builds a report covering the last few days of Wi-Fi activity, showing connection sessions, durations and reasons for disconnects. The command prints the report file location.',
    expectedOutput: 'A path to wlan-report-latest.html. In the report, long sessions are healthy; many short sessions with repeated reasons indicate a pattern to investigate.',
    whenToUse: 'Intermittent Wi-Fi drops where you need evidence rather than a guess.',
    risks: 'Creates a report file only. The report names networks the device has used, so treat it as private.', risk: 'safe', needsAdmin: true,
    related: ['netsh-wlan-show-interfaces'], keywords: ['wifi report', 'disconnects', 'wireless history'],
  },
  {
    id: 'netsh-winsock-reset', group: 'Networking', name: 'netsh winsock reset', shell: 'both',
    syntax: 'netsh winsock reset',
    purpose: 'Reset the Winsock catalogue to defaults.',
    example: 'netsh winsock reset',
    explanation: 'Removes third-party layered providers and restores the Winsock catalogue. It can fix odd connectivity problems left by VPN, security or proxy software. A reboot is required.',
    expectedOutput: '"Successfully reset the Winsock Catalog. You must restart the computer in order to complete the reset."',
    whenToUse: 'As a late step when connectivity is broken at the software level and simpler checks have not found the cause.',
    risks: 'Needs a reboot. Can remove hooks installed by VPN or security clients, so those may need reinstalling or repairing. Do not use it as a first step.', risk: 'caution', needsAdmin: true,
    related: ['netsh-int-ip-reset', 'ipconfig-release-renew'], keywords: ['reset network', 'winsock', 'network stack'],
  },
  {
    id: 'netsh-int-ip-reset', group: 'Networking', name: 'netsh int ip reset', shell: 'both',
    syntax: 'netsh int ip reset [<logfile>]',
    purpose: 'Reset the TCP/IP stack configuration to defaults.',
    example: 'netsh int ip reset',
    explanation: 'Rewrites TCP/IP related registry settings back to defaults. It is a heavier reset than releasing and renewing a lease. A reboot is needed.',
    expectedOutput: 'A list of items reset. Some may report access denied if not elevated. Restart afterwards.',
    whenToUse: 'A late step for a corrupted TCP/IP stack after simpler fixes fail.',
    risks: 'May wipe static IP settings and other customisation. Record the current configuration first (ipconfig /all). Needs a reboot. Do not run over a remote session you cannot reconnect.', risk: 'caution', needsAdmin: true,
    related: ['netsh-winsock-reset', 'ipconfig-all'], keywords: ['tcp/ip reset', 'reset ip stack'],
  },

  // ============================================================ WINDOWS
  {
    id: 'systeminfo', group: 'Windows', name: 'systeminfo', shell: 'both',
    syntax: 'systeminfo [/s <computer>]',
    purpose: 'Show OS version, boot time, hardware summary and installed hotfixes.',
    example: 'systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Boot Time"',
    explanation: 'Reports OS name and build, install date, last boot time, processor, BIOS, memory, network cards and hotfixes. Takes a few seconds.',
    expectedOutput: 'A long list of properties. Useful checks: OS build matches expectations, boot time is recent, and available memory is not exhausted.',
    whenToUse: 'Capturing a quick inventory for a ticket, or checking uptime and build.',
    risks: 'Read-only. Output includes identifying details; redact before sharing.', risk: 'safe', needsAdmin: false,
    related: ['get-computerinfo', 'get-hotfix', 'reliability-monitor'], keywords: ['uptime', 'os version', 'build', 'inventory'],
  },
  {
    id: 'get-computerinfo', group: 'Windows', name: 'Get-ComputerInfo', shell: 'powershell',
    syntax: 'Get-ComputerInfo [-Property <name>[,<name>]]',
    purpose: 'Return detailed system information as PowerShell objects.',
    example: 'Get-ComputerInfo -Property OsName,OsVersion,OsLastBootUpTime,CsTotalPhysicalMemory',
    explanation: 'Gathers OS, hardware and BIOS properties. Without -Property it can be slow and verbose, so ask for the fields you need.',
    expectedOutput: 'The requested properties. Healthy values are those consistent with the device specification.',
    whenToUse: 'Scripted or filtered inventory where systeminfo text is awkward to parse.',
    risks: 'Read-only. Slow without -Property.', risk: 'safe', needsAdmin: false,
    related: ['systeminfo', 'get-hotfix'], keywords: ['inventory', 'hardware info', 'bios'],
  },
  {
    id: 'sfc-scannow', group: 'Windows', name: 'sfc /scannow', shell: 'both',
    syntax: 'sfc /scannow',
    purpose: 'Scan protected Windows system files and repair damaged ones.',
    example: 'sfc /scannow',
    explanation: 'System File Checker compares protected system files with cached known-good copies and replaces mismatches. Run it from an elevated prompt and let it finish. Details go to the CBS.log.',
    expectedOutput: '"did not find any integrity violations" (clean); "found corrupt files and successfully repaired them" (fixed, reboot and re-run); "found corrupt files but was unable to fix some of them" (run DISM RestoreHealth then SFC again).',
    whenToUse: 'Suspected system file corruption, strange system errors and failed updates. Run SFC after DISM RestoreHealth if the component store is damaged.',
    risks: 'Generally safe but takes a while and uses disk. If it cannot repair, back up data and consider escalation or reimage rather than repeating blindly.', risk: 'caution', needsAdmin: true,
    related: ['dism-checkhealth', 'dism-restorehealth', 'chkdsk'], keywords: ['system file checker', 'corruption', 'repair windows'],
  },
  {
    id: 'dism-checkhealth', group: 'Windows', name: 'DISM /Online /Cleanup-Image /CheckHealth', shell: 'both',
    syntax: 'DISM /Online /Cleanup-Image /CheckHealth\nDISM /Online /Cleanup-Image /ScanHealth',
    purpose: 'Check whether the Windows component store is flagged as corrupt.',
    example: 'DISM /Online /Cleanup-Image /CheckHealth',
    explanation: 'CheckHealth quickly reports whether corruption has already been detected. ScanHealth performs a deeper scan that takes longer. Neither makes changes.',
    expectedOutput: '"No component store corruption detected" is healthy. "The component store is repairable" means run RestoreHealth.',
    whenToUse: 'Before attempting repairs, or when SFC cannot fix problems.',
    risks: 'Read-only checks. ScanHealth can take a long time and uses CPU and disk.', risk: 'safe', needsAdmin: true,
    related: ['dism-restorehealth', 'sfc-scannow'], keywords: ['component store', 'winsxs', 'scanhealth'],
  },
  {
    id: 'dism-restorehealth', group: 'Windows', name: 'DISM /Online /Cleanup-Image /RestoreHealth', shell: 'both',
    syntax: 'DISM /Online /Cleanup-Image /RestoreHealth [/Source:<path>] [/LimitAccess]',
    purpose: 'Repair the Windows component store.',
    example: 'DISM /Online /Cleanup-Image /RestoreHealth',
    explanation: 'Repairs the component store using Windows Update or a specified source. It can take a long time and may appear to pause. Run SFC afterwards.',
    expectedOutput: '"The restore operation completed successfully" is healthy. Errors about source files mean it needs a valid source (matching Windows version) or internet access.',
    whenToUse: 'CheckHealth or ScanHealth reports repairable corruption, or SFC cannot repair files.',
    risks: 'Takes time and network access. Changes system files. Back up important data first, and escalate or reimage if repeated repairs fail.', risk: 'caution', needsAdmin: true,
    related: ['dism-checkhealth', 'sfc-scannow'], keywords: ['repair component store', 'windows repair'],
  },
  {
    id: 'chkdsk', group: 'Windows', name: 'chkdsk', shell: 'both',
    syntax: 'chkdsk <drive>: [/f] [/r] [/scan]',
    purpose: 'Check a volume for file system errors and optionally repair them.',
    example: 'chkdsk C:',
    explanation: 'Without switches it runs read-only and reports problems. /f fixes file system errors and for the system drive schedules a check at the next restart. /r also scans for bad sectors and attempts to recover data, which takes much longer.',
    expectedOutput: '"Windows has scanned the file system and found no problems" is healthy. Reports of errors, bad sectors or unreadable files suggest corruption or a failing disk.',
    whenToUse: 'File system errors, unexpected shutdown damage, or checking a suspect drive. On an SSD, bad-sector scans are rarely the answer, so check drive health first.',
    risks: '/f and /r modify the volume and can remove corrupted data. Running /r on a failing drive can stress it further. Back up first where possible and check the drive health.', risk: 'caution', needsAdmin: true,
    related: ['get-physicaldisk', 'get-volume', 'sfc-scannow'], keywords: ['disk check', 'file system', 'bad sectors'],
  },
  {
    id: 'tasklist', group: 'Windows', name: 'tasklist', shell: 'both',
    syntax: 'tasklist [/v] [/svc] [/fi "<filter>"]',
    purpose: 'List running processes.',
    example: 'tasklist /svc /fi "imagename eq svchost.exe"',
    explanation: 'Shows process name, PID, session and memory. /svc lists the services hosted by each process, /v adds user and window title, and /fi applies a filter.',
    expectedOutput: 'A table of processes. Look for very high memory use, duplicated or unfamiliar processes, and match PIDs from netstat.',
    whenToUse: 'Quick command-line process check, especially over a remote shell.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-process', 'taskkill', 'netstat-ano'], keywords: ['processes', 'running programs', 'pid'],
  },
  {
    id: 'taskkill', group: 'Windows', name: 'taskkill', shell: 'both',
    syntax: 'taskkill /pid <pid> | /im <image> [/f] [/t]',
    purpose: 'End a running process.',
    example: 'taskkill /im notepad.exe',
    explanation: 'Asks a process to close. /f forces it to end without letting it save, and /t also ends child processes.',
    expectedOutput: '"SUCCESS: Sent termination signal" or "SUCCESS: The process ... has been terminated". "Access is denied" means you need elevation or the process is protected.',
    whenToUse: 'A hung application will not close normally. Prefer asking the user to save their work first.',
    risks: 'Forcing a process to end can lose unsaved work and corrupt files. Ending the wrong process (system or security services) can destabilise the machine. Confirm the PID or image name first.', risk: 'destructive', needsAdmin: false,
    related: ['tasklist', 'get-process', 'net-stop-start'], keywords: ['kill process', 'end task', 'hung application'],
  },
  {
    id: 'sc-query', group: 'Windows', name: 'sc query', shell: 'both',
    syntax: 'sc query [<service>] | sc qc <service>',
    purpose: 'Show the state or configuration of a Windows service.',
    example: 'sc query Spooler',
    explanation: 'sc query reports whether a service is running. sc qc shows its configuration including start type and the account it runs as.',
    expectedOutput: 'STATE: RUNNING is healthy for an expected service. STOPPED or a failure to start, together with the start type, helps explain problems.',
    whenToUse: 'Checking a service quickly from CMD, including over remote shells.',
    risks: 'Read-only. Other sc subcommands (stop, config, delete) change services.', risk: 'safe', needsAdmin: false,
    related: ['get-service', 'net-stop-start'], keywords: ['service status', 'services'],
  },
  {
    id: 'net-stop-start', group: 'Windows', name: 'net stop / net start', shell: 'both',
    syntax: 'net stop <service>\nnet start <service>',
    purpose: 'Stop or start a Windows service.',
    example: 'net stop wuauserv\nnet start wuauserv',
    explanation: 'Stops or starts a service by its service name. Used to restart a stuck service or to stop it while files it uses are cleared.',
    expectedOutput: '"The ... service was stopped/started successfully." Failures state a reason, such as dependencies or access denied.',
    whenToUse: 'A service is hung, or a repair procedure requires it to be stopped temporarily.',
    risks: 'Stopping a service interrupts what depends on it, and stopping the wrong one (security, networking) can cause outages. Confirm the service and dependents first.', risk: 'caution', needsAdmin: true,
    related: ['sc-query', 'get-service', 'restart-spooler'], keywords: ['restart service', 'stop service'],
  },
  {
    id: 'get-service', group: 'Windows', name: 'Get-Service', shell: 'powershell',
    syntax: 'Get-Service [-Name <name>] | Where-Object Status -eq <state>',
    purpose: 'List Windows services and their state.',
    example: "Get-Service | Where-Object { $_.Status -eq 'Stopped' -and $_.StartType -eq 'Automatic' }",
    explanation: 'Returns services with status and start type, easy to filter. Automatic services that are stopped can indicate a failed start.',
    expectedOutput: 'A list of services. Review automatic services that are stopped, bearing in mind some are triggered or delayed start by design.',
    whenToUse: 'Finding services that failed to start, or checking one service.',
    risks: 'Read-only. Start-Service, Stop-Service and Restart-Service change state.', risk: 'safe', needsAdmin: false,
    related: ['sc-query', 'net-stop-start'], keywords: ['services', 'automatic services stopped'],
  },
  {
    id: 'get-process', group: 'Windows', name: 'Get-Process', shell: 'powershell',
    syntax: 'Get-Process [-Name <name>] | Sort-Object CPU -Descending | Select-Object -First <n>',
    purpose: 'List running processes with resource use.',
    example: 'Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 10 Name,Id,CPU,WorkingSet',
    explanation: 'Returns processes as objects, so you can sort by CPU, memory or other fields. CPU is cumulative processor time in seconds, not current percentage.',
    expectedOutput: 'The top processes by your sort. Look for unexpected heavy processes, then confirm what they are before taking action.',
    whenToUse: 'Finding what is consuming memory or CPU, with sorting that tasklist lacks.',
    risks: 'Read-only. Stop-Process would end a process and can lose work.', risk: 'safe', needsAdmin: false,
    related: ['tasklist', 'taskkill', 'netstat-ano'], keywords: ['high cpu', 'memory usage', 'slow computer'],
  },
  {
    id: 'get-winevent', group: 'Windows', name: 'Get-WinEvent', shell: 'powershell',
    syntax: 'Get-WinEvent -FilterHashtable @{LogName=<log>; Level=<n>; StartTime=<date>} [-MaxEvents <n>]',
    purpose: 'Query Windows event logs.',
    example: "Get-WinEvent -FilterHashtable @{LogName='System'; Level=2; StartTime=(Get-Date).AddDays(-1)} -MaxEvents 30",
    explanation: 'Reads events from Event Viewer logs with filtering. Level 1 is critical, 2 error, 3 warning. Filtering is much faster than reading everything.',
    expectedOutput: 'Matching events with time, provider and message. Cluster errors around the time of a fault; one-off errors are often noise.',
    whenToUse: 'Correlating a crash, reboot or failure with logged errors.',
    risks: 'Read-only. Reading the Security log requires elevation, and logs can contain personal data.', risk: 'safe', needsAdmin: false,
    related: ['reliability-monitor', 'get-hotfix'], keywords: ['event viewer', 'errors', 'crash logs', 'event id'],
  },
  {
    id: 'get-hotfix', group: 'Windows', name: 'Get-HotFix', shell: 'powershell',
    syntax: 'Get-HotFix [| Sort-Object InstalledOn -Descending]',
    purpose: 'List installed Windows updates (hotfixes).',
    example: 'Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 10',
    explanation: 'Returns installed updates with KB number and install date. It does not list every kind of update (some servicing updates and drivers may be missing), so check Update history for the full picture.',
    expectedOutput: 'Recent KBs with dates. Healthy: updates installed recently. If a problem began on a date, look for a matching KB.',
    whenToUse: 'Checking patch level, or whether a problem started after an update.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['systeminfo', 'get-winevent'], keywords: ['kb', 'updates installed', 'patch level'],
  },
  {
    id: 'gpupdate-force', group: 'Windows', name: 'gpupdate /force', shell: 'both',
    syntax: 'gpupdate /force',
    purpose: 'Reapply Group Policy settings immediately.',
    example: 'gpupdate /force',
    explanation: 'Reprocesses all policy settings rather than only changes. Some settings require a logoff or restart, and the command may prompt for it.',
    expectedOutput: '"Computer Policy update has completed successfully" and the same for User Policy. Errors point to connectivity to a domain controller or policy processing failures.',
    whenToUse: 'A new or changed policy has not applied yet. Not relevant to devices without Group Policy.',
    risks: 'May prompt to log off or restart, which can interrupt the user. Policy changes can alter settings.', risk: 'caution', needsAdmin: true,
    related: ['gpresult', 'whoami-all'], keywords: ['group policy', 'refresh policy', 'domain'],
  },
  {
    id: 'gpresult', group: 'Windows', name: 'gpresult', shell: 'both',
    syntax: 'gpresult /r [/scope user|computer]\ngpresult /h <report.html>',
    purpose: 'Show which Group Policy objects applied to a user and computer.',
    example: 'gpresult /h C:\\Temp\\gpreport.html',
    explanation: '/r prints a summary in the console, and /h writes a detailed HTML report. Computer-scope results need an elevated prompt.',
    expectedOutput: 'Lists applied and denied GPOs with reasons. Healthy: expected GPOs applied. Unhealthy: missing GPOs or filtering reasons you did not expect.',
    whenToUse: 'A policy is not behaving as expected, or confirming what applies to a device.',
    risks: 'Read-only. Reports include account and domain names, so treat as sensitive.', risk: 'safe', needsAdmin: false,
    related: ['gpupdate-force', 'whoami-all'], keywords: ['rsop', 'applied policies', 'group policy results'],
  },
  {
    id: 'powercfg-batteryreport', group: 'Windows', name: 'powercfg /batteryreport', shell: 'both',
    syntax: 'powercfg /batteryreport [/output <file>]',
    purpose: 'Generate an HTML battery health and usage report for laptops.',
    example: 'powercfg /batteryreport /output "C:\\Temp\\battery-report.html"',
    explanation: 'Creates a report with design capacity versus full-charge capacity, cycle count (where reported) and recent usage.',
    expectedOutput: 'A file path. In the report, full-charge capacity far below design capacity indicates a worn battery.',
    whenToUse: 'Short battery life complaints or deciding whether a battery needs replacing.',
    risks: 'Creates a report file only.', risk: 'safe', needsAdmin: false,
    related: ['systeminfo', 'reliability-monitor'], keywords: ['battery health', 'laptop battery', 'capacity'],
  },
  {
    id: 'reliability-monitor', group: 'Windows', name: 'perfmon /rel', shell: 'both',
    syntax: 'perfmon /rel',
    purpose: 'Open Reliability Monitor to see a timeline of failures and changes.',
    example: 'perfmon /rel',
    explanation: 'Shows a stability index over time with application failures, Windows failures and software installs or updates. Clicking a day lists the events.',
    expectedOutput: 'A graph with red crosses for failures. Look for patterns coinciding with installs, updates or the date the user reports a problem.',
    whenToUse: 'Slowness or crashes with no obvious cause, and to see what changed before it started.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-winevent', 'get-hotfix'], keywords: ['stability', 'crashes timeline', 'reliability history'],
  },

  // ============================================================ USERS & ACCESS
  {
    id: 'whoami', group: 'Users & Access', name: 'whoami', shell: 'both',
    syntax: 'whoami [/upn | /fqdn]',
    purpose: 'Show the account the current session is running as.',
    example: 'whoami /upn',
    explanation: 'Prints DOMAIN\\user, or with /upn the user principal name (the sign-in address for work accounts). Useful to confirm which account a shell or remote session is using.',
    expectedOutput: 'The current account. Unexpected account names (for example the local administrator) mean the session is not running as you expect.',
    whenToUse: 'Confirming identity before changes, particularly in elevated or remote shells.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['whoami-all', 'quser', 'dsregcmd-status'], keywords: ['current user', 'upn', 'account'],
  },
  {
    id: 'whoami-all', group: 'Users & Access', name: 'whoami /groups, /priv', shell: 'both',
    syntax: 'whoami /groups\nwhoami /priv\nwhoami /all',
    purpose: 'Show group memberships and privileges of the current token.',
    example: 'whoami /groups',
    explanation: '/groups lists the groups in your token (and whether a Mandatory Label shows elevated), /priv lists privileges and whether they are enabled, /all combines everything.',
    expectedOutput: 'A list of groups. Check for Administrators, and High Mandatory Level if the prompt is elevated.',
    whenToUse: 'Why can or can\'t this user do something? Confirming elevation and group-based access.',
    risks: 'Read-only. Output may reveal internal group names.', risk: 'safe', needsAdmin: false,
    related: ['whoami', 'net-localgroup-administrators', 'gpresult'], keywords: ['groups', 'privileges', 'elevation', 'token'],
  },
  {
    id: 'net-user', group: 'Users & Access', name: 'net user', shell: 'both',
    syntax: 'net user [<username>] [/domain]',
    purpose: 'List local accounts or show account details.',
    example: 'net user',
    explanation: 'Alone, it lists local accounts. With a name it shows details such as active status, password last set and group membership. Adding /domain queries the domain.',
    expectedOutput: 'A list of accounts. Review for unexpected accounts, and check "Account active" and "Password last set" for a named user.',
    whenToUse: 'Reviewing local accounts or checking an account\'s state from the command line.',
    risks: 'Querying is read-only, but this command can also change accounts: specifying a password or /add changes or creates accounts. Be careful not to put passwords into command history.', risk: 'caution', needsAdmin: false,
    related: ['get-localuser', 'net-localgroup-administrators'], keywords: ['local accounts', 'user list', 'account status'],
  },
  {
    id: 'net-localgroup-administrators', group: 'Users & Access', name: 'net localgroup administrators', shell: 'both',
    syntax: 'net localgroup administrators',
    purpose: 'List members of the local Administrators group.',
    example: 'net localgroup administrators',
    explanation: 'Shows who has local administrator rights, including domain or cloud groups that were added.',
    expectedOutput: 'Healthy: only expected admin accounts and groups. Unhealthy: unfamiliar accounts, everyday users, or stale former staff.',
    whenToUse: 'Least-privilege reviews and security checks.',
    risks: 'Listing is read-only. The /add and /delete forms change membership, so use them only with authorisation and a record of the change.', risk: 'safe', needsAdmin: false,
    related: ['get-localgroupmember', 'net-user', 'whoami-all'], keywords: ['local admin', 'administrators group', 'privileged accounts'],
  },
  {
    id: 'quser', group: 'Users & Access', name: 'quser', shell: 'both',
    syntax: 'quser [<username>] [/server:<server>]',
    purpose: 'Show logged-on users and session state.',
    example: 'quser',
    explanation: 'Lists sessions with username, session name, ID, state (Active or Disc) and idle time. Also available as query user.',
    expectedOutput: 'Active and disconnected sessions. Healthy: only expected users. Many disconnected sessions can explain memory pressure on shared machines.',
    whenToUse: 'Checking who is logged on before remote work, reboots or maintenance.',
    risks: 'Read-only. Be careful with logoff or reset session commands that end sessions.', risk: 'safe', needsAdmin: false,
    related: ['whoami', 'tasklist'], keywords: ['logged on users', 'sessions', 'rdp'],
  },
  {
    id: 'get-localuser', group: 'Users & Access', name: 'Get-LocalUser', shell: 'powershell',
    syntax: 'Get-LocalUser [| Select-Object Name,Enabled,LastLogon,PasswordLastSet]',
    purpose: 'List local user accounts with state.',
    example: 'Get-LocalUser | Select-Object Name,Enabled,LastLogon,PasswordLastSet',
    explanation: 'Shows local accounts, whether they are enabled and when they last signed in or had a password set.',
    expectedOutput: 'Healthy: only expected accounts enabled. Unhealthy: unfamiliar enabled accounts or the built-in Administrator enabled without a reason.',
    whenToUse: 'Local account reviews on standalone or Entra-joined machines.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['net-user', 'get-localgroupmember'], keywords: ['local accounts', 'enabled accounts'],
  },
  {
    id: 'get-localgroupmember', group: 'Users & Access', name: 'Get-LocalGroupMember', shell: 'powershell',
    syntax: 'Get-LocalGroupMember -Group <group>',
    purpose: 'List the members of a local group.',
    example: "Get-LocalGroupMember -Group 'Administrators'",
    explanation: 'Returns members with name, object class and source. It can fail with an error if the group contains accounts whose SID cannot be resolved (for example deleted domain accounts); net localgroup is a useful fallback.',
    expectedOutput: 'Members of the group. Review for unknown users and nested groups.',
    whenToUse: 'Admin reviews where you want filterable PowerShell output.',
    risks: 'Read-only. Add- and Remove-LocalGroupMember change membership and need authorisation.', risk: 'safe', needsAdmin: false,
    related: ['net-localgroup-administrators', 'get-localuser'], keywords: ['group members', 'local admin'],
  },
  {
    id: 'dsregcmd-status', group: 'Users & Access', name: 'dsregcmd /status', shell: 'both',
    syntax: 'dsregcmd /status',
    purpose: 'Show device registration and join state (Entra ID / hybrid).',
    example: 'dsregcmd /status',
    explanation: 'Reports whether the device is Entra-joined, hybrid-joined or workplace-registered, the tenant, and the SSO state including whether a primary refresh token is present.',
    expectedOutput: 'Look at AzureAdJoined, DomainJoined, WorkplaceJoined and the SSO state (AzureAdPrt). A device not joined as expected, or without a token, can fail conditional access and SSO.',
    whenToUse: 'Sign-in loops, conditional access failures, or confirming how a device is joined.',
    risks: 'Read-only, but output includes tenant and device identifiers. Redact before sharing.', risk: 'safe', needsAdmin: false,
    related: ['whoami', 'gpresult'], keywords: ['entra', 'azure ad join', 'hybrid join', 'prt', 'sso'],
  },

  // ============================================================ DISK & STORAGE
  {
    id: 'get-physicaldisk', group: 'Disk & Storage', name: 'Get-PhysicalDisk', shell: 'powershell',
    syntax: 'Get-PhysicalDisk | Select-Object FriendlyName,MediaType,HealthStatus,OperationalStatus,Size',
    purpose: 'Show physical disk type and health as reported by Windows.',
    example: 'Get-PhysicalDisk | Select-Object FriendlyName,MediaType,HealthStatus,OperationalStatus,Size',
    explanation: 'Reports media type (SSD or HDD), health and operational status. HealthStatus Healthy is a good sign but not a guarantee, and some drives report limited data.',
    expectedOutput: 'Healthy: HealthStatus Healthy and OperationalStatus OK. Warning or Unhealthy deserves immediate backup and replacement planning.',
    whenToUse: 'Slow disk, file system errors or suspected failing drive.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-volume', 'chkdsk', 'diskpart-list-disk'], keywords: ['disk health', 'smart', 'ssd', 'failing drive'],
  },
  {
    id: 'get-volume', group: 'Disk & Storage', name: 'Get-Volume', shell: 'powershell',
    syntax: 'Get-Volume | Select-Object DriveLetter,FileSystemLabel,HealthStatus,SizeRemaining,Size',
    purpose: 'Show volumes, file systems and free space.',
    example: 'Get-Volume | Select-Object DriveLetter,FileSystemLabel,HealthStatus,SizeRemaining,Size',
    explanation: 'Lists volumes with free and total space and health. Low free space on the system drive causes slowness and update failures.',
    expectedOutput: 'Healthy: reasonable free space (often 15 to 20 percent or more) and Healthy status. Unhealthy: nearly full system drive.',
    whenToUse: 'Low space complaints and checking volumes before updates.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-physicaldisk', 'cleanmgr', 'chkdsk'], keywords: ['free space', 'disk space', 'storage'],
  },
  {
    id: 'diskpart-list-disk', group: 'Disk & Storage', name: 'diskpart (list disk / list volume)', shell: 'cmd',
    syntax: 'diskpart\nDISKPART> list disk\nDISKPART> list volume\nDISKPART> exit',
    purpose: 'Inspect disks and volumes using the DiskPart utility (read-only use).',
    example: 'diskpart\nlist disk\nlist volume\nexit',
    explanation: 'DiskPart is an interactive disk management tool. The list commands only display disks and volumes. The same tool can erase and repartition disks, so only run list and select commands unless you intend to change things.',
    expectedOutput: 'A table of disks with size and status, and volumes with letters and file systems. "Offline" or "No Media" entries are worth investigating.',
    whenToUse: 'When Disk Management is unavailable, or you need to confirm which disk is which before any change.',
    risks: 'DANGEROUS if misused. Commands such as clean, format, convert and delete can wipe data instantly with no confirmation. Always select the disk carefully and confirm with the client before any change.', risk: 'caution', needsAdmin: true,
    related: ['get-physicaldisk', 'get-volume', 'manage-bde-status'], keywords: ['partitions', 'disk management', 'list disk'],
  },
  {
    id: 'manage-bde-status', group: 'Disk & Storage', name: 'manage-bde -status', shell: 'both',
    syntax: 'manage-bde -status [<drive>:]',
    purpose: 'Show BitLocker encryption status.',
    example: 'manage-bde -status C:',
    explanation: 'Reports conversion status, percentage encrypted, protection status (On, Off or suspended) and key protector types for each volume.',
    expectedOutput: 'Healthy: Fully Encrypted with Protection On. Unhealthy: Protection Off, encryption in progress, or no key protectors.',
    whenToUse: 'Security checks, before firmware changes, or when a recovery prompt appears.',
    risks: 'Read-only in this form. Do not display or write recovery keys into tickets. Other manage-bde switches change protection.', risk: 'safe', needsAdmin: true,
    related: ['get-tpm', 'confirm-securebootuefi'], keywords: ['bitlocker', 'encryption', 'recovery key'],
  },
  {
    id: 'cleanmgr', group: 'Disk & Storage', name: 'cleanmgr', shell: 'both',
    syntax: 'cleanmgr /d <drive>',
    purpose: 'Run Disk Cleanup to free space.',
    example: 'cleanmgr /d C:',
    explanation: 'Opens Disk Cleanup for the drive, with options such as temporary files, the Recycle Bin, Windows Update cleanup and previous Windows installations. Use "Clean up system files" for the larger categories.',
    expectedOutput: 'A list of categories with sizes. After cleanup, free space increases.',
    whenToUse: 'Low disk space on a client where you have permission to clear temporary data.',
    risks: 'Deletes the selected files. Emptying the Recycle Bin or removing previous Windows versions cannot be undone, and may remove the ability to roll back an upgrade. Check with the user first.', risk: 'caution', needsAdmin: false,
    related: ['get-volume', 'get-physicaldisk'], keywords: ['disk cleanup', 'free space', 'temp files'],
  },

  // ============================================================ SECURITY
  {
    id: 'get-mpcomputerstatus', group: 'Security', name: 'Get-MpComputerStatus', shell: 'powershell',
    syntax: 'Get-MpComputerStatus | Select-Object AMServiceEnabled,AntivirusEnabled,RealTimeProtectionEnabled,AntivirusSignatureLastUpdated,IsTamperProtected',
    purpose: 'Show Microsoft Defender protection and signature status.',
    example: 'Get-MpComputerStatus | Select-Object AMServiceEnabled,AntivirusEnabled,RealTimeProtectionEnabled,AntivirusSignatureLastUpdated,IsTamperProtected',
    explanation: 'Reports whether the Defender service, antivirus and real-time protection are on, and when signatures were last updated. Run it elevated to avoid blank fields.',
    expectedOutput: 'Healthy: all enabled values True and signatures updated recently. False values or old signatures need investigation. If another antivirus is active, Defender may report as passive.',
    whenToUse: 'Security checklists, after malware concerns, and any "protection is off" report.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['update-mpsignature', 'start-mpscan', 'get-netfirewallprofile'], keywords: ['defender', 'antivirus', 'real-time protection', 'signatures'],
  },
  {
    id: 'update-mpsignature', group: 'Security', name: 'Update-MpSignature', shell: 'powershell',
    syntax: 'Update-MpSignature',
    purpose: 'Download the latest Defender security intelligence updates.',
    example: 'Update-MpSignature',
    explanation: 'Triggers an update of antivirus signatures from Microsoft update sources, subject to your network and any managed update configuration.',
    expectedOutput: 'No error and a newer AntivirusSignatureLastUpdated in Get-MpComputerStatus. Errors suggest connectivity, proxy or update-source problems.',
    whenToUse: 'Signatures are old, or before running a scan.',
    risks: 'Low risk. It uses network bandwidth briefly and may be controlled by management policy.', risk: 'caution', needsAdmin: true,
    related: ['get-mpcomputerstatus', 'start-mpscan'], keywords: ['defender update', 'definitions', 'security intelligence'],
  },
  {
    id: 'start-mpscan', group: 'Security', name: 'Start-MpScan', shell: 'powershell',
    syntax: 'Start-MpScan -ScanType QuickScan | FullScan | CustomScan [-ScanPath <path>]',
    purpose: 'Run a Microsoft Defender scan from PowerShell.',
    example: 'Start-MpScan -ScanType QuickScan',
    explanation: 'Starts a quick, full or custom scan. A full scan can take hours and slows the machine while it runs.',
    expectedOutput: 'Returns when the scan completes. Review detections with Get-MpThreatDetection or Windows Security. A clean scan is a snapshot, not proof the device is safe.',
    whenToUse: 'After suspicious behaviour, as part of maintenance, or when verifying a removal.',
    risks: 'Uses CPU and disk. If Defender quarantines files, tell the user and record what was removed.', risk: 'caution', needsAdmin: true,
    related: ['get-mpcomputerstatus', 'update-mpsignature', 'get-filehash'], keywords: ['malware scan', 'virus scan', 'full scan'],
  },
  {
    id: 'get-netfirewallprofile', group: 'Security', name: 'Get-NetFirewallProfile', shell: 'powershell',
    syntax: 'Get-NetFirewallProfile | Select-Object Name,Enabled,DefaultInboundAction,DefaultOutboundAction',
    purpose: 'Show Windows Firewall state per network profile.',
    example: 'Get-NetFirewallProfile | Select-Object Name,Enabled,DefaultInboundAction,DefaultOutboundAction',
    explanation: 'Lists the Domain, Private and Public profiles with whether the firewall is enabled and the default actions.',
    expectedOutput: 'Healthy: all profiles Enabled True with default inbound Block. A profile disabled needs a reason, such as a managed alternative firewall.',
    whenToUse: 'Security checks and diagnosing blocked connections.',
    risks: 'Read-only. Set-NetFirewallProfile changes protection, so avoid disabling the firewall as a test unless authorised and time-limited.', risk: 'safe', needsAdmin: false,
    related: ['get-mpcomputerstatus', 'test-netconnection'], keywords: ['firewall', 'windows firewall', 'profiles'],
  },
  {
    id: 'confirm-securebootuefi', group: 'Security', name: 'Confirm-SecureBootUEFI', shell: 'powershell',
    syntax: 'Confirm-SecureBootUEFI',
    purpose: 'Check whether Secure Boot is enabled.',
    example: 'Confirm-SecureBootUEFI',
    explanation: 'Returns True if Secure Boot is enabled and False if it is disabled. On a legacy BIOS system it reports that the cmdlet is not supported on this platform.',
    expectedOutput: 'True is healthy. False means disabled in firmware. The platform-not-supported error means the device boots in legacy BIOS mode.',
    whenToUse: 'Security checklists and Windows 11 readiness checks.',
    risks: 'Read-only. Changing Secure Boot in firmware can affect BitLocker and boot behaviour, so have the recovery key available.', risk: 'safe', needsAdmin: true,
    related: ['get-tpm', 'manage-bde-status'], keywords: ['secure boot', 'uefi', 'legacy bios'],
  },
  {
    id: 'get-tpm', group: 'Security', name: 'Get-Tpm', shell: 'powershell',
    syntax: 'Get-Tpm',
    purpose: 'Show Trusted Platform Module (TPM) status.',
    example: 'Get-Tpm',
    explanation: 'Reports whether a TPM is present, ready, enabled and activated.',
    expectedOutput: 'Healthy: TpmPresent True and TpmReady True. Not present or not ready means it may be disabled in firmware or not supported.',
    whenToUse: 'BitLocker, Windows Hello and Windows 11 checks.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: true,
    related: ['manage-bde-status', 'confirm-securebootuefi'], keywords: ['tpm', 'trusted platform module', 'windows 11'],
  },
  {
    id: 'get-filehash', group: 'Security', name: 'Get-FileHash', shell: 'powershell',
    syntax: 'Get-FileHash -Path <file> [-Algorithm SHA256]',
    purpose: 'Compute a cryptographic hash of a file.',
    example: 'Get-FileHash -Path "C:\\Users\\Public\\Downloads\\setup.exe" -Algorithm SHA256',
    explanation: 'Calculates the file hash (SHA256 by default). Compare it with a published hash to verify a download, or look it up in a reputation service to check whether a file is known.',
    expectedOutput: 'A hash string. A match with the vendor\'s published hash indicates an unmodified file. A mismatch means the file differs.',
    whenToUse: 'Verifying downloads and identifying suspicious files without uploading the file itself.',
    risks: 'Read-only. Do not upload client files to public services.', risk: 'safe', needsAdmin: false,
    related: ['start-mpscan', 'get-startup-commands'], keywords: ['sha256', 'checksum', 'verify download', 'integrity'],
  },
  {
    id: 'get-startup-commands', group: 'Security', name: 'Get-CimInstance Win32_StartupCommand', shell: 'powershell',
    syntax: 'Get-CimInstance Win32_StartupCommand | Select-Object Name,Command,Location,User',
    purpose: 'List programs configured to start with Windows.',
    example: 'Get-CimInstance Win32_StartupCommand | Select-Object Name,Command,Location,User',
    explanation: 'Shows startup entries from common registry and startup folder locations. It does not include every persistence mechanism (scheduled tasks and services need separate checks).',
    expectedOutput: 'Known applications. Unfamiliar entries, especially pointing at temp or user profile folders, deserve investigation.',
    whenToUse: 'Slow boots and suspicious software triage.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-scheduledtask', 'get-process', 'get-filehash'], keywords: ['startup programs', 'autorun', 'persistence'],
  },
  {
    id: 'get-scheduledtask', group: 'Security', name: 'Get-ScheduledTask', shell: 'powershell',
    syntax: "Get-ScheduledTask | Where-Object State -ne 'Disabled' | Select-Object TaskName,TaskPath,State",
    purpose: 'List scheduled tasks.',
    example: "Get-ScheduledTask | Where-Object State -ne 'Disabled' | Select-Object TaskName,TaskPath,State",
    explanation: 'Returns scheduled tasks, which many applications and some malware use to run code. Look at recently added or oddly named tasks and what action they run.',
    expectedOutput: 'Mostly Microsoft and known vendor tasks. Investigate tasks with random names or actions that launch scripts from user or temp folders.',
    whenToUse: 'Checking persistence during suspicious software triage, and boot or logon slowness.',
    risks: 'Read-only. Some tasks are hidden without elevation.', risk: 'safe', needsAdmin: false,
    related: ['get-startup-commands', 'get-process'], keywords: ['scheduled tasks', 'persistence', 'task scheduler'],
  },

  // ============================================================ PRINTING
  {
    id: 'get-printer', group: 'Printing', name: 'Get-Printer', shell: 'powershell',
    syntax: 'Get-Printer [-Name <name>] | Select-Object Name,DriverName,PortName,PrinterStatus',
    purpose: 'List installed printers with driver, port and status.',
    example: 'Get-Printer | Select-Object Name,DriverName,PortName,PrinterStatus',
    explanation: 'Shows each printer queue with its driver and port. Compare the port with the device\'s current address when a printer shows offline.',
    expectedOutput: 'A list of queues. Healthy: Normal status and a port matching the device. Offline or Error status prompts connectivity and queue checks.',
    whenToUse: 'First look at a printing problem on a client or print server.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-printerport', 'get-printjob', 'get-printerdriver'], keywords: ['printers', 'print queue', 'offline printer'],
  },
  {
    id: 'get-printjob', group: 'Printing', name: 'Get-PrintJob', shell: 'powershell',
    syntax: "Get-PrintJob -PrinterName '<printer>'",
    purpose: 'List jobs waiting in a printer queue.',
    example: "Get-PrintJob -PrinterName 'Office-MFP-01'",
    explanation: 'Shows job IDs, owners, size and status for a queue. One job in an error state often blocks the rest.',
    expectedOutput: 'Healthy: an empty queue or jobs that move. Unhealthy: a job stuck in error or deleting at the head of the queue.',
    whenToUse: 'Jobs are stuck or not printing.',
    risks: 'Read-only. Remove-PrintJob deletes jobs, so check ownership first.', risk: 'safe', needsAdmin: false,
    related: ['get-printer', 'restart-spooler', 'clear-print-queue'], keywords: ['stuck job', 'print jobs'],
  },
  {
    id: 'get-printerport', group: 'Printing', name: 'Get-PrinterPort', shell: 'powershell',
    syntax: 'Get-PrinterPort | Select-Object Name,PrinterHostAddress,PortNumber',
    purpose: 'List printer ports and the addresses they point to.',
    example: 'Get-PrinterPort | Select-Object Name,PrinterHostAddress,PortNumber',
    explanation: 'Shows TCP/IP ports with the host address and port number. A port pointing to an old IP is a frequent cause of offline printers.',
    expectedOutput: 'Healthy: PrinterHostAddress matches the device\'s current address and port 9100 or the expected one.',
    whenToUse: 'Printer shows offline and you suspect an address change.',
    risks: 'Read-only.', risk: 'safe', needsAdmin: false,
    related: ['get-printer', 'test-netconnection', 'ping'], keywords: ['printer ip', 'tcp/ip port', 'wsd'],
  },
  {
    id: 'get-printerdriver', group: 'Printing', name: 'Get-PrinterDriver', shell: 'powershell',
    syntax: 'Get-PrinterDriver | Select-Object Name,PrinterEnvironment,DriverVersion,Manufacturer',
    purpose: 'List installed printer drivers and versions.',
    example: 'Get-PrinterDriver | Select-Object Name,PrinterEnvironment,DriverVersion,Manufacturer',
    explanation: 'Shows which drivers are installed, their architecture and version. Multiple or generic drivers can explain feature loss or conflicts.',
    expectedOutput: 'The expected vendor driver at a current version. Unexpected generic drivers may explain missing options.',
    whenToUse: 'Garbled output, missing features, or problems after a driver or Windows update.',
    risks: 'Read-only. Removing drivers on a print server affects all clients.', risk: 'safe', needsAdmin: false,
    related: ['get-printer', 'restart-spooler'], keywords: ['printer driver', 'driver version'],
  },
  {
    id: 'restart-spooler', group: 'Printing', name: 'Restart-Service Spooler', shell: 'both',
    syntax: 'Restart-Service -Name Spooler -Force\nnet stop spooler && net start spooler',
    purpose: 'Restart the Print Spooler service.',
    example: 'Restart-Service -Name Spooler -Force',
    explanation: 'Stops and restarts the service that manages print jobs. This often releases a hung queue but does not remove the cause.',
    expectedOutput: 'No error and the service running again. Check Get-Service Spooler.',
    whenToUse: 'The queue is stuck or printers are missing, before clearing spool files.',
    risks: 'Jobs currently printing may fail or be resent. On a print server it briefly affects every user.', risk: 'caution', needsAdmin: true,
    related: ['clear-print-queue', 'get-printjob', 'net-stop-start'], keywords: ['spooler', 'print service'],
  },
  {
    id: 'clear-print-queue', group: 'Printing', name: 'Clear print queue (stop spooler, delete spool files)', shell: 'cmd',
    syntax: 'net stop spooler\ndel /Q /F /S "%SystemRoot%\\System32\\spool\\PRINTERS\\*.*"\nnet start spooler',
    purpose: 'Remove every stuck job by clearing the spool folder.',
    example: 'net stop spooler\ndel /Q /F /S "%SystemRoot%\\System32\\spool\\PRINTERS\\*.*"\nnet start spooler',
    explanation: 'Stops the spooler, deletes all spool files and starts the service again. It removes every pending job for every printer on that machine, not just the stuck one.',
    expectedOutput: 'The service stops, files are deleted and the service starts. The queue shows empty afterwards.',
    whenToUse: 'A corrupt job will not delete and restarting the spooler did not help.',
    risks: 'DELETES ALL QUEUED PRINT JOBS for all users on that machine or server. Warn users and check for important jobs first. Make sure the path is typed exactly.', risk: 'destructive', needsAdmin: true,
    related: ['restart-spooler', 'get-printjob'], keywords: ['stuck queue', 'delete print jobs', 'spool folder'],
  },

  // ============================================================ MICROSOFT 365
  {
    id: 'outlook-safe', group: 'Microsoft 365', name: 'outlook.exe /safe', shell: 'both',
    syntax: 'outlook.exe /safe',
    purpose: 'Start desktop Outlook in safe mode with add-ins disabled.',
    example: 'outlook.exe /safe',
    explanation: 'Run from the Run box (Win+R) or a prompt. Starts Outlook without add-ins and some customisations. It prompts to choose a profile.',
    expectedOutput: 'Outlook opens with "Safe Mode" in the title bar. If a problem disappears in safe mode, an add-in or customisation is the likely cause.',
    whenToUse: 'Outlook crashes, hangs on start or behaves oddly, to separate add-in issues from profile or server issues.',
    risks: 'Low. Some features are unavailable in safe mode. Do not change settings there that you intend to keep.', risk: 'safe', needsAdmin: false,
    related: ['mlcfg32'], keywords: ['outlook safe mode', 'add-ins', 'outlook crash'],
  },
  {
    id: 'mlcfg32', group: 'Microsoft 365', name: 'control mlcfg32.cpl', shell: 'both',
    syntax: 'control mlcfg32.cpl',
    purpose: 'Open the Mail Setup control panel for classic Outlook profiles.',
    example: 'control mlcfg32.cpl',
    explanation: 'Opens Mail Setup where you can show profiles, add a new profile and set which profile Outlook uses. It exists when classic desktop Outlook is installed.',
    expectedOutput: 'The Mail Setup dialog. Show Profiles lists existing profiles; a new profile can be tested alongside the old one.',
    whenToUse: 'Profile corruption, loading profile hangs, or shared mailbox problems where you need a clean profile.',
    risks: 'Creating a profile is safe, but removing one deletes its settings (and may require re-downloading mail). Add a new profile rather than deleting the old one first.', risk: 'safe', needsAdmin: false,
    related: ['outlook-safe'], keywords: ['mail profile', 'new outlook profile', 'profile corrupt'],
  },
  {
    id: 'connect-exchangeonline', group: 'Microsoft 365', name: 'Connect-ExchangeOnline', shell: 'powershell',
    syntax: 'Install-Module ExchangeOnlineManagement -Scope CurrentUser\nConnect-ExchangeOnline -UserPrincipalName <admin@contoso.com>',
    purpose: 'Connect PowerShell to Exchange Online to query mailbox settings.',
    example: 'Connect-ExchangeOnline -UserPrincipalName admin@contoso.com',
    explanation: 'Needs the ExchangeOnlineManagement module and an account with a suitable role. Signs in (with MFA where required) and then allows Exchange Online cmdlets in that session.',
    expectedOutput: 'A sign-in prompt, then a connected session. Errors usually relate to module installation, MFA or insufficient role.',
    whenToUse: 'Admin-side checks such as mailbox permissions, but only when authorised by the client.',
    risks: 'Admin cmdlets in this session can change mailboxes and tenant settings. Use only the roles and accounts you are authorised for, stick to read-only Get- cmdlets for diagnosis, and disconnect afterwards with Disconnect-ExchangeOnline. Never store credentials in scripts or notes.', risk: 'caution', needsAdmin: false,
    related: ['get-mailboxpermission', 'get-recipientpermission'], keywords: ['exchange online', 'powershell', 'm365 admin'],
  },
  {
    id: 'get-mailboxpermission', group: 'Microsoft 365', name: 'Get-MailboxPermission', shell: 'powershell',
    syntax: "Get-MailboxPermission -Identity <mailbox> | Where-Object { $_.User -notlike 'NT AUTHORITY*' }",
    purpose: 'List Full Access (and other mailbox) permissions on a mailbox.',
    example: "Get-MailboxPermission -Identity shared@contoso.com | Where-Object { $_.User -notlike 'NT AUTHORITY*' }",
    explanation: 'Shows who has permissions such as FullAccess to the mailbox. Filtering out the built-in system entries makes the output readable.',
    expectedOutput: 'Healthy: the intended users or groups listed with FullAccess and Deny false. Missing entries explain access failures. Deny entries override allows.',
    whenToUse: 'A user cannot open a shared mailbox, after connecting to Exchange Online with an authorised role.',
    risks: 'Read-only. Add-MailboxPermission changes access and needs client authorisation.', risk: 'safe', needsAdmin: false,
    related: ['connect-exchangeonline', 'get-recipientpermission'], keywords: ['full access', 'shared mailbox', 'mailbox delegation'],
  },
  {
    id: 'get-recipientpermission', group: 'Microsoft 365', name: 'Get-RecipientPermission', shell: 'powershell',
    syntax: 'Get-RecipientPermission -Identity <mailbox>',
    purpose: 'List Send As permissions on a mailbox.',
    example: 'Get-RecipientPermission -Identity shared@contoso.com',
    explanation: 'Shows trustees with the SendAs access right for the mailbox. Send As is separate from Full Access, so a user may read a mailbox but be unable to send as it.',
    expectedOutput: 'Healthy: the intended senders listed with AccessRights SendAs. Missing entries explain send failures.',
    whenToUse: 'A user can open a shared mailbox but cannot send from it.',
    risks: 'Read-only. Add-RecipientPermission changes who can send as the mailbox and needs authorisation.', risk: 'safe', needsAdmin: false,
    related: ['get-mailboxpermission', 'connect-exchangeonline'], keywords: ['send as', 'send on behalf', 'shared mailbox'],
  },
];
