/** Orientation notes on well-known engineer tools. Original wording, generic example values only (documentation addresses). */
export interface EngTool { id: string; name: string; group: string; what: string; use: string; cmds: string[]; care?: string; job?: string; lab?: string }

export const ENG_GROUPS = ['Remote access and transfer', 'VPN and routing', 'Network and packets', 'Virtual machines and storage', 'Scripting and editing', 'Automation, secrets and logs', 'Testing and research', 'Building internal tools'];

export const ENG_TOOLS: EngTool[] = [
  { id: 'ssh', name: 'ssh', group: ENG_GROUPS[0], what: 'Encrypted remote shell, file copy and port forwarding to servers and network gear.',
    use: 'Any remote command-line work. Learn keys, jump hosts and tunnels properly.',
    cmds: ['ssh-keygen -t ed25519', 'ssh user@host', 'ssh -J jumphost user@host', 'ssh -L 8080:localhost:80 user@host   # local tunnel', 'ssh-keygen -t ed25519-sk   # key held on a hardware token'],
    care: 'On servers you own, turn off password sign-in (PasswordAuthentication no) once keys work, and keep a second way in until you have tested it. Protect private keys with a passphrase and never copy or paste them into notes.',
    job: 'Reaching customer servers and gear through the approved remote route only.' },
  { id: 'rsync', name: 'rsync', group: ENG_GROUPS[0], what: 'Copies and syncs files, sending only what changed. Works locally or over ssh.',
    use: 'Backups, migrations and "make this folder match that one", including over slow or flaky links (it resumes).',
    cmds: ['rsync -avh --progress src/ user@host:/dest/', 'rsync -avhn src/ dest/   # -n = dry run, shows what would happen', 'rsync -avh --delete src/ dest/   # makes dest an exact copy (deletes extras)'],
    care: 'A trailing slash on the source matters: src/ copies the contents, src copies the folder itself. Always dry-run (-n) before using --delete.' },
  { id: 'curl', name: 'curl and wget', group: ENG_GROUPS[0], what: 'Make web requests from the command line and download files.',
    use: 'Test how a web service or API really responds when a browser is broken or hides detail.',
    cmds: ['curl -I https://example.com   # headers only', 'curl -v https://example.com   # connection and certificate detail', 'curl -X POST -H "Content-Type: application/json" -d \'{"a":1}\' https://example.com/api', 'curl --resolve example.com:443:192.0.2.10 https://example.com/   # test a specific server', 'wget -c https://example.com/file.iso   # resume a download', 'wget --spider https://example.com   # check a URL exists'],
    care: 'curl -k switches off certificate checking. Use it only to confirm a certificate is the problem, never as a fix. Keep tokens out of command history.', lab: undefined },

  { id: 'wireguard', name: 'WireGuard and OpenVPN', group: ENG_GROUPS[1], what: 'Two widely used open-source VPN tunnels. WireGuard is small and fast; OpenVPN is older, flexible and very widely supported.',
    use: 'Site-to-site links, remote access to your own lab, secure paths into a network.',
    cmds: ['wg genkey | tee private.key | wg pubkey > public.key', 'wg-quick up wg0', 'wg show', 'openvpn --config client.ovpn'],
    care: 'The private key never leaves its device and never goes in notes or tickets. Share only the public key. Customer VPNs are theirs; do not change them without approval.' },
  { id: 'vyos', name: 'VyOS', group: ENG_GROUPS[1], what: 'An open-source router and firewall operating system you can run in a virtual machine.',
    use: 'A cheap way to practise routing, NAT, VLANs and firewall rules in a lab.',
    cmds: ['configure', 'set interfaces ethernet eth0 address 192.0.2.1/24', 'commit', 'save'],
    care: 'Lab use. Changes only take effect on commit and survive a reboot only after save. Build and break it in a VM, away from real networks.' },
  { id: 'iptables', name: 'iptables (and nftables)', group: ENG_GROUPS[1], what: 'The Linux packet filter used for firewall rules. Many newer systems use nftables, the successor.',
    use: 'Read, understand and write host firewall rules.',
    cmds: ['iptables -L -n -v   # list rules with counters', 'iptables -S   # rules as commands', 'nft list ruleset   # the nftables equivalent'],
    care: 'Rule order matters and a wrong rule can cut your own remote session. Test with a scheduled rollback, and keep console access. Read before you change.' },

  { id: 'nmap', name: 'nmap', group: ENG_GROUPS[2], what: 'Finds devices and open ports on a network and can identify services.',
    use: 'Asset discovery, checking which ports a device exposes, confirming a firewall change.',
    cmds: ['nmap -sn 192.0.2.0/24   # which hosts answer', 'nmap -p 9100,631,445 192.0.2.50   # check specific ports', 'nmap -sV 192.0.2.50   # try to identify services'],
    care: 'Scan only networks you are authorised to scan, in writing where it is a customer. Unapproved scanning can breach the contract and the law, and some older devices, printers included, react badly. Start gently.',
    job: 'Checking which print ports a printer really answers on, once you have permission.' },
  { id: 'wireshark', name: 'Wireshark, tshark and tcpdump', group: ENG_GROUPS[2], what: 'Capture and inspect network traffic. tcpdump and tshark are the command-line versions.',
    use: 'Prove what is on the wire when logs and guesses run out: DNS failures, retries, resets, who is talking to whom.',
    cmds: ['tcpdump -i eth0 host 192.0.2.50 and port 9100 -w cap.pcap', 'tshark -r cap.pcap', 'ip.addr == 192.0.2.50   # a Wireshark display filter', 'dns   # display filter: only DNS'],
    care: 'Captures can contain passwords, mail and customer data. Capture only what you need, only with permission, keep the file off shared places and delete it when finished. Never put a capture in this app.' },
  { id: 'arp', name: 'arp and arping', group: ENG_GROUPS[2], what: 'arp shows which hardware address your machine learned for each neighbour. arping asks "who has this address?" directly at layer 2.',
    use: 'Is that device on the wire at all, and is another device claiming the same address? Works even when ping is blocked.',
    cmds: ['arp -a   # Windows and Linux', 'ip neigh   # Linux', 'arping -I eth0 192.0.2.50   # Linux: is it reachable on this segment'],
    care: 'Only works on your own segment. Two different MAC addresses answering for one address means an address conflict.',
    lab: 'arp -a works in the Network lab. Ping something first, then run it.' },

  { id: 'qemu', name: 'QEMU', group: ENG_GROUPS[3], what: 'A general emulator and virtualiser. It can run whole machines of many types.',
    use: 'Test an operating system, an image or an odd architecture without real hardware.',
    cmds: ['qemu-img create -f qcow2 disk.qcow2 20G', 'qemu-system-x86_64 -m 2048 -hda disk.qcow2 -cdrom installer.iso'],
    care: 'Keep lab VMs off customer networks and never load customer data into them.' },
  { id: 'proxmox', name: 'Proxmox', group: ENG_GROUPS[3], what: 'A platform for running many virtual machines and containers from a web interface.',
    use: 'A home or work lab: build practice servers, routers and clients and snapshot them.',
    cmds: ['qm list   # list VMs (on the host)', 'qm snapshot 100 before-change   # snapshot VM 100', 'pct list   # list containers'],
    care: 'Snapshot before every experiment. A snapshot is not a backup.' },
  { id: 'zfs', name: 'ZFS and Ceph', group: ENG_GROUPS[3], what: 'Storage systems for large amounts of data. ZFS manages disks and snapshots on one server; Ceph spreads storage across a cluster.',
    use: 'Learn how snapshots, checksums and replication work, and how storage scales.',
    cmds: ['zpool status', 'zfs list', 'zfs snapshot pool/data@before-change', 'ceph -s   # cluster health'],
    care: 'Read-only commands first. Destroying a pool or dataset cannot be undone.' },

  { id: 'python', name: 'Python', group: ENG_GROUPS[4], what: 'A general-purpose scripting language with a huge library ecosystem. Good for gluing tools together.',
    use: 'Parse logs, call APIs, automate repetitive jobs, build small tools.',
    cmds: ['python3 -m venv .venv', 'python3 -m http.server 8000   # share a folder on your network, briefly', 'python3 -c "import socket; print(socket.gethostbyname(\'example.com\'))"'],
    care: 'Work in a virtual environment. Check a package before installing it. http.server has no sign-in, so stop it when done and never serve customer files.' },
  { id: 'powershell', name: 'PowerShell', group: ENG_GROUPS[4], what: 'The Windows scripting shell, built in. It works with objects rather than plain text.',
    use: 'Quick, built-in checks and fixes on Windows without installing anything.',
    cmds: ['Get-Help Get-Service -Examples', 'Get-Service | Where-Object Status -eq Stopped', 'Test-NetConnection 192.0.2.50 -Port 9100', 'Get-WinEvent -LogName System -MaxEvents 20'],
    care: 'Read what a script does before running it, especially one pasted from the internet. Prefer -WhatIf where a command offers it.',
    lab: 'Test-NetConnection works in the Network lab.' },
  { id: 'busybox', name: 'BusyBox', group: ENG_GROUPS[4], what: 'One small program that provides many common Unix commands. Common in containers, routers and rescue systems.',
    use: 'When you land on a minimal system with few tools.',
    cmds: ['busybox --list   # which commands this build has', 'busybox ls /'],
    care: 'Options differ from the full versions of the same commands, so check --help.' },
  { id: 'dos2unix', name: 'dos2unix and unix2dos', group: ENG_GROUPS[4], what: 'Convert line endings between Windows (CRLF) and Unix (LF) text files.',
    use: 'A script or config someone sent fails with odd errors or a stray ^M. Wrong line endings are a classic cause.',
    cmds: ['file script.sh   # reports "with CRLF line terminators" if affected', 'dos2unix script.sh', 'unix2dos notes.txt'],
    care: 'Convert a copy if the file matters. Do not run it over binary files.' },
  { id: 'nvim', name: 'Neovim', group: ENG_GROUPS[4], what: 'A modern, keyboard-driven text editor, descended from vi.',
    use: 'Editing config files over ssh, where vi or vim is often the only editor.',
    cmds: ['nvim file.conf', 'i   # insert mode;  Esc to leave it', ':wq   # save and quit;   :q!   # quit without saving', '/text   # search;   :%s/old/new/g   # replace all'],
    care: 'Take a copy of a config file before editing it.' },

  { id: 'ansible', name: 'Ansible', group: ENG_GROUPS[5], what: 'Automation by describing the state you want in files, applied over ssh with no agent to install.',
    use: 'Repeatable changes across many machines, so every one is configured the same way.',
    cmds: ['ansible all -i inventory.ini -m ping', 'ansible-playbook -i inventory.ini site.yml --check --diff   # dry run, show changes', 'ansible-playbook -i inventory.ini site.yml'],
    care: 'Always run --check first, and start on one test machine. Keep secrets in an encrypted store, not in playbooks.' },
  { id: 'vault', name: 'Vault (secrets manager)', group: ENG_GROUPS[5], what: 'A server that stores secrets and hands them out to people and programs under access rules, with an audit trail.',
    use: 'Stop passwords and keys living in scripts and chat. Learn the idea even if you use another product.',
    cmds: ['vault status', 'vault kv get secret/example'],
    care: 'Typing a secret into a command line can leave it in shell history. Use prompts or files. ForgeTools never stores passwords.' },
  { id: 'opensearch', name: 'OpenSearch', group: ENG_GROUPS[5], what: 'A search and analytics engine with dashboards and alerting. Often used to collect and search logs, SIEM style.',
    use: 'Search and alert across large volumes of logs from many systems.',
    cmds: ['curl -s http://localhost:9200/_cluster/health?pretty   # health of a local node'],
    care: 'Logs are customer data. Control who can read them and how long they are kept. Treat it as a project, not a quick tool.' },

  { id: 'tor', name: 'Tor Browser', group: ENG_GROUPS[6], what: 'A browser that routes traffic through a volunteer network, hiding where you connect from.',
    use: 'Looking at your own organisation or a customer from the outside, for example what is publicly visible or reachable.',
    cmds: [],
    care: 'Check company policy and the law before using it for work. Do not sign in to customer or company accounts through it, and do not use it to probe systems you are not authorised to test.' },
  { id: 'postman', name: 'Postman', group: ENG_GROUPS[6], what: 'A graphical tool for building, sending and saving API requests.',
    use: 'Explore and test an API without writing code. curl does the same from a terminal.',
    cmds: [],
    care: 'Keep tokens in environment variables, and check whether your collections sync to a cloud workspace before saving anything sensitive.' },

  { id: 'dotnet', name: 'Java with Spring, C# with .NET', group: ENG_GROUPS[7], what: 'Two mainstream enterprise platforms for building internal systems.',
    use: 'When a process (build, server or network requests and approvals) needs a small purpose-built internal system rather than a bought product, these are the languages employers already support.',
    cmds: [],
    care: 'An internal tool still needs ownership, access control and review. Agree it with the people who will run it.' },
];
