/** Windows event reference for first-line security and fault triage. General, documented event meanings. */
export type EventGroup = 'Sign-in' | 'Accounts and groups' | 'Changes and persistence' | 'Remote access' | 'Defender and firewall' | 'System health' | 'Updates and software';

export interface WinEvent { id: string; log: string; group: EventGroup; title: string; meaning: string; look: string }

export const EVENT_GROUPS: EventGroup[] = ['Sign-in', 'Accounts and groups', 'Changes and persistence', 'Remote access', 'Defender and firewall', 'System health', 'Updates and software'];

export const EVENTS: WinEvent[] = [
  { id: '4624', log: 'Security', group: 'Sign-in', title: 'Successful logon', meaning: 'An account signed in. The logon type says how.', look: 'Logon type, account, source address and workstation. A type 10 from an unexpected place, or a sign-in at an odd hour, deserves a look.' },
  { id: '4625', log: 'Security', group: 'Sign-in', title: 'Failed logon', meaning: 'A sign-in attempt failed.', look: 'Account, source, logon type and the sub-status code. Many failures for one account is guessing; one failure per account across many accounts is spraying.' },
  { id: '4634', log: 'Security', group: 'Sign-in', title: 'Logoff', meaning: 'A logon session ended.', look: 'Pair with the matching 4624 by logon ID to get session length.' },
  { id: '4647', log: 'Security', group: 'Sign-in', title: 'User started a logoff', meaning: 'The user chose to sign out.', look: 'Interactive and remote sessions.' },
  { id: '4648', log: 'Security', group: 'Sign-in', title: 'Logon using explicit credentials', meaning: 'A process signed in as another account (run as, mapped drive with other credentials).', look: 'Which process and which target. Unexpected use can signal lateral movement.' },
  { id: '4672', log: 'Security', group: 'Sign-in', title: 'Special privileges assigned to a logon', meaning: 'An administrator-level account signed in.', look: 'Expected for admins. Unexpected for ordinary users.' },
  { id: '4740', log: 'Security', group: 'Sign-in', title: 'Account locked out', meaning: 'Too many bad attempts locked an account.', look: 'The caller computer name shows where the bad attempts came from, such as a phone with an old password.' },
  { id: '4767', log: 'Security', group: 'Sign-in', title: 'Account unlocked', meaning: 'A locked account was unlocked.', look: 'Who unlocked it, and whether a lockout followed.' },
  { id: '4768', log: 'Security (domain controller)', group: 'Sign-in', title: 'Kerberos ticket requested', meaning: 'A domain sign-in asked for its first ticket.', look: 'Failures show a status code. Useful when tracking a domain sign-in problem.' },
  { id: '4771', log: 'Security (domain controller)', group: 'Sign-in', title: 'Kerberos pre-authentication failed', meaning: 'Wrong password or clock difference for a domain sign-in.', look: 'Check the status and whether the device clock is correct.' },
  { id: '4776', log: 'Security (domain controller)', group: 'Sign-in', title: 'NTLM credential check', meaning: 'A domain controller checked an account using NTLM.', look: 'Failure codes show bad password, unknown user or disabled account.' },
  { id: '4720', log: 'Security', group: 'Accounts and groups', title: 'User account created', meaning: 'A new local or domain account exists.', look: 'Who created it and whether it was expected. A surprise new account is a red flag.' },
  { id: '4722', log: 'Security', group: 'Accounts and groups', title: 'User account enabled', meaning: 'A disabled account was switched on.', look: 'Compare with leavers and starters lists.' },
  { id: '4723', log: 'Security', group: 'Accounts and groups', title: 'Password change attempted', meaning: 'An account tried to change its own password.', look: 'Success or failure, and who.' },
  { id: '4724', log: 'Security', group: 'Accounts and groups', title: 'Password reset attempted', meaning: 'Someone tried to reset another account\'s password.', look: 'The actor and the target. Match it to a ticket.' },
  { id: '4725', log: 'Security', group: 'Accounts and groups', title: 'User account disabled', meaning: 'An account was switched off.', look: 'Expected for leavers; unexpected otherwise.' },
  { id: '4726', log: 'Security', group: 'Accounts and groups', title: 'User account deleted', meaning: 'An account was removed.', look: 'Who and when. Hard to undo.' },
  { id: '4732', log: 'Security', group: 'Accounts and groups', title: 'Member added to a local group', meaning: 'An account joined a local group such as Administrators.', look: 'Administrators or Remote Desktop Users membership changes are the important ones.' },
  { id: '4728', log: 'Security (domain controller)', group: 'Accounts and groups', title: 'Member added to a global security group', meaning: 'A domain group gained a member.', look: 'Domain Admins and similar groups especially.' },
  { id: '4756', log: 'Security (domain controller)', group: 'Accounts and groups', title: 'Member added to a universal security group', meaning: 'A universal group gained a member.', look: 'Privileged groups especially.' },
  { id: '4738', log: 'Security', group: 'Accounts and groups', title: 'User account changed', meaning: 'Properties of an account changed.', look: 'Which attribute changed, such as password-never-expires.' },
  { id: '4688', log: 'Security', group: 'Changes and persistence', title: 'New process created', meaning: 'A program started. Only logged when process auditing is on.', look: 'The command line (if enabled), parent process and account. Admin tools launched by Office apps are suspicious.' },
  { id: '4697', log: 'Security', group: 'Changes and persistence', title: 'Service installed (Security log)', meaning: 'A service was installed on the system.', look: 'Service name and file path. Unknown paths in user folders are suspicious.' },
  { id: '7045', log: 'System', group: 'Changes and persistence', title: 'New service installed', meaning: 'The service control manager registered a new service.', look: 'Name, file path, start type and account. Common persistence method.' },
  { id: '7040', log: 'System', group: 'Changes and persistence', title: 'Service start type changed', meaning: 'A service was set to automatic, manual or disabled.', look: 'A protection service set to disabled is a warning sign.' },
  { id: '4698', log: 'Security', group: 'Changes and persistence', title: 'Scheduled task created', meaning: 'A task was added.', look: 'Task name, action and the account. Unknown tasks that run scripts are suspicious.' },
  { id: '4699', log: 'Security', group: 'Changes and persistence', title: 'Scheduled task deleted', meaning: 'A task was removed.', look: 'Matches to an uninstall or a clean-up.' },
  { id: '4702', log: 'Security', group: 'Changes and persistence', title: 'Scheduled task updated', meaning: 'A task was changed.', look: 'What it runs now.' },
  { id: '4657', log: 'Security', group: 'Changes and persistence', title: 'Registry value modified', meaning: 'A watched registry value changed.', look: 'Only appears when auditing is set. Run keys are common targets.' },
  { id: '4104', log: 'PowerShell Operational', group: 'Changes and persistence', title: 'PowerShell script block logged', meaning: 'The text of a PowerShell script block that ran.', look: 'Encoded or obfuscated text, downloads and credential access.' },
  { id: '1102', log: 'Security', group: 'Changes and persistence', title: 'Audit log cleared', meaning: 'Someone cleared the Security log.', look: 'Rarely benign on a managed machine. Treat as important.' },
  { id: '104', log: 'System', group: 'Changes and persistence', title: 'An event log was cleared', meaning: 'A log other than Security was cleared.', look: 'Who cleared it and why.' },
  { id: '4719', log: 'Security', group: 'Changes and persistence', title: 'Audit policy changed', meaning: 'What the machine records was changed.', look: 'Auditing switched off before other activity is a concern.' },
  { id: '4616', log: 'Security', group: 'Changes and persistence', title: 'System time changed', meaning: 'The clock was changed.', look: 'Large jumps can break Kerberos and hide activity.' },
  { id: '1149', log: 'TerminalServices-RemoteConnectionManager', group: 'Remote access', title: 'Remote Desktop authentication succeeded', meaning: 'A remote user got past network authentication.', look: 'Source address and account.' },
  { id: '21', log: 'TerminalServices-LocalSessionManager', group: 'Remote access', title: 'Remote Desktop session logon', meaning: 'A remote session started.', look: 'Account and source. Pair with 24 and 25.' },
  { id: '24', log: 'TerminalServices-LocalSessionManager', group: 'Remote access', title: 'Remote Desktop session disconnected', meaning: 'A session ended or was dropped.', look: 'Timing against the user\'s report.' },
  { id: '25', log: 'TerminalServices-LocalSessionManager', group: 'Remote access', title: 'Remote Desktop session reconnected', meaning: 'A disconnected session was picked up again.', look: 'Unexpected reconnects from a different source.' },
  { id: '4778', log: 'Security', group: 'Remote access', title: 'Session reconnected', meaning: 'A session was reconnected to a window station.', look: 'Source address and client name.' },
  { id: '5140', log: 'Security', group: 'Remote access', title: 'Network share accessed', meaning: 'A share was opened by a user.', look: 'Share name, account and source. Many different shares fast is scanning.' },
  { id: '1116', log: 'Windows Defender Operational', group: 'Defender and firewall', title: 'Malware detected', meaning: 'Defender found something.', look: 'Threat name, path and action taken.' },
  { id: '1117', log: 'Windows Defender Operational', group: 'Defender and firewall', title: 'Action taken on malware', meaning: 'Defender removed or quarantined a threat.', look: 'Confirm it succeeded and that the file is gone.' },
  { id: '5001', log: 'Windows Defender Operational', group: 'Defender and firewall', title: 'Real-time protection turned off', meaning: 'Protection was disabled.', look: 'Who or what did it, and whether a different product took over.' },
  { id: '5007', log: 'Windows Defender Operational', group: 'Defender and firewall', title: 'Defender configuration changed', meaning: 'A setting such as an exclusion was changed.', look: 'New exclusions for folders or processes are a red flag.' },
  { id: '4946', log: 'Security', group: 'Defender and firewall', title: 'Firewall rule added', meaning: 'A new Windows Firewall rule exists.', look: 'Name, program, direction and action.' },
  { id: '4947', log: 'Security', group: 'Defender and firewall', title: 'Firewall rule modified', meaning: 'A rule was changed.', look: 'What changed.' },
  { id: '4948', log: 'Security', group: 'Defender and firewall', title: 'Firewall rule deleted', meaning: 'A rule was removed.', look: 'Whether it protected something.' },
  { id: '6416', log: 'Security', group: 'Defender and firewall', title: 'New external device recognised', meaning: 'A USB or similar device was plugged in.', look: 'Device name and vendor, useful for data-leak questions.' },
  { id: '41', log: 'System (Kernel-Power)', group: 'System health', title: 'System rebooted without a clean shutdown', meaning: 'The machine lost power, crashed or was reset.', look: 'Bug check code, and what happened just before.' },
  { id: '6008', log: 'System', group: 'System health', title: 'Previous shutdown was unexpected', meaning: 'Windows notes the last shutdown was not clean.', look: 'Often follows event 41.' },
  { id: '1074', log: 'System', group: 'System health', title: 'Shutdown or restart initiated', meaning: 'A process or user asked for a restart or shutdown.', look: 'Reason and which process. Shows planned restarts.' },
  { id: '6005', log: 'System', group: 'System health', title: 'Event log service started', meaning: 'Marks a boot.', look: 'Pair with 6006 to see uptime periods.' },
  { id: '6006', log: 'System', group: 'System health', title: 'Event log service stopped', meaning: 'Marks a clean shutdown.', look: 'Missing before a boot means it was not clean.' },
  { id: '7034', log: 'System', group: 'System health', title: 'Service crashed unexpectedly', meaning: 'A service stopped without being asked.', look: 'Service name and how often.' },
  { id: '7036', log: 'System', group: 'System health', title: 'Service changed state', meaning: 'A service started or stopped.', look: 'Use to line up a fault with a service.' },
  { id: '1000', log: 'Application', group: 'System health', title: 'Application error', meaning: 'A program crashed.', look: 'Faulting application, module and exception code.' },
  { id: '7', log: 'System (Disk)', group: 'System health', title: 'Bad block on a disk', meaning: 'The disk reported a bad block.', look: 'Repeats point to a failing disk. Back up first.' },
  { id: '11', log: 'System (Disk)', group: 'System health', title: 'Disk controller error', meaning: 'The driver found a controller error.', look: 'Check cables, controller and drive health.' },
  { id: '129', log: 'System (storage driver)', group: 'System health', title: 'Reset to device', meaning: 'A storage request timed out and was reset.', look: 'Repeated entries point at the drive, cable or driver.' },
  { id: '153', log: 'System (Disk)', group: 'System health', title: 'I/O retried', meaning: 'A disk operation had to be retried.', look: 'A growing count points to storage trouble.' },
  { id: '55', log: 'System (Ntfs)', group: 'System health', title: 'File system corruption', meaning: 'NTFS found damage on a volume.', look: 'Back up and run a proper check on the drive.' },
  { id: '19', log: 'WindowsUpdateClient', group: 'Updates and software', title: 'Update installed', meaning: 'An update installed successfully.', look: 'Name of the update and when.' },
  { id: '20', log: 'WindowsUpdateClient', group: 'Updates and software', title: 'Update failed', meaning: 'An update did not install.', look: 'Error code and the update name.' },
  { id: '1033', log: 'Application (MsiInstaller)', group: 'Updates and software', title: 'Installer finished', meaning: 'An MSI installation completed.', look: 'Product name and result.' },
];

export const LOGON_TYPES: Array<[string, string]> = [
  ['2', 'Interactive: someone at the keyboard'],
  ['3', 'Network: a share, printer or similar'],
  ['4', 'Batch: a scheduled task'],
  ['5', 'Service: a service starting under an account'],
  ['7', 'Unlock: screen unlocked'],
  ['8', 'Network with clear-text credentials'],
  ['9', 'New credentials: run-as with different network credentials'],
  ['10', 'Remote interactive: Remote Desktop'],
  ['11', 'Cached interactive: signed in without reaching a domain controller'],
];

export const FAIL_CODES: Array<[string, string]> = [
  ['0xC000006D', 'Sign-in failed (general); see the sub-status below'],
  ['0xC000006A', 'Right username, wrong password'],
  ['0xC0000064', 'Username does not exist'],
  ['0xC0000234', 'Account is locked out'],
  ['0xC0000072', 'Account is disabled'],
  ['0xC0000071', 'Password has expired'],
  ['0xC0000193', 'Account has expired'],
  ['0xC000006F', 'Sign-in outside allowed hours'],
  ['0xC0000070', 'Sign-in from a workstation that is not allowed'],
];

export const EVENT_COMMANDS: Array<[string, string]> = [
  ['Last 20 failed logons', 'Get-WinEvent -FilterHashtable @{LogName="Security"; Id=4625} -MaxEvents 20 | Format-List TimeCreated, Message'],
  ['Events in the last 24 hours', 'Get-WinEvent -FilterHashtable @{LogName="System"; StartTime=(Get-Date).AddDays(-1)} | Select TimeCreated, Id, ProviderName, Message -First 50'],
  ['New services', 'Get-WinEvent -FilterHashtable @{LogName="System"; Id=7045} -MaxEvents 20 | Format-List TimeCreated, Message'],
  ['Unexpected shutdowns', 'Get-WinEvent -FilterHashtable @{LogName="System"; Id=41,6008} -MaxEvents 10 | Format-List TimeCreated, Id, Message'],
  ['Open Event Viewer', 'eventvwr.msc'],
];
