/** Original generic checklists for hardening and phishing triage. */
export interface CheckList { id: string; title: string; intro: string; items: string[] }

export const HARDENING: CheckList[] = [
  { id: 'win', title: 'Windows workstation', intro: 'Check against the customer\'s own standard first. Tick what you have confirmed.', items: [
    'Windows and Microsoft Office are receiving updates and the device is on a supported version',
    'Disk encryption is on and the recovery key is held by the right place, not on the device',
    'Built-in protection is on, up to date and not showing exclusions nobody can explain',
    'The firewall is on for every network profile',
    'Users run as standard users; admin rights are held by a separate account',
    'The local administrator account is unique per device or managed by a tool',
    'Screen lock is set to a short idle time and needs a sign-in',
    'Remote Desktop is off unless needed, and needs network-level authentication when on',
    'Old protocols such as SMBv1 are off',
    'Autorun and autoplay for removable media are off',
    'Unneeded accounts, shares and startup items are removed',
    'Event logs are large enough to cover several weeks',
    'The device is in the customer\'s management and asset records' ] },
  { id: 'm365', title: 'Microsoft 365 tenant', intro: 'Settings to confirm with the person who owns the tenant. Do not change them without approval.', items: [
    'Multi-factor sign-in is required for every user, admins first',
    'Old sign-in methods that skip multi-factor are blocked',
    'Admin accounts are separate from daily-use accounts and are few in number',
    'Mailboxes are checked for unexpected forwarding rules',
    'External auto-forwarding is blocked',
    'Anti-phishing and safe attachment features are on at the level the licence allows',
    'SPF, DKIM and DMARC are set for the sending domain, with DMARC moving beyond monitoring',
    'Sign-in and audit logging is on and kept long enough',
    'Guest and external sharing settings match what the customer wants',
    'Licences and accounts for leavers are removed promptly',
    'Mobile devices needing mail must meet a basic policy such as a PIN',
    'A break-glass admin account exists, is protected and is tested' ] },
  { id: 'fw', title: 'Firewall and router', intro: 'Review from the management page, read-only first. Capture the current settings before any change.', items: [
    'Management page is not reachable from the internet',
    'The default admin name and password are changed and held in the approved password manager',
    'Firmware is current, or the gap is known and recorded',
    'Inbound rules and port forwards each have a named purpose and owner',
    'No "any to any" allow rules remain',
    'Remote access uses a VPN with multi-factor rather than open ports',
    'Guest Wi-Fi is separate from the business network',
    'Wi-Fi uses modern encryption and a strong key; the key is not the default',
    'Unused services such as UPnP and remote management are off',
    'Logs are kept somewhere that survives a restart',
    'A backup of the configuration exists and was stored safely',
    'DNS and time settings are sensible' ] },
  { id: 'print', title: 'Printer and copier admin settings', intro: 'Network printers are computers with long-lived passwords. Review with approval.', items: [
    'The administrator password is not the factory default and is recorded in the approved place',
    'The web interface uses an encrypted connection where supported',
    'Unused protocols and services such as old print, discovery and file transfer are off',
    'Scan-to-email and scan-to-folder use a dedicated account with the least access',
    'The scan account password is not shared with a person\'s login',
    'Address books hold only what is needed',
    'Stored jobs and the internal drive are cleared or encrypted, as the customer requires',
    'Firmware is current, or the gap is known and recorded',
    'The device has a fixed or reserved address and appears in the asset list',
    'Date, time and time source are correct',
    'Remote service features are known, approved and documented',
    'Panel lock or user authentication is on where the customer wants it' ] },
];

export const PHISHING: CheckList = { id: 'phish', title: 'Phishing triage', intro: 'Work through in order. Stop and escalate at the first sign someone entered credentials or opened a file.', items: [
  'Do not click links or open attachments to investigate',
  'Ask whether the user clicked, opened, replied or typed anything in',
  'If they did, stop here and follow the customer\'s incident process',
  'Note the sender, subject and time in the ticket without copying private content',
  'Check the sender address, not just the display name',
  'Look for urgency, threats, gift offers or unusual payment requests',
  'Hover over links to see where they really go, without clicking',
  'Check the full header for SPF, DKIM, DMARC and mismatched domains',
  'Look for the same message in other mailboxes and remove it where you have approval',
  'Block the sender or link only through the customer\'s agreed route',
  'If credentials were entered, reset the password, revoke sessions and check for forwarding rules',
  'Tell the user what you found and remind them how to report the next one',
  'Record the outcome and any follow-up in the ticket' ] };

export const ALERT_TYPES: Array<[string, string, string]> = [
  ['Impossible travel', 'Two sign-ins from places too far apart for the time between them', 'Check for a VPN or phone before assuming compromise; then check the sign-in method and any new rules'],
  ['Unfamiliar sign-in', 'A sign-in from a new device or place', 'Ask the user; look at the app used and whether multi-factor was met'],
  ['Brute force or spray', 'Many failures against one account or one failure across many accounts', 'Look at the source, whether any attempt succeeded and whether the account is exposed'],
  ['Malware detected', 'Protection found and acted on a file', 'Confirm it was removed, how it arrived and whether other devices saw it'],
  ['Suspicious inbox rule', 'A rule hides, deletes or forwards mail', 'Treat as likely compromise; escalate'],
  ['New admin or group change', 'An account gained high privilege', 'Match it to a request; if there is none, escalate'],
  ['Mass file activity', 'Many files changed, renamed or deleted fast', 'Could be ransomware; isolate the device through the agreed route and escalate'],
  ['Outbound spike', 'Unusual volume of data leaving', 'Find the device and process; check for backup or sync tools first'],
  ['Disabled protection', 'Security software or logging turned off', 'Find who or what did it and restore it'],
  ['Port scan or probe', 'One address trying many ports', 'Normal from internet noise; concerning from inside the network'],
] ;
