/** Common network ports and what they are for. Original reference notes. */
export interface PortInfo { port: number; proto: 'TCP' | 'UDP' | 'TCP/UDP'; name: string; note: string; care?: string }

export const PORTS: PortInfo[] = [
  { port: 20, proto: 'TCP', name: 'FTP data', note: 'File transfer, data channel', care: 'Clear text; prefer SFTP' },
  { port: 21, proto: 'TCP', name: 'FTP control', note: 'File transfer, commands', care: 'Clear text; prefer SFTP' },
  { port: 22, proto: 'TCP', name: 'SSH / SFTP', note: 'Secure shell and secure file transfer' },
  { port: 23, proto: 'TCP', name: 'Telnet', note: 'Old remote shell', care: 'Clear text; should be off' },
  { port: 25, proto: 'TCP', name: 'SMTP', note: 'Mail between servers' },
  { port: 53, proto: 'TCP/UDP', name: 'DNS', note: 'Name lookups; UDP for small answers, TCP for large' },
  { port: 67, proto: 'UDP', name: 'DHCP server', note: 'Hands out addresses' },
  { port: 68, proto: 'UDP', name: 'DHCP client', note: 'Receives addresses' },
  { port: 69, proto: 'UDP', name: 'TFTP', note: 'Simple file transfer, often firmware or boot', care: 'No authentication' },
  { port: 80, proto: 'TCP', name: 'HTTP', note: 'Web, not encrypted. Many printer pages use it' },
  { port: 88, proto: 'TCP/UDP', name: 'Kerberos', note: 'Domain sign-in tickets' },
  { port: 110, proto: 'TCP', name: 'POP3', note: 'Old mail download', care: 'Clear text unless wrapped in TLS on 995' },
  { port: 123, proto: 'UDP', name: 'NTP', note: 'Time sync. Bad time breaks sign-in and certificates' },
  { port: 135, proto: 'TCP', name: 'RPC endpoint mapper', note: 'Windows remote calls', care: 'Do not expose to the internet' },
  { port: 137, proto: 'UDP', name: 'NetBIOS name', note: 'Old Windows name service' },
  { port: 139, proto: 'TCP', name: 'NetBIOS session', note: 'Old file sharing', care: 'Prefer 445 and keep internal' },
  { port: 143, proto: 'TCP', name: 'IMAP', note: 'Mail access', care: 'Clear text unless wrapped in TLS on 993' },
  { port: 161, proto: 'UDP', name: 'SNMP', note: 'Device monitoring, printer counters and status', care: 'Change default community strings' },
  { port: 162, proto: 'UDP', name: 'SNMP trap', note: 'Alerts sent from devices to a monitor' },
  { port: 389, proto: 'TCP/UDP', name: 'LDAP', note: 'Directory lookups, address books, sign-in', care: 'Clear text; prefer 636' },
  { port: 443, proto: 'TCP', name: 'HTTPS', note: 'Encrypted web. Also used by many VPNs and cloud services' },
  { port: 445, proto: 'TCP', name: 'SMB', note: 'Windows file and printer sharing; scan-to-folder uses it', care: 'Never expose to the internet' },
  { port: 465, proto: 'TCP', name: 'SMTPS', note: 'Mail submission with TLS from the start' },
  { port: 500, proto: 'UDP', name: 'IKE', note: 'Start of an IPsec VPN' },
  { port: 514, proto: 'UDP', name: 'Syslog', note: 'Log messages sent to a collector' },
  { port: 515, proto: 'TCP', name: 'LPD', note: 'Older printing protocol' },
  { port: 587, proto: 'TCP', name: 'SMTP submission', note: 'Mail submission with STARTTLS; common for scan-to-email' },
  { port: 631, proto: 'TCP', name: 'IPP', note: 'Internet Printing Protocol' },
  { port: 636, proto: 'TCP', name: 'LDAPS', note: 'LDAP with TLS' },
  { port: 993, proto: 'TCP', name: 'IMAPS', note: 'IMAP with TLS' },
  { port: 995, proto: 'TCP', name: 'POP3S', note: 'POP3 with TLS' },
  { port: 1433, proto: 'TCP', name: 'SQL Server', note: 'Database', care: 'Keep internal' },
  { port: 1701, proto: 'UDP', name: 'L2TP', note: 'Tunnel used with IPsec VPNs' },
  { port: 1723, proto: 'TCP', name: 'PPTP', note: 'Old VPN', care: 'Weak; replace' },
  { port: 3306, proto: 'TCP', name: 'MySQL', note: 'Database', care: 'Keep internal' },
  { port: 3389, proto: 'TCP/UDP', name: 'Remote Desktop', note: 'Windows remote desktop', care: 'Never open to the internet; use a VPN' },
  { port: 4500, proto: 'UDP', name: 'IPsec NAT traversal', note: 'IPsec VPN through NAT' },
  { port: 5060, proto: 'TCP/UDP', name: 'SIP', note: 'Phone call setup', care: 'Often attacked; restrict sources' },
  { port: 5061, proto: 'TCP', name: 'SIP over TLS', note: 'Encrypted phone call setup' },
  { port: 5353, proto: 'UDP', name: 'mDNS', note: 'Local discovery, used by many printers and phones' },
  { port: 5900, proto: 'TCP', name: 'VNC', note: 'Remote screen sharing', care: 'Keep internal or tunnel it' },
  { port: 5985, proto: 'TCP', name: 'WinRM HTTP', note: 'PowerShell remoting', care: 'Internal only' },
  { port: 5986, proto: 'TCP', name: 'WinRM HTTPS', note: 'PowerShell remoting with TLS' },
  { port: 9100, proto: 'TCP', name: 'Raw printing', note: 'Direct print jobs to a printer; the standard TCP/IP port uses it', care: 'Anyone who can reach it can print' },
  { port: 10000, proto: 'UDP', name: 'RTP range start', note: 'Phone call audio uses a wide UDP range such as 10000 to 20000' },
  { port: 51820, proto: 'UDP', name: 'WireGuard', note: 'Common default for this VPN' },
];

export const PORT_RANGES: Array<[string, string]> = [
  ['0 to 1023', 'Well-known ports, used by standard services'],
  ['1024 to 49151', 'Registered ports, used by applications'],
  ['49152 to 65535', 'Dynamic ports, picked at random for outgoing connections'],
];

export const PORT_COMMANDS: Array<[string, string]> = [
  ['Test one port from Windows', 'Test-NetConnection -ComputerName <host-or-IP> -Port 445'],
  ['What is listening on this PC', 'netstat -ano | findstr LISTENING'],
  ['Which program owns a port number', 'Get-NetTCPConnection -LocalPort 3389 | Select LocalAddress, State, OwningProcess'],
  ['Firewall rules for a port', 'Get-NetFirewallPortFilter -Protocol TCP | Where LocalPort -eq 445'],
];
